### PR TITLE
BIGTOP-3579. Spark smoke test fails on Debian 9 and Ubuntu 18.04.

### PR DESCRIPTION
**Pull request by sekikn**
https://issues.apache.org/jira/browse/BIGTOP-3579

### CODE REVIEW

**Comment by sekikn** [comment]
Tested on Debian 9 and CentOS 7 (as regression).

**Review by iwasakims — APPROVED** [review]
+1. I was able to reproduce the issue on Ubuntu 18.04 x86_64 and the patch worked.

**Comment by iwasakims** [comment]
@sekikn It took over 800 seconds to apply the manifest in the docker provisioned container. Do we have enough long timeout on CI environment?

**Comment by sekikn** [comment]
Thanks for the review @iwasakims. Timeout is set to 10h (!) on our CI environment, so it's enough. It may be too long conversely :)

**Pull request merged**
