### PR TITLE
BIGTOP-3528. Bump Oozie to 5.2.0

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3528

We need to fix following issues

* compilation error due to version mismatch
  * hive
  * hadoop
  * log4j2
  * httpclient 
* migration from Tomcat to Jetty [OOZIE-2317](https://issues.apache.org/jira/browse/OOZIE-2317)

### CODE REVIEW

**Comment by iwasakims** [comment]
I fixed compilation erros and issues in install_oozie.sh. init script should be fixed too for [OOZIE-2317](https://issues.apache.org/jira/browse/OOZIE-2317).

**Comment by sekikn** [comment]
@iwasakims Thank you for addressing this! A few comments:

* Oozie 5.2.1 has been released recently. How about upgrading to that?

* On Ubuntu 18.04 and 20.04, this PR failed with the following error.

```
ln -s -f /var/lib/oozie/ext-2.2 debian/oozie/usr/lib/oozie/webapps/oozie/ext-2.2
ln: failed to create symbolic link 'debian/oozie/usr/lib/oozie/webapps/oozie/ext-2.2': No such file or directory
make[1]: *** [debian/rules:40: override_dh_auto_install] Error 1
make[1]: Leaving directory '/home/vagrant/bigtop/output/oozie/oozie-5.2.0'
make: *** [debian/rules:27: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b
 failed

> Task :oozie-deb FAILED
```

**Comment by iwasakims** [comment]
> Oozie 5.2.1 has been released recently. How about upgrading to that?

Sure. The patch0 is applicable without update.

**Comment by iwasakims** [comment]
> ln -s -f /var/lib/oozie/ext-2.2 debian/oozie/usr/lib/oozie/webapps/oozie/ext-2.2
> ln: failed to create symbolic link 'debian/oozie/usr/lib/oozie/webapps/oozie/ext-2.2': No such file or directory

fixed this error.

**Comment by sekikn** [comment]
+1, I successfully built and deployed Oozie 5.2.1 with this PR on CentOS 7, 8, Debian 10, and Ubuntu 18.04.
We possibly have to fix its puppet manifest and/or smoke test additionally, because the smoke test failed on my environment. But it can be addressed as another follow-up issue.
Thanks @iwasakims for working on this!

**Pull request merged**
