### PR TITLE
BIGTOP-3281. Bump Tez to 0.9.2.

### PR DESCRIPTION
**Pull request by iwasakims**

### CODE REVIEW

**Comment by iwasakims** [comment]
minimal manual testing on single node docker provisioned cluster:

```
$ cd provisioner/docker
$ cat config.yaml
docker:
        memory_limit: "12g"
        image: "bigtop/puppet:trunk-centos-7"

distro: centos
components: [hdfs, yarn, mapreduce, tez]
enable_local_repo: true
smoke_test_components: [hdfs]

$ ./docker-hadoop.sh -c 1
$ ./docker-hadoop.sh --exec 1 /bin/bash
[root@d54010111793 /]# echo 'export HADOOP_CLASSPATH=/etc/tez/conf:/usr/lib/tez/*:/usr/lib/tez/lib/*:$HADOOP_CLASSPATH' >> /etc/hadoop/conf/hadoop-env.sh
[root@d54010111793 /]# hdfs dfs -put /etc/hosts /tmp/
[root@d54010111793 /]# yarn jar /usr/lib/tez/tez-examples-0.9.2.jar wordcount /tmp/hosts /tmp/out1
[root@d54010111793 /]# hdfs dfs -cat /tmp/out1/part-v001-o000-r-00000
127.0.0.1	1
172.17.0.2	1
d54010111793	1
d54010111793.bigtop.apache.org	1
localhost	1
```

**Comment by sekikn** [comment]
+1, confirmed the PR worked on the following distros:

- CentOS 7 and 8
- Debian 9 and 10
- Ubuntu 16.04 and 18.04

**Comment by iwasakims** [comment]
Thanks, @sekikn .

**Comment by evans-ye** [comment]
+1.

**Pull request merged**
