### PR TITLE
BIGTOP-3295. Fix build failure of hadoop-2.10.0 on CentOS 8

### PR DESCRIPTION
**Pull request by sekikn**

### CODE REVIEW

**Comment by sekikn** [comment]
@iwasakims I submitted a PR based on HADOOP-16739 so that we can build and test other components which depends on Hadoop on CentOS 8.
This PR also fixes an conditional error for Fedora 31 in `bigtop_toolchain/manifests/packages.pp`.

I confirmed that the following commands succeeded:

```
$ cd docker/bigtop-slaves
$ for i in centos-7 centos-8 fedora-31; do ./build.sh trunk-$i; done
$ cd -
$ for i in centos-7 centos-8 fedora-31; do ./gradlew hadoop-clean; ./gradlew hadoop-pkg-ind -POS=$i; done
```

**Comment by evans-ye** [comment]
LGTM. +1.

**Comment by iwasakims** [comment]
Thanks @sekikn . I'm obviously +1(non-binding).

**Comment by iwasakims** [comment]
FYI [HADOOP-16739](https://issues.apache.org/jira/browse/HADOOP-16739) was comitted to trunk, while we still need the patch for hadoop-2.10.x.

**Comment by sekikn** [comment]
Sorry for my late response, just merged into master. Thanks @evans-ye and @iwasakims for reviewing!

**Pull request merged**
