### PR TITLE
BIGTOP-3625. Fix Livy's build failure

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3625

```
[[1;31mERROR[m]   The project org.apache.livy:livy-scala-api_2.12:0.7.1-incubating (/bigtop/build/livy/rpm/BUILD/livy-0.7.1/scala-api/scala-2.12/pom.xml) has 1 error
[[1;31mERROR[m]     'dependencies.dependency.version' for io.netty:netty-all:jar must be a valid version but is '${netty.spark-2.12.version}'. @ org.apache.livy:livy-main:0.7.1-incubating, /bigtop/build/livy/rpm/BUILD/livy-0.7.1/pom.xml, line 329, column 18
```

I replaced the patch1 based on https://github.com/apache/incubator-livy/pull/289 with the one based on https://github.com/apache/incubator-livy/commit/97cf2f75929ef6c152afc468adbead269bd0758f as @elukey suggested in the [BIGTOP-3625](https://issues.apache.org/jira/browse/BIGTOP-3625).

### CODE REVIEW

**Comment by iwasakims** [comment]
I needed additional fixes for Livy 0.7.1 and Spark 3.1.2.

Since scala-maven-plugin 4.2.0 caused following error, I used 4.3.0 instead.

```
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.2.0:compile (scala-compile-first) on project livy-core_2.12: Execution scala-compile-first of goal net.alchim31.maven:scala-maven-plugin:4.2.0:compile failed: An API incompatibility was encountered while executing net.alchim31.maven:scala-maven-plugin:4.2.0:compile: java.lang.NoSuchMethodError: scala.tools.nsc.Settings.nowarn()Lscala/tools/nsc/settings/AbsSettings$AbsSetting;
```

**Comment by iwasakims** [comment]
I also updated the value of spark.bin.download.url and spark.bin.name to the one matching Spark bundled by Bigtop.

**Comment by iwasakims** [comment]
smoke-tests of Livy passed on CentOS 8 container.

```
$ ./docker-hadoop.sh \
   --create 1 \
   --image bigtop/puppet:trunk-centos-8 \
   --memory 16g \
   --repo file:///bigtop-home/output \
   --disable-gpg-check \
   --stack hdfs,yarn,mapreduce,spark,livy \
   --smoke-tests livy
...
Now testing...
:bigtop-tests:smoke-tests:livy:test (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 35.506 secs.

BUILD SUCCESSFUL in 1m 16s
34 actionable tasks: 7 executed, 27 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```

**Comment by elukey** [comment]
LGTM! Built and smoke-tested on Debian-11

+1

**Comment by iwasakims** [comment]
Thanks, @elukey. I merged this.

**Pull request merged**
