### PR TITLE
BIGTOP-3418. Fix Ambari deployment on CentOS 8, Fedora 31 and Debian 10.

### PR DESCRIPTION
**Pull request by sekikn**
Tested on Debian 10 and Fedora 31.

### CODE REVIEW

**Comment by iwasakims** [comment]
While the patch worked for CentOS 8 too, `ambari-server setup` failed due to error on starting PostgreSQL. I'm looking into the cause.
```
Notice: /Stage[main]/Ambari::Server/Exec[server setup]/returns: Configuring ambari database...
Notice: /Stage[main]/Ambari::Server/Exec[server setup]/returns: Checking PostgreSQL...
Notice: /Stage[main]/Ambari::Server/Exec[server setup]/returns: Running initdb: This may take up to a minute.
Notice: /Stage[main]/Ambari::Server/Exec[server setup]/returns: About to start PostgreSQL
Notice: /Stage[main]/Ambari::Server/Exec[server setup]/returns: ERROR: Exiting with exit code 3.
Notice: /Stage[main]/Ambari::Server/Exec[server setup]/returns: REASON: Unable to start PostgreSQL server. Exiting
```

**Comment by iwasakims** [comment]
The cause turned out to be the locale.
```
[root@e175411847c9 /]# cat /var/lib/pgsql/initdb_postgresql.log
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

initdb: invalid locale settings; check LANG and LC_* environment variables
```

`--no-locale` on initdb should be the fix. The cmdline is not configurable in Ambari. Setting environment variable in puppet manifest might be an option.
```
[root@e175411847c9 /]# PGSETUP_INITDB_OPTIONS="--no-locale" /usr/bin/postgresql-setup initdb
WARNING: using obsoleted argument syntax, try --help
WARNING: arguments transformed to: postgresql-setup --initdb --unit postgresql
 * Initializing database in '/var/lib/pgsql/data'
 * Initialized, logs are in /var/lib/pgsql/initdb_postgresql.log
```

**Review by iwasakims — APPROVED** [review]
I'm +1 on the fix here. We should merge this first to see the result of CI. We can address PostgreSQL issue in the follow-up JIRA.

**Comment by iwasakims** [comment]
I filed [BIGTOP-3422](https://issues.apache.org/jira/browse/BIGTOP-3422) for PostgreSQL initdb issue.

**Comment by sekikn** [comment]
@iwasakims Thanks! This PR fixed the problem on Debian 10,
https://ci.bigtop.apache.org/job/Bigtop-trunk-smoke-tests/174/COMPONENTS=ambari.bigtop-utils@ambari,OS=debian-10-amd64-deploy/console
https://ci.bigtop.apache.org/job/Bigtop-trunk-smoke-tests/174/COMPONENTS=ambari.bigtop-utils@ambari,OS=debian-10-arm64-deploy/console

but there's still a PostgreSQL issue on CentOS 8, as you mentioned.
https://ci.bigtop.apache.org/job/Bigtop-trunk-smoke-tests/174/COMPONENTS=ambari.bigtop-utils@ambari,OS=centos-8-x86_64-deploy/console

In addition, starting ambari-agent failed on Fedora 31 for some reason. I'm going to file this as another issue.
https://ci.bigtop.apache.org/job/Bigtop-trunk-smoke-tests/174/COMPONENTS=ambari.bigtop-utils@ambari,OS=fedora-31-aarch64-deploy/console
https://ci.bigtop.apache.org/job/Bigtop-trunk-smoke-tests/174/COMPONENTS=ambari.bigtop-utils@ambari,OS=fedora-31-x86_64-deploy/console

**Pull request merged**
