### PR TITLE
BIGTOP-3427. Deploying GPDB fails due to the paramiko installation on some distros.

### PR DESCRIPTION
**Pull request by sekikn**

### CODE REVIEW

**Comment by sekikn** [comment]
I already tested this on Fedora 31/ARM64 locally and confirmed it worked, so I'm going to merge it for testing on Jenkins.

**Comment by guyuqi** [comment]
Also verified it on Arm64 servers. +1

**Comment by sekikn** [comment]
Hmm, [building GPDB with this PR succeeded on Fedora 31 ARM64](https://ci.bigtop.apache.org/job/Bigtop-trunk-smoke-tests/192/COMPONENTS=gpdb.bigtop-utils@gpdb,OS=fedora-31-aarch64-deploy/console), but it's still failing on Debian and Ubuntu. Additional fix seems to be required.

https://ci.bigtop.apache.org/job/Bigtop-trunk-smoke-tests/192/COMPONENTS=gpdb.bigtop-utils@gpdb,OS=debian-9-arm64-deploy/
https://ci.bigtop.apache.org/job/Bigtop-trunk-smoke-tests/192/COMPONENTS=gpdb.bigtop-utils@gpdb,OS=ubuntu-16.04-arm64-deploy/
https://ci.bigtop.apache.org/job/Bigtop-trunk-smoke-tests/192/COMPONENTS=gpdb.bigtop-utils@gpdb,OS=ubuntu-18.04-arm64-deploy/

**Comment by guyuqi** [comment]
Let me look into it.

**Comment by sekikn** [comment]
Thanks! I think we have to install some additional packages on deployment in the case that the Docker image doesn't have them, just as Fedora.

**Comment by sekikn** [comment]
Submitted additional fix as #690 ;)

**Pull request merged**
