### PR TITLE
BIGTOP-4151: Add pkgSuffix and parentDir build arguments to Zookeeper…

### PR DESCRIPTION
**Pull request by JiaLiangC**
… deb

### Description of PR
Add pkgSuffix and parentDir build arguments to Zookeepe deb to make it can be installed by ambari

### How was this patch tested?
test build with pkgSuffix and parentDir build arguments on ubuntu22
image

test build without pkgSuffix and parentDir on ubuntu22
image

**Run smoke test on Ubuntu 22 x86_64 with -ps and -pd parameters. These two parameters are used to deploy and perform smoke tests on the deb package built with bigtop using the pkgSuffix and parentDir build arguments.**

./docker-hadoop.sh -d -dcp --create 3 --image bigtop/puppet:trunk-ubuntu-22.04 --docker-compose-yml docker-compose.yml --memory 8g --repo file:///bigtop-home/output/apt --disable-gpg-check --stack zookeeper --smoke-tests zookeeper -ps -pd /usr/bigtop

image

**Run smoke test on Ubuntu 22 x86_64 without -ps and -pd parameters.  ensure that even with the code changes brought about by these two parameters, the compilation and packaging process works correctly when the parameters are not used**

./docker-hadoop.sh -d -dcp --create 3 --image bigtop/puppet:trunk-ubuntu-22.04 --docker-compose-yml docker-compose.yml --memory 8g --repo file:///bigtop-home/output/apt --disable-gpg-check --stack zookeeper --smoke-tests zookeeper 
image

test install with ambari
image
image
image

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by iwasakims** [comment]
> ./docker-hadoop.sh -d -dcp --create 3 --image bigtop/puppet:trunk-debian-11 --docker-compose-yml docker-compose.yml  --memory 8g --repo file:///bigtop-home/output/apt --disable-gpg-check --stack zookeeper --smoke-tests zookeeper

Do docker provisioner and smoke-tests work if the name of package is changed with the suffix?

**Comment by JiaLiangC** [comment]
@iwasakims Currently, the addition of the pkg suffix and parentDir parameters in both rpm and deb packages prevents the smoketests from running. The purpose of the smoketest here is to ensure that even with the code changes brought about by these two parameters, the compilation and packaging process works correctly when the parameters are not used. In order for the smoke test to run with the pkg suffix and parentDir parameters, some modifications may be necessary.

**Comment by JiaLiangC** [comment]
i will try to make smoke test run with pkgSuffix and parentDir build arguments

**Comment by JiaLiangC** [comment]
@iwasakims  Currently, I have fixed the bigtop deploy and smoke tests so that they can test the  zk deb package produced by pkgSuffix and parentDir build parameters .

However, the zk RPM packages build with these two parameters  have not been fixed. The RPM pkgSuffix and parentDir parameters cause the service script's zkhome related paths to not be replaced correctly, leading to startup failures.
Should the fix for the RPM issue be included in this PR, or should I open a separate PR for it?

**Comment by iwasakims** [comment]
> Should the fix for the RPM issue be included in this PR, or should I open a separate PR for it?

RPM issue should be addressed in separate PR. @JiaLiangC.

**Comment by JiaLiangC** [comment]
> > Should the fix for the RPM issue be included in this PR, or should I open a separate PR for it?
> 
> RPM issue should be addressed in separate PR. @JiaLiangC.


Okay, I will create a new PR to address the RPM issue. However, the fixes for RPM deployment and smoke tests depend on the code provided in this PR, so I can only open a new PR after this one is merged.

**Comment by JiaLiangC** [comment]
@iwasakims Could you help check again?

**Pull request closed without merging**
