### PR TITLE
BIGTOP-3823: Support parent directory configuration for HBase rpm build script

### PR DESCRIPTION
**Pull request by kevinw66**
### How was this patch tested?
diff result:
```
753496 blocks
753496 blocks
2d1
< ./etc/hbase
10 blocks
10 blocks
27 blocks
27 blocks
10 blocks
10 blocks
10 blocks
10 blocks
10 blocks
10 blocks
```

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by sekikn** [comment]
+1, tested as follows:

```
$ ./gradlew hbase-clean hbase-pkg repo -Dbuildwithdeps=true
$ mv output/hbase /tmp
$ curl -sL https://github.com/apache/bigtop/pull/1021.diff | git apply
$ ./gradlew hbase-clean hbase-pkg repo -Dbuildwithdeps=true
$ for i in $(find output/hbase -name '*.rpm'); do diff <(rpm -qlp $i) <(rpm -qlp ${i/output/\/tmp}); done
2d1
< /etc/hbase
$ ./gradlew hbase-clean hbase-pkg repo -Dbuildwithdeps=true -PparentDir=/usr/bigtop
$ for i in $(find output/hbase/noarch output/hbase/x86_64 -name '*.rpm'); do rpm -qlp $i; done
/usr/bigtop/usr/share/doc/hbase-2.4.13

...

/etc/hbase
/etc/security/limits.d/hbase.nofiles.conf
/usr/bigtop/etc/default/hbase
/usr/bigtop/etc/hbase/conf.dist
/usr/bigtop/etc/hbase/conf.dist/hadoop-metrics2-hbase.properties
/usr/bigtop/etc/hbase/conf.dist/hbase-env.sh
/usr/bigtop/etc/hbase/conf.dist/hbase-policy.xml
/usr/bigtop/etc/hbase/conf.dist/hbase-site.xml
/usr/bigtop/etc/hbase/conf.dist/log4j-hbtop.properties
/usr/bigtop/etc/hbase/conf.dist/log4j.properties
/usr/bigtop/etc/hbase/conf.dist/regionservers
/usr/bigtop/usr/bin/hbase
/usr/bigtop/usr/lib/hbase

...

/usr/bigtop/var/lib/hbase
/var/log/hbase
/var/run/hbase
/etc/rc.d/init.d/hbase-regionserver
/etc/rc.d/init.d/hbase-thrift2
/etc/rc.d/init.d/hbase-master
/etc/rc.d/init.d/hbase-thrift
/etc/rc.d/init.d/hbase-rest
```

**Comment by sekikn** [comment]
Merged into master. Thanks @kevinw66!

**Comment by sekikn** [comment]
Oh, I've just found some debug messages after merging it. @kevinw66 would you submit a brief patch to remove them?
https://github.com/apache/bigtop/pull/1022/files#diff-830b6899b86a1bb787661972ce4541597f14f09e39a973e1c8ae0b0225990a64R155-R157

**Comment by kevinw66** [comment]
> Oh, I've just found some debug messages after merging it. @kevinw66 would you submit a brief patch to remove them? https://github.com/apache/bigtop/pull/1022/files#diff-830b6899b86a1bb787661972ce4541597f14f09e39a973e1c8ae0b0225990a64R155-R157

Sorry, my bad, I'll remove them immediately

**Pull request merged**
