### PR TITLE
BIGTOP-3512. Drop Giraph.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3512

Drop Giraph based on the discussion in [BIGTOP-3471](https://issues.apache.org/jira/browse/BIGTOP-3471).

### CODE REVIEW

**Comment by iwasakims** [comment]
I ran following on CentOS 8 in order to check that the code removal does not harm manifests and tests of other components.

```
$ ./gradlew hadoop-clean hadoop-pkg repo
$ cd provisioner/docker
$ ./docker-hadoop.sh \
    --create 3 \
    --image bigtop/puppet:trunk-centos-8 \
    --memory 8g \
    --repo file:///bigtop-home/output \
    --disable-gpg-check \
    --stack hdfs,mapreduce,yarn \
    --smoke-tests hdfs,mapreduce,yarn
```

**Comment by sekikn** [comment]
After applying this PR, it seems that we still have some giraph-related configurations in bigtop.bom and pom.xml.

```
$ curl -sL https://github.com/apache/bigtop/pull/753.patch | git apply -
$ git grep -i giraph

...

bigtop.bom:      So, below phoenix and giraph ought to be build after the hbase has been built
bigtop.bom:      'oozie', 'flume', 'giraph', 'solr', 'spark',
bigtop.bom:    hbase:['phoenix','giraph','ycsb','hive'],
bigtop.bom:    'giraph' {
bigtop.bom:      name    = 'giraph'
bigtop.bom:      relNotes = 'Apache Giraph'
pom.xml:    <giraph.version>1.1.0</giraph.version>
pom.xml:        <groupId>org.apache.giraph</groupId>
pom.xml:        <artifactId>giraph</artifactId>
pom.xml:        <version>${giraph.version}</version>
```

**Comment by iwasakims** [comment]
Oops. I forgot to add changes in top directory. updated.

**Comment by sekikn** [comment]
+1, confirmed that some components are successfully built after applying this PR.

**Comment by sekikn** [comment]
Merged into master.

**Pull request merged**
