### PR TITLE
BIGTOP-3715. Add TestWebHDFS to smoke-tests.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3715

estWebHDFS added by [BIGTOP-2012](https://issues.apache.org/jira/browse/BIGTOP-2012) should be leveraged to find the issue like [BIGTOP-3714](https://issues.apache.org/jira/browse/BIGTOP-3714).

I needed to modify testCreateFile to make it pass.

### CODE REVIEW

**Comment by iwasakims** [comment]
tested on Rocky Linux 8 x86_64:

```
$ ./docker-hadoop.sh \
       --create 3 \
       --image bigtop/puppet:trunk-rockylinux-8 \
       --memory 8g \
       --repo file:///bigtop-home/output \
       --disable-gpg-check \
       --stack hdfs,yarn,mapreduce \
       --smoke-tests hdfs
...
org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testDelte STANDARD_OUT
    testDelete

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testMkdir STANDARD_OUT
    testMkdir

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testOpen STANDARD_OUT
    testOpen

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testGetFileStatus STANDARD_OUT
    testtGetFileStatus

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testSetReplication STANDARD_OUT
    testSetReplication

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testGetContentSummary STANDARD_OUT
    testtGetContentSummary

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testCreateFile STANDARD_OUT
    testCreateFile

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testRename STANDARD_OUT
    testRename

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testGetFileChecksum STANDARD_OUT
    testtGetFileChecksum

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testSetPermissions STANDARD_OUT
    testSetPermissions

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testSetTimes STANDARD_OUT
    testSetTimes

Gradle Test Executor 2 finished executing tests.

> Task :bigtop-tests:smoke-tests:hdfs:test
Finished generating test XML results (0.015 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hdfs/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.021 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hdfs/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:hdfs:test (Thread[Execution worker for ':' Thread 6,5,main]) completed. Took 7 mins 43.823 secs.

BUILD SUCCESSFUL in 8m 53s
36 actionable tasks: 8 executed, 28 up-to-date
```

**Comment by sekikn** [comment]
Tested on the following distros for x86_64.

Fedora 35

```
$ ./docker-hadoop.sh -d -c 3 -F docker-compose-cgroupv2.yml -i bigtop/puppet:trunk-fedora-35 -r file:///bigtop-home/output -G -k hdfs,yarn -s hdfs

...

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testDelte STANDARD_OUT
    testDelete

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testMkdir STANDARD_OUT
    testMkdir

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testOpen STANDARD_OUT
    testOpen

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testGetFileStatus STANDARD_OUT
    testtGetFileStatus

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testSetReplication STANDARD_OUT
    testSetReplication

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testGetContentSummary STANDARD_OUT
    testtGetContentSummary

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testCreateFile STANDARD_OUT
    testCreateFile

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testRename STANDARD_OUT
    testRename

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testGetFileChecksum STANDARD_OUT
    testtGetFileChecksum

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testSetPermissions STANDARD_OUT
    testSetPermissions

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testSetTimes STANDARD_OUT
    testSetTimes

...

BUILD SUCCESSFUL in 11m 11s
36 actionable tasks: 7 executed, 29 up-to-date
```

Debian 10

```
$ ./docker-hadoop.sh -d -c 3 -i bigtop/puppet:trunk-debian-10 -r file:///bigtop-home/output/apt -m 8g -G -k hdfs,yarn -s hdfs

...

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testDelte STANDARD_OUT                                                                                                                                                             [63/1765]
    testDelete                                                                                                                                                                                                                                
                                                                                                                                                                                                                                              
org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testMkdir STANDARD_OUT                                                                                                                                                                      
    testMkdir                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                              
org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testOpen STANDARD_OUT                                                                                                                                                                       
    testOpen                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                              
org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testGetFileStatus STANDARD_OUT                                       
    testtGetFileStatus                                     

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testSetReplication STANDARD_OUT                                      
    testSetReplication                                     

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testGetContentSummary STANDARD_OUT                                   
    testtGetContentSummary                                 

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testCreateFile STANDARD_OUT                                          
    testCreateFile                                         

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testRename STANDARD_OUT                                              
    testRename                                             

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testGetFileChecksum STANDARD_OUT                                     
    testtGetFileChecksum                                   

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testSetPermissions STANDARD_OUT                                      
    testSetPermissions                                     

org.apache.bigtop.itest.hadoop.hdfs.TestWebHDFS > testSetTimes STANDARD_OUT                                            
    testSetTimes                                           

...

BUILD SUCCESSFUL in 9m 43s
36 actionable tasks: 8 executed, 28 up-to-date
```

The misspelling of `testDelte` should be fixed, but otherwise LGTM.

**Comment by iwasakims** [comment]
Thanks, @sekikn. I updated the patch.

**Comment by sekikn** [comment]
+1, will merge into master and branch-3.1. Thanks @iwasakims!

**Pull request merged**
