### PR TITLE
BIGTOP-3303. Fix build failure of hbase-1.5.0 on Ubuntu.

### PR DESCRIPTION
**Pull request by iwasakims**

### CODE REVIEW

**Comment by iwasakims** [comment]
This looks like the issue around maven as reported in [HBase ML](https://lists.apache.org/thread.html/0c39364a2949fab134107eaf164723e09d895b3eb2c16610b841e033%40%3Cuser.hbase.apache.org%3E) and [HBASE-21513](https://issues.apache.org/jira/browse/HBASE-21513). The error can be reproduced on Ubuntu 18.04 but not on CentOS 7 for me. While the root cause is unclear, workaround is separating `site` phase from other mvn invocation.

**Comment by sekikn** [comment]
+1, I confirmed the PR worked on Ubuntu 16.04/18.04 and did not introduce any problem on CentOS 7 and Debian 9/10.
Waiting for the CI to succeed, just in case.

**Comment by sekikn** [comment]
Even with this PR, building HBase on CentOS 8 failed as follows:

```
$ cat /etc/redhat-release 
CentOS Linux release 8.0.1905 (Core) 
$ ./gradlew hbase-pkg

(snip)

+ mvn -DskipTests -Dslf4j.version=1.7.25 -Dhadoop-two.version=2.10.0 -Dzookeeper.version=3.4.13 -Dcheckstyle.skip=true -Dadditionalparam=-Xdoclint:none install                                                                                                                                                              

(snip)

[INFO] --- maven-jar-plugin:3.0.0:test-jar (default) @ hbase-checkstyle ---
[WARNING] The POM for org.apache.maven:maven-archiver:jar:3.0.2 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Apache HBase 1.5.0 ................................. SUCCESS [  2.831 s]
[INFO] Apache HBase - Checkstyle .......................... FAILURE [  1.036 s]
[INFO] Apache HBase - Resource Bundle ..................... SKIPPED
[INFO] Apache HBase - Annotations ......................... SKIPPED
[INFO] Apache HBase - Protocol ............................ SKIPPED
[INFO] Apache HBase - Common .............................. SKIPPED
[INFO] Apache HBase - Procedure ........................... SKIPPED
[INFO] Apache HBase - Client .............................. SKIPPED
[INFO] Apache HBase - Metrics API ......................... SKIPPED
[INFO] Apache HBase - Hadoop Compatibility ................ SKIPPED
[INFO] Apache HBase - Metrics Implementation .............. SKIPPED
[INFO] Apache HBase - Hadoop Two Compatibility ............ SKIPPED
[INFO] Apache HBase - Prefix Tree ......................... SKIPPED
[INFO] Apache HBase - Server .............................. SKIPPED
[INFO] Apache HBase - Testing Util ........................ SKIPPED
[INFO] Apache HBase - Thrift .............................. SKIPPED
[INFO] Apache HBase - Rest ................................ SKIPPED
[INFO] Apache HBase - RSGroup ............................. SKIPPED
[INFO] Apache HBase - Shell ............................... SKIPPED
[INFO] Apache HBase - Integration Tests ................... SKIPPED
[INFO] Apache HBase - Examples ............................ SKIPPED
[INFO] Apache HBase - External Block Cache ................ SKIPPED
[INFO] Apache HBase - HBTop ............................... SKIPPED
[INFO] Apache HBase - Assembly ............................ SKIPPED
[INFO] Apache HBase - Shaded .............................. SKIPPED
[INFO] Apache HBase - Shaded - Client ..................... SKIPPED
[INFO] Apache HBase - Shaded - Server ..................... SKIPPED
[INFO] Apache HBase - Shaded - Testing Util ............... SKIPPED
[INFO] Apache HBase - Shaded - Testing Util Tester ........ SKIPPED
[INFO] Apache HBase Shaded Packaging Invariants ........... SKIPPED
[INFO] Apache HBase - Archetypes .......................... SKIPPED
[INFO] Apache HBase - Exemplar for hbase-client archetype . SKIPPED
[INFO] Apache HBase - Exemplar for hbase-shaded-client archetype SKIPPED
[INFO] Apache HBase - Archetype builder 1.5.0 ............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.130 s
[INFO] Finished at: 2020-02-07T14:09:45Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.0.0:test-jar (default) on project hbase-checkstyle: Execution default of goal org.apache.maven.plugins:maven-jar-plugin:3.0.0:test-jar failed: A required class was missing while executing org.apache.maven.plugins:maven-jar-plugin:3.0.0:test-j
ar: org/apache/maven/shared/utils/io/IOUtil
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-jar-plugin:3.0.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/vagrant/.m2/repository/org/apache/maven/plugins/maven-jar-plugin/3.0.0/maven-jar-plugin-3.0.0.jar
[ERROR] urls[1] = file:/home/vagrant/.m2/repository/org/sonatype/sisu/sisu-inject-bean/1.4.2/sisu-inject-bean-1.4.2.jar
[ERROR] urls[2] = file:/home/vagrant/.m2/repository/org/sonatype/sisu/sisu-guice/2.1.7/sisu-guice-2.1.7-noaop.jar
[ERROR] urls[3] = file:/home/vagrant/.m2/repository/org/sonatype/aether/aether-util/1.7/aether-util-1.7.jar
[ERROR] urls[4] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[5] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[6] = file:/home/vagrant/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[7] = file:/home/vagrant/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[8] = file:/home/vagrant/.m2/repository/org/apache/maven/maven-archiver/3.0.2/maven-archiver-3.0.2.jar
[ERROR] urls[9] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-archiver/3.1.1/plexus-archiver-3.1.1.jar
[ERROR] urls[10] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-io/2.7.1/plexus-io-2.7.1.jar
[ERROR] urls[11] = file:/home/vagrant/.m2/repository/commons-io/commons-io/2.2/commons-io-2.2.jar
[ERROR] urls[12] = file:/home/vagrant/.m2/repository/org/apache/commons/commons-compress/1.10/commons-compress-1.10.jar
[ERROR] urls[13] = file:/home/vagrant/.m2/repository/org/iq80/snappy/snappy/0.4/snappy-0.4.jar
[ERROR] urls[14] = file:/home/vagrant/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.apache.hbase:hbase:1.5.0, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------
[ERROR] : org.apache.maven.shared.utils.io.IOUtil
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hbase-checkstyle
error: Bad exit status from /var/tmp/rpm-tmp.gN3oCE (%build)
    Bad exit status from /var/tmp/rpm-tmp.gN3oCE (%build)


RPM build errors:

> Task :hbase-rpm FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/vagrant/bigtop/packages.gradle' line: 500

* What went wrong:
Execution failed for task ':hbase-rpm'.
> Process 'command 'rpmbuild'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
5 actionable tasks: 5 executed
```

@iwasakims Would you check if it's reproducable in your environment?

**Comment by iwasakims** [comment]
@sekikn I could not reproduce your issue on my CentOS 8 env like below. `./gradlew hbase-pkg` succeeded with this PR. There was no issue even without the fix. 
```
$ rpm -q centos-release
centos-release-8.0-0.1905.0.9.el8.x86_64

$ mvn --version
Apache Maven 3.5.4 (Red Hat 3.5.4-5)
Maven home: /usr/share/maven
Java version: 1.8.0_232, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el8_0.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-80.el8.x86_64", arch: "amd64", family: "unix"

$ rpm -q maven
maven-3.5.4-5.module_el8.0.0+39+6a9b6e22.noarch

$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

$ rpm -q java-1.8.0-openjdk-devel
java-1.8.0-openjdk-devel-1.8.0.232.b09-0.el8_0.x86_64
```

**Comment by sekikn** [comment]
@iwasakims I recreated my CentOS 8 VM cleanly and succeeded in building. Sorry for taking your time. Will merge the PR.

**Comment by iwasakims** [comment]
Thanks, @sekikn.

**Pull request merged**
