### PR TITLE
BIGTOP-3298. Bump Phoenix to 4.15.0-HBase-1.5.

### PR DESCRIPTION
**Pull request by iwasakims**
Please refer to [BIGTOP-3298](https://issues.apache.org/jira/browse/BIGTOP-3298) for the description of the fix and manual test.

### CODE REVIEW

**Comment by iwasakims** [comment]
This conflicts with #588. I will push the change to revert the line updating the version of HBase in bigtop.bom once [BIGTOP-3297](https://issues.apache.org/jira/browse/BIGTOP-3297) is merged.

**Comment by youngwookim** [comment]
@iwasakims BIGTOP-3297, #588 is merged to master. So please rebase this. 
Otherwise, LGTM!

**Comment by iwasakims** [comment]
@youngwookim Thanks. I rebased this.

**Comment by sekikn** [comment]
+1, confirmed that the PR worked on CentOS 7/8, Debian 9/10, and Ubuntu 16.04/18.04.

**Pull request merged**
