### PR TITLE
BIGTOP-3758. Fix build failure of Tez against Hadoop 3.3.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3758

* We can leverage protoc-jar-maven-plugin by cherry-picking [TEZ-4300](https://issues.apache.org/jira/browse/TEZ-4300) and [TEZ-4428](https://issues.apache.org/jira/browse/TEZ-4428). (TEZ-4300 is just needed to cleanly apply TEZ-4428)
  * We need to install protoc artifact from locally installed one on aarch64 and ppc64le.
* [TEZ-4298](https://issues.apache.org/jira/browse/TEZ-4298) fixed ShuffleHandler.

### CODE REVIEW

**Comment by iwasakims** [comment]
tested on Rocky Linux 8 x86_64:

```
$ ./docker-hadoop.sh \
     --create 1 \
     --image bigtop/puppet:trunk-rockylinux-8 \
     --memory 16g \
     --repo file:///bigtop-home/output \
     --disable-gpg-check \
     --stack hdfs,yarn,mapreduce,tez \
     --smoke-tests tez
...
Now testing...
:bigtop-tests:smoke-tests:tez:test (Thread[Execution worker for ':',5,main]) completed. Took 39.337 secs.

BUILD SUCCESSFUL in 1m 11s
34 actionable tasks: 7 executed, 27 up-to-date
```

**Comment by iwasakims** [comment]
and on Ubuntu 18.04 aarch64:

```
$ ./docker-hadoop.sh \
     --create 1 \
     --image bigtop/puppet:trunk-ubuntu-18.04 \
     --memory 16g \
     --repo file:///bigtop-home/output/apt \
     --disable-gpg-check \
     --stack hdfs,yarn,mapreduce,tez \
     --smoke-tests tez
...
Now testing...
:bigtop-tests:smoke-tests:tez:test (Thread[Daemon worker,5,main]) completed. Took 1 mins 5.052 secs.

BUILD SUCCESSFUL in 1m 55s
34 actionable tasks: 7 executed, 27 up-to-date
```

**Comment by guyuqi** [comment]
+1, LGTM.

**Comment by guyuqi** [comment]
Merged.

**Pull request merged**
