### PR TITLE
BIGTOP-3329. Bump ambari to v2.7.5.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3329

### CODE REVIEW

**Comment by iwasakims** [comment]
I need additional fix to address changes of contained files.
```
$ ./gradlew ambari-clean ambari-pkg
...
+ install -d -m 0755 /home/centos/srcs/bigtop/build/ambari/rpm/BUILDROOT/ambari-2.7.5.0-1.el8.x86_64//usr/lib/ambari-client/lib
+ cp -a '/home/centos/srcs/bigtop/build/ambari/rpm/BUILD/apache-ambari-2.7.5-src/ambari-client/groovy-client/target/groovy-client*.jar' /home/centos/srcs/bigtop/build/ambari/rpm/BUILDROOT/ambari-2.7.5.0-1.el8.x86_64//usr/lib/ambari-client/lib
cp: cannot stat '/home/centos/srcs/bigtop/build/ambari/rpm/BUILD/apache-ambari-2.7.5-src/ambari-client/groovy-client/target/groovy-client*.jar': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.tVSEHZ (%install)
```

**Comment by iwasakims** [comment]
ambari-shell and ambari-client are removed by [AMBARI-23144](https://issues.apache.org/jira/browse/AMBARI-23144).

**Comment by iwasakims** [comment]
`./gradlew ambari-pkg` succeeded on CentOS 8.

**Comment by sekikn** [comment]
Thank you for taking this issue @iwasakims!

`./gradlew ambari-pkg` seems to fail with the following error on Debian 10 and Ubuntu 18.04, 20.04:

```
> Task :ambari-sdeb

...

dh clean
   dh_auto_clean
dh_auto_clean: warning: Please use the third-party "pybuild" build system instead of python-distutils
dh_auto_clean: warning: This feature will be removed in compat 12.
pyversions: missing X(S)-Python-Version in control file, fall back to debian/pyversions
pyversions: missing debian/pyversions file, fall back to supported versions
        python setup.py clean -a
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from setuptools import find_packages, setup
ImportError: No module named setuptools
dh_auto_clean: error: python setup.py clean -a returned exit code 1
make: *** [debian/rules:26: clean] Error 25
dpkg-buildpackage: error: fakeroot debian/rules clean subprocess returned exit status 2

> Task :ambari-sdeb FAILED

FAILURE: Build failed with an exception.
```

**Comment by iwasakims** [comment]
@sekikn I could not reproduce the `ImportError: No module named setuptools`. Maybe because there is python-setuptools on my Ubuntu VM. Could you try updating bigtop_toolchain/manifests/packages.pp like below on your env? If it works, I will add the fix to this PR.
```
diff --git a/bigtop_toolchain/manifests/packages.pp b/bigtop_toolchain/manifests/packages.pp
index f25e79f8..d97cc176 100644
--- a/bigtop_toolchain/manifests/packages.pp
+++ b/bigtop_toolchain/manifests/packages.pp
@@ -207,6 +207,7 @@ class bigtop_toolchain::packages {
         "bison",
         "flex",
         "python-dev",
+        "python-setuptools",
         "libffi-dev"
       ]
       file { '/etc/apt/apt.conf.d/01retries':
```

**Comment by iwasakims** [comment]
I got another error on Ubuntu 18.04.
```
debian/rules:26: recipe for target 'binary' failed
make: *** [binary] Error 255
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2

> Task :ambari-deb FAILED
6 actionable tasks: 6 executed
dpkg-buildpackage: warning: debian/rules is not executable; fixing that
 dpkg-source --before-build ambari-2.7.5.0
 fakeroot debian/rules clean
pyversions: missing X(S)-Python-Version in control file, fall back to debian/pyversions
pyversions: missing debian/pyversions file, fall back to supported versions
'build/lib.linux-x86_64-2.7' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-2.7' does not exist -- can't clean it
 dpkg-source -b ambari-2.7.5.0
 dpkg-genbuildinfo --build=source
 dpkg-genchanges -sa --build=source >../ambari_2.7.5.0-1_source.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build ambari-2.7.5.0
dpkg-source: warning: extracting unsigned source package (ambari_2.7.5.0-1.dsc)
debuild: fatal error at line 1152:
dpkg-buildpackage -rfakeroot -us -uc -ui -b
 failed

FAILURE: Build failed with an exception.
```

**Comment by sekikn** [comment]
Thanks for the advice @iwasakims, updating bigtop_toolchain/manifests/packages.pp just worked.
I didn't come across the error you mentioned above, but got another one at least on Debian 9, 10 and Ubuntu 20.04:

```
   dh_install
dh_install: warning: Cannot find (any matches for) "/usr/lib/python2.6/site-packages/ambari_server" (tried in ., debian/tmp)

dh_install: warning: ambari-server missing files: /usr/lib/python2.6/site-packages/ambari_server
        install -d debian/ambari-server//etc
        cp --reflink=auto -a debian/tmp/etc/ambari-server debian/ambari-server//etc/
        install -d debian/ambari-server//etc/init.d
        cp --reflink=auto -a debian/tmp/etc/init.d/ambari-server debian/ambari-server//etc/init.d/
        install -d debian/ambari-server//usr/sbin
        cp --reflink=auto -a debian/tmp/usr/sbin/ambari-server.py debian/tmp/usr/sbin/ambari_server_main.py debian/ambari-server//usr/sbin/
        install -d debian/ambari-server//var/lib
        cp --reflink=auto -a debian/tmp/var/lib/ambari-server/ debian/ambari-server//var/lib/
dh_install: warning: Cannot find (any matches for) "/usr/lib/python2.6/site-packages/ambari_agent" (tried in ., debian/tmp)

dh_install: warning: ambari-agent missing files: /usr/lib/python2.6/site-packages/ambari_agent
dh_install: error: missing files, aborting
        install -d debian/.debhelper/generated/ambari-server
        install -d debian/.debhelper/generated/ambari-agent
make: *** [debian/rules:26: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b
 failed

> Task :ambari-deb FAILED

FAILURE: Build failed with an exception.
```

**Comment by sekikn** [comment]
+1, tested with all supported distros on the x86_64 platforms. I've not run the smoke test yet, but if there's any problem, we can address it as another issue. Thanks @iwasakims!

**Pull request merged**
