### PR TITLE
BIGTOP-3693. Support Docker Compose V2

### PR DESCRIPTION
**Pull request by vivostar**
### Description of PR
Make docker-hadoop.sh support docker compose v2

### How was this patch tested?
1. install docker
```shell
yum install -y git yum-utils ruby
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
systemctl start docker
```
2. test docker-hadoop.sh
```shell
./docker-hadoop.sh \
       -d \
       -dc2 \
       --create 2 \
       --image bigtop/puppet:trunk-centos-7 \
       --memory 8g \
       --repo http://repos.bigtop.apache.org/releases/3.1.0/centos/7/\$basearch \
       --disable-gpg-check \
       --stack hdfs,yarn,mapreduce,spark,hive
./docker-hadoop.sh \
       -d \
       --docker-compose-v2 \
       --create 2 \
       --image bigtop/puppet:trunk-centos-7 \
       --memory 8g \
       --repo http://repos.bigtop.apache.org/releases/3.1.0/centos/7/\$basearch \
       --disable-gpg-check \
       --stack hdfs,yarn,mapreduce,spark,hive
```

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [x] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by guyuqi** [comment]
The users could select the corresponding binaries of `docker-compose`  for v1 and v2  from `https://github.com/docker/compose/releases`.

We've made docker-provisioner to be used both in docker-compose v1 and v2 : https://github.com/apache/bigtop/pull/903.

I'm afraid this PR is not about `support docker-compose v2`,  but just provides the command for showing some inessential help-info .
To be honest, I don't think this PR makes sense.

**Comment by vivostar** [comment]
@guyuqi , Thanks for your advice. When we use docker client v2, it's docker-compose is "docker compose". My dev machine is docker client v2, too, so when I test something I must change the docker-hadoop.sh. So I add the pr to improve it.

**Comment by sekikn** [comment]
@vivostar As you mentioned, the plugin version of "docker compose" command is available in v2.
https://docs.docker.com/compose/#compose-v2-and-the-new-docker-compose-command
I think this change is useful for the users of that version (including me), so would you submit this PR again?
And in that PR, the option name `--docker-compose-v2` feels somewhat ambiguous to me if it refers to the yaml format or plugin command, so `--docker-compose-plugin` or something may be better.

**Comment by vivostar** [comment]
hi, @sekikn , thanks for your concern the issue, I will reopen the pr and work on this.

**Comment by vivostar** [comment]
test docker-hadoop.sh
1. start containers
```shell
./docker-hadoop.sh \
       -d \
       -dcp \
       --create 2 \
       --image bigtop/puppet:trunk-centos-7 \
       --memory 8g \
       --repo http://repos.bigtop.apache.org/releases/3.1.0/centos/7/\$basearch \
       --disable-gpg-check \
       --stack hdfs,yarn,mapreduce,spark,hive
./docker-hadoop.sh \
       -d \
       --docker-compose-plugin \
       --create 2 \
       --image bigtop/puppet:trunk-centos-7 \
       --memory 8g \
       --repo http://repos.bigtop.apache.org/releases/3.1.0/centos/7/\$basearch \
       --disable-gpg-check \
       --stack hdfs,yarn,mapreduce,spark,hive
```
2. stop containers
```
./docker-hadoop.sh  -d  -dcp # don't forget add the command line parameter
```

**Comment by sekikn** [comment]
Thanks @vivostar! Would you rebase the PR on the latest master? It looks mergeable on GitHub, but it actually conflicts #1026 and seems to cancel that change.

**Comment by vivostar** [comment]
hi @sekikn, thanks for your advice, I have updated the pr.

**Comment by sekikn** [comment]
+1, tested with both "docker-compose" and "docker compose". @vivostar thank you for your contribution!

**Pull request merged**
