### PR TITLE
BIGTOP-2550: Update juju hadoop bundle for Juju 2.0 and Xenial

### PR DESCRIPTION
**Pull request by kwmonroe**
- Update README with xenial and juju2 instructions.  Callout juju1 equivalent commands where applicable.
- Colocate apps that can live together (eg: RM and NN) to cut down on required machine resources.  Note this colocation in the readme.
- Bump charm revisions to include newly built charms from BIGTOP-2548.

### CODE REVIEW

**Comment by johnsca** [comment]
+1 LGTM, deployed and tested successfully on AWS.

**Comment by ktsakalozos** [comment]
LGTM +1 also tested with no problems

**Comment by ktsakalozos** [comment]
Here is another run. This time the mapping of machines to application was correct but we still get failing amulet tests.
http://pastebin.ubuntu.com/23318768/

**Comment by kwmonroe** [comment]
Thanks all.  I've refreshed the charm revision numbers to pick up the recent bind-host options (bigtop-2554) and fix an issue with terasorting on lxd.

**Pull request closed without merging**
