### PR TITLE
BIGTOP-3562. Building Logstash is failing due to the unavailability of keyserver.

### PR DESCRIPTION
**Pull request by sekikn**
https://issues.apache.org/jira/browse/BIGTOP-3562

### CODE REVIEW

**Comment by iwasakims** [comment]
It did not worked on my (non-docker) environment.

```
+ gpg2 --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: keyserver receive failed: No data
error: Bad exit status from /var/tmp/rpm-tmp.iOiL5M (%build)
    Bad exit status from /var/tmp/rpm-tmp.iOiL5M (%build)
```

I got no issue on Ubunt 18.04 (non-docker environment too).

**Comment by iwasakims** [comment]
@sekikn
While https://github.com/rvm/rvm/issues/4573 is suggesting to use `hkp://keys.gnupg.net`, it did not work.

https://github.com/railsgirls/installation-scripts/pull/61 addressed the issue by the following cmdline which worked for me too.

```
curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
```

**Comment by sekikn** [comment]
Thanks for the comment @iwasakims, the last one looks better because it's not affected by keyserver's status. I'm going to update the PR.

**Review by iwasakims — APPROVED** [review]
+1

**Pull request merged**
