### PR TITLE
BIGTOP-3282. Bump Hive to 2.3.6.

### PR DESCRIPTION
**Pull request by iwasakims**

### CODE REVIEW

**Comment by iwasakims** [comment]
smoke-tests passed on the following configuration. (tez is not used while it is contained in coponents.):
```
$ cat config.yaml 
docker:
        memory_limit: "8g"
        image: "bigtop/puppet:trunk-centos-7"
distro: centos
components: [hdfs, yarn, mapreduce, hive, tez]
enable_local_repo: true
smoke_test_components: [hive]

$ ./docker-hadoop.sh -c 4 --smoke-tests
...
Now testing...
:bigtop-tests:smoke-tests:hive:test (Thread[Task worker for ':',5,main]) completed. Took 16.861 secs.

BUILD SUCCESSFUL in 1m 10s
```

**Comment by iwasakims** [comment]
manual testing with Tez (0.9.2 based on #591) enabled:
```
[root@b68055d8f372 /]# echo 'export HADOOP_CLASSPATH=/etc/tez/conf:/usr/lib/tez/*:/usr/lib/tez/lib/*:$HADOOP_CLASSPATH' >> /etc/hadoop/conf/hadoop-env.sh
[root@b68055d8f372 /]# sed -i -e 's/<value>mr<\/value>/<value>tez<\/value>/' /etc/hive/conf/hive-site.xml
[root@b68055d8f372 /]# hive
hive> create table test(id int, st string);
hive> insert into test values (1, 'foo'), (2, 'bar'), (3, 'baz');
Query ID = root_20200207023400_516b2c5b-1983-4eb7-bc49-0bd1193a0c5b
Total jobs = 1
Launching Job 1 out of 1
Status: Running (Executing on YARN cluster with App id application_1581040795396_0003)

----------------------------------------------------------------------------------------------
        VERTICES      MODE        STATUS  TOTAL  COMPLETED  RUNNING  PENDING  FAILED  KILLED  
----------------------------------------------------------------------------------------------
Map 1 .......... container     SUCCEEDED      1          1        0        0       0       0  
----------------------------------------------------------------------------------------------
VERTICES: 01/01  [==========================>>] 100%  ELAPSED TIME: 6.12 s     
----------------------------------------------------------------------------------------------
Loading data to table default.test
OK
Time taken: 9.328 seconds

hive> select * from test;
OK
1	foo
2	bar
3	baz
Time taken: 0.22 seconds, Fetched: 3 row(s)
```

**Comment by sekikn** [comment]
+1, I confirmed that `./gradlew hive-pkg` succeeded at least on CentOS 7 and 8, Debian 9 and Ubuntu 16.04 and 18.04.

**Comment by iwasakims** [comment]
Thanks, @sekikn.

**Comment by MrZXR** [comment]
[spark 2.4.5 ](https://github.com/apache/spark/blob/cee4ecbb16917fa85f02c635925e2687400aa56b/sql/hive/src/main/scala/org/apache/spark/sql/hive/client/IsolatedClientLoader.scala#L91)

spark 2.4.5 not working with hive 2.3.6, highest is 2.3.3

**Pull request merged**
