### PR TITLE
BIGTOP-3790: Add symlink for Tez conf dir

### PR DESCRIPTION
**Pull request by kevinw66**
### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by sekikn** [comment]
+1. Building Tez with this PR finished without any errors and its artifact passed the smoke test.

```
$ curl -sL https://github.com/apache/bigtop/pull/990.patch | git apply
$ ./gradlew tez-clean tez-pkg repo -Dbuildwithdeps=true

...

Checking for unpackaged file(s): /usr/lib/rpm/check-files /home/vagrant/bigtop/build/tez/rpm/BUILDROOT/tez-0.10.1-1.el7.x86_64                                                                                                                
Wrote: /home/vagrant/bigtop/build/tez/rpm/RPMS/noarch/tez-0.10.1-1.el7.noarch.rpm                                                                                                                                                             
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.1bHWq8                                                                                                                                                                                         
+ umask 022                                                                                                                                                                                                                                   
+ cd /home/vagrant/bigtop/build/tez/rpm//BUILD                                                                                                                                                                                                
+ cd apache-tez-0.10.1-src                                                                                                                                                                                                                    
+ /usr/bin/rm -rf /home/vagrant/bigtop/build/tez/rpm/BUILDROOT/tez-0.10.1-1.el7.x86_64                                                                                                                                                        
+ exit 0                                                                                                                                                                                                                                      
Executing(--clean): /bin/sh -e /var/tmp/rpm-tmp.tirrGP                                                                                                                                                                                        
+ umask 022                                                                                                                                                                                                                                   
+ cd /home/vagrant/bigtop/build/tez/rpm//BUILD                                                                                                                                                                                                
+ rm -rf apache-tez-0.10.1-src                                                                                                                                                                                                                
+ exit 0                                                                                                                                                                                                                                      

...

BUILD SUCCESSFUL in 3m 30s
34 actionable tasks: 34 executed
```

```
$ cd provisioner/docker
$ ./docker-hadoop.sh -d -C config_centos-7.yaml -r file:///bigtop-home/output -G -k hdfs,yarn,tez -s tez -c 3

...

> Task :bigtop-tests:smoke-tests:tez:test
Finished generating test XML results (0.019 secs) into: /bigtop-home/bigtop-tests/smoke-tests/tez/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.038 secs) into: /bigtop-home/bigtop-tests/smoke-tests/tez/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:tez:test (Thread[Daemon worker,5,main]) completed. Took 50.256 secs.

BUILD SUCCESSFUL in 2m 51s
30 actionable tasks: 7 executed, 23 up-to-date
```

**Comment by sekikn** [comment]
Merged into master. Thanks for the contribution @kevinw66!

**Comment by sekikn** [comment]
@kevinw66 I've just noticed that I forgot to test it for the deb package, and it seems to have a problem. Would you take a look?

```
dh_install: warning: tez missing files: etc/tez/conf
        install -d debian/tez//usr/lib
        cp --reflink=auto -a debian/tmp/usr/lib/tez debian/tez//usr/lib/
        install -d debian/tez//usr/share/man
        cp --reflink=auto -a debian/tmp/usr/share/man/man1 debian/tez//usr/share/man/
dh_install: error: missing files, aborting
        install -d debian/.debhelper/generated/tez
make: *** [debian/rules:32: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b
 failed

> Task :tez-deb FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/home/vagrant/bigtop/packages.gradle' line: 355

* What went wrong:
Execution failed for task ':tez-deb'.
> Process 'command 'debuild'' finished with non-zero exit value 29
```

**Comment by kevinw66** [comment]
> @kevinw66 I've just noticed that I forgot to test it for the deb package, and it seems to have a problem. Would you take a look?
> 
> ```
> dh_install: warning: tez missing files: etc/tez/conf
>         install -d debian/tez//usr/lib
>         cp --reflink=auto -a debian/tmp/usr/lib/tez debian/tez//usr/lib/
>         install -d debian/tez//usr/share/man
>         cp --reflink=auto -a debian/tmp/usr/share/man/man1 debian/tez//usr/share/man/
> dh_install: error: missing files, aborting
>         install -d debian/.debhelper/generated/tez
> make: *** [debian/rules:32: binary] Error 25
> dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
> debuild: fatal error at line 1182:
> dpkg-buildpackage -us -uc -ui -b
>  failed
> 
> > Task :tez-deb FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/home/vagrant/bigtop/packages.gradle' line: 355
> 
> * What went wrong:
> Execution failed for task ':tez-deb'.
> > Process 'command 'debuild'' finished with non-zero exit value 29
> ```

Sure, let me check on this

**Pull request merged**
