### PR TITLE
BIGTOP-3297. Bump HBase to 1.5.0.

### PR DESCRIPTION
**Pull request by iwasakims**

### CODE REVIEW

**Comment by iwasakims** [comment]
We need the patch of [HBASE-19663](https://issues.apache.org/jira/browse/HBASE-19663) to fix javadoc compilation failure.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project hbase: Error generating maven-javadoc-plugin:2.10.3:aggregate:
[ERROR] Exit code: 1 - warning: unknown enum constant When.MAYBE
[ERROR]   reason: class file for javax.annotation.meta.When not found
[ERROR] warning: unknown enum constant When.ALWAYS
[ERROR] warning: unknown enum constant When.UNKNOWN
[ERROR] javadoc: error - class file for javax.annotation.concurrent.Immutable not found
[ERROR]
[ERROR] Command line was: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el7_7.x86_64/jre/../bin/javadoc -J-Xmx2048m @options @packages
```

**Comment by iwasakims** [comment]
`./docker-hadoop.sh -c 3 --smoke-tests` passed on my local with the following configuration.

```
docker:
        memory_limit: "8g"
        image: "bigtop/puppet:trunk-centos-7"

#repo: "http://repos.bigtop.apache.org/releases/1.4.0/centos/7/$basearch"
distro: centos
components: [hdfs, yarn, mapreduce, hbase]
enable_local_repo: true
smoke_test_components: [hbase]
```

**Comment by iwasakims** [comment]
Phoenix 4.15.0-HBase-1.5 was successfully built based on the fix here. (Please refer to [BIGTOP-3298](https://issues.apache.org/jira/browse/BIGTOP-3298).)

**Comment by evans-ye** [comment]
Looks great. +1.

**Comment by youngwookim** [comment]
+1

I'll push to master shortly. Thanks @evans-ye and @iwasakims for the patch and review.

**Comment by iwasakims** [comment]
Thanks, @evans-ye and @youngwookim. Closing this.

**Pull request closed without merging**
