### PR TITLE
BIGTOP-3740: Add Zeppelin support for Bigtop 3.1.0 Mpack

### PR DESCRIPTION
**Pull request by kevinw66**
### Description of PR
Add Zeppelin support for Bigtop 3.1.0 Mpack

### How was this patch tested?
Need to test with #953 
Visit localhost:9995 to access zeppelin web ui(if you are using docker env, remember to expose the port to your local machine).

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by kevinw66** [comment]
Sorry, I left tests info under wrong pull request, please redirect to #953

**Comment by kevinw66** [comment]
Simple tests for python and shell succeed, others may need to install interpreter manually. 

image

image

**Comment by kevinw66** [comment]
change notebook storage dir to /user/zeppelin/

image

image

**Comment by guyuqi** [comment]
It would take a while to rebuild Ambari and pls give me some time to test this PR, thanks

**Comment by guyuqi** [comment]
Re-build and deploy zeppelin based on Bigtop 3.1.0 repo:

It seems Zeppelin Notebook Start failed:
`Python script has been killed due to timeout after waiting 10000 secs`

```
2022-07-21 06:19:47,512 - get_user_call_output returned
 (0, u'{"RemoteException":{"exception":
"FileNotFoundException","javaClassName":"java.io.FileNotFoundException",
"message":
"File does not exist: /user/zeppelin/notebook/R Tutorial/2. Shiny App_2EZ66TM57.zpln"}}404', u'')

2022-07-21 06:19:47,512 - Creating new file /user/zeppelin/notebook/R Tutorial/2. 
Shiny App_2EZ66TM57.zpln in DFS
2022-07-21 06:19:47,514 - call['ambari-sudo.sh su hdfs -l -s /bin/bash -c
 'curl -sS -L -w '"'"'%{http_code}'"'"' -X PUT --data-binary '"'"'@/var/lib/zeppelin/notebook/R Tutorial/2. 
Shiny App_2EZ66TM57.zpln'"'"' -H '"'"'Content-Type: application/octet-stream'"'"' 
'"'"'http://ambari-agent-01:50070/webhdfs/v1/user/zeppelin/notebook/R%20Tutorial/2.%20Shiny%20App_2EZ66TM57.zpln?op
=CREATE&user.name=hdfs&overwrite=True'"'"' 1>/tmp/tmptNTDU6 2>/tmp/tmpIDDAyp'']
 {'logoutput': None, 'quiet': False}
```

Does it caused by [BIGTOP-3714](https://issues.apache.org/jira/browse/BIGTOP-3714) too?

**Comment by kevinw66** [comment]
> Re-built Ambari with #953, and deployed zeppelin based on Bigtop 3.1.0 repo:
> 
> It seems Zeppelin Notebook Start failed: `Python script has been killed due to timeout after waiting 10000 secs`
> 
> ```
> 2022-07-21 06:19:47,512 - get_user_call_output returned
>  (0, u'{"RemoteException":{"exception":
> "FileNotFoundException","javaClassName":"java.io.FileNotFoundException",
> "message":
> "File does not exist: /user/zeppelin/notebook/R Tutorial/2. Shiny App_2EZ66TM57.zpln"}}404', u'')
> 
> 2022-07-21 06:19:47,512 - Creating new file /user/zeppelin/notebook/R Tutorial/2. 
> Shiny App_2EZ66TM57.zpln in DFS
> 2022-07-21 06:19:47,514 - call['ambari-sudo.sh su hdfs -l -s /bin/bash -c
>  'curl -sS -L -w '"'"'%{http_code}'"'"' -X PUT --data-binary '"'"'@/var/lib/zeppelin/notebook/R Tutorial/2. 
> Shiny App_2EZ66TM57.zpln'"'"' -H '"'"'Content-Type: application/octet-stream'"'"' 
> '"'"'http://ambari-agent-01:50070/webhdfs/v1/user/zeppelin/notebook/R%20Tutorial/2.%20Shiny%20App_2EZ66TM57.zpln?op
> =CREATE&user.name=hdfs&overwrite=True'"'"' 1>/tmp/tmptNTDU6 2>/tmp/tmpIDDAyp'']
>  {'logoutput': None, 'quiet': False}
> ```
> 
> Was it caused by [BIGTOP-3714](https://issues.apache.org/jira/browse/BIGTOP-3714) too?

Yes @guyuqi

**Comment by guyuqi** [comment]
> > Re-built Ambari with #953, and deployed zeppelin based on Bigtop 3.1.0 repo:
> > It seems Zeppelin Notebook Start failed: `Python script has been killed due to timeout after waiting 10000 secs`
> > ```
> > 2022-07-21 06:19:47,512 - get_user_call_output returned
> >  (0, u'{"RemoteException":{"exception":
> > "FileNotFoundException","javaClassName":"java.io.FileNotFoundException",
> > "message":
> > "File does not exist: /user/zeppelin/notebook/R Tutorial/2. Shiny App_2EZ66TM57.zpln"}}404', u'')
> > 
> > 2022-07-21 06:19:47,512 - Creating new file /user/zeppelin/notebook/R Tutorial/2. 
> > Shiny App_2EZ66TM57.zpln in DFS
> > 2022-07-21 06:19:47,514 - call['ambari-sudo.sh su hdfs -l -s /bin/bash -c
> >  'curl -sS -L -w '"'"'%{http_code}'"'"' -X PUT --data-binary '"'"'@/var/lib/zeppelin/notebook/R Tutorial/2. 
> > Shiny App_2EZ66TM57.zpln'"'"' -H '"'"'Content-Type: application/octet-stream'"'"' 
> > '"'"'http://ambari-agent-01:50070/webhdfs/v1/user/zeppelin/notebook/R%20Tutorial/2.%20Shiny%20App_2EZ66TM57.zpln?op
> > =CREATE&user.name=hdfs&overwrite=True'"'"' 1>/tmp/tmptNTDU6 2>/tmp/tmpIDDAyp'']
> >  {'logoutput': None, 'quiet': False}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Was it caused by [BIGTOP-3714](https://issues.apache.org/jira/browse/BIGTOP-3714) too?
> 
> Yes @guyuqi

Thanks, @kevinw66 

I'm working on Bump Zeppelin to 0.10.1.
I'd like merge this PR after BIGTOP-3700 resolved.

**Comment by guyuqi** [comment]
Re-built Ambari with https://github.com/apache/bigtop/pull/953 and successfully deployed Zeppelin against on Hadoop-3.3.4.

LGTM, +1

And one more thing, could you please expose port `9995 `like `-p 9995:9995` in https://github.com/apache/bigtop/blob/master/bigtop-packages/src/common/bigtop-ambari-mpack/dev-support/docker/centos7/build-containers.sh#L44?  @kevinw66

**Comment by kevinw66** [comment]
> Re-built Ambari with #953 and successfully deployed Zeppelin against on Hadoop-3.3.4.
> 
> LGTM, +1
> 
> And one more thing, could you please expose port `9995 ` in this PR like `-p 9995:9995` in https://github.com/apache/bigtop/blob/master/bigtop-packages/src/common/bigtop-ambari-mpack/dev-support/docker/centos7/build-containers.sh#L44?
> 
> @kevinw66

@guyuqi I can only choose one container to expose the port(default is ambari-agent-01), but this is useless if we choose different container to install zeppelin.

**Comment by guyuqi** [comment]
Just expose port 9995 in https://github.com/apache/bigtop/blob/master/bigtop-packages/src/common/bigtop-ambari-mpack/dev-support/docker/centos7/build-containers.sh#L44,  not in Mpack service module.
In Mpack test, Zeppelin server would be always installed ambari-agent01.

**Review by guyuqi — APPROVED** [review]

**Comment by guyuqi** [comment]
Thanks, @kevinw66

**Pull request merged**
