### PR TITLE
BIGTOP-3279. Bump Zookeeper to 3.4.13

### PR DESCRIPTION
**Pull request by sekikn**
Confirmed this patch worked on CentOS 7 & 8, Debian 9 & 10 and Ubuntu 18.04 at least.

### CODE REVIEW

**Comment by youngwookim** [comment]
+1

**Comment by sekikn** [comment]
Thanks! Just merged the PR.

**Comment by evans-ye** [comment]
@sekikn you can do PR merge in Github and it'll be merged to ASF repo as well.

**Comment by sekikn** [comment]
Oh I didn't know that. Thanks!

**Pull request closed without merging**
