### PR TITLE
Bump Solr to 8.3.1

### PR DESCRIPTION
**Pull request by evans-ye**

### CODE REVIEW

**Comment by evans-ye** [comment]
https://ci.bigtop.apache.org/view/Test/job/Build-Deploy-Smoke-Test-Pull-Request-All-Distros/24/

**Comment by leolb-aphp** [comment]
Build is failing because of:

```
[ERROR] The specified file '/bigtop/build/solr/rpm/BUILD/solr-8.3.1/solr/dist/solr-uima-8.3.1.jar' not exists
```

UIMA integration was removed in 7.5/8.0 as written on JIRA https://issues.apache.org/jira/browse/SOLR-11694

So that must somehow be removed from the requirements, I'm investigating..

**Comment by leolb-aphp** [comment]
I've opened https://github.com/apache/bigtop/pull/614

**Comment by evans-ye** [comment]
@leolb-aphp Yes. Please continue your contribution at #614. Let me close this one.

**Pull request closed without merging**
