### PR TITLE
BIGTOP-3380. Bump Tomcat to 8.5.57.

### PR DESCRIPTION
**Pull request by iwasakims**
Please refer to [BIGTOP-3380](https://issues.apache.org/jira/browse/BIGTOP-3380) for the background.

### CODE REVIEW

**Comment by iwasakims** [comment]
I ran smoke-tests of hadoop-kms which uses bigtop-tomcat with the following configuration.
```
docker:
        memory_limit: "6g"
        image: "bigtop/puppet:trunk-centos-8"

distro: centos
components: [hdfs, kms]
enable_local_repo: true
smoke_test_components: [kms]
```
```
$ ./docker-hadoop.sh -c 1 --smoke-tests
...(snip)
Now testing...
:bigtop-tests:smoke-tests:kms:test (Thread[Daemon worker,5,main]) completed. Took 13.036 secs.

BUILD SUCCESSFUL in 2m 7s
39 actionable tasks: 7 executed, 32 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```

**Comment by iwasakims** [comment]
It worked for me on CentOS 7 too.
```
docker:
        memory_limit: "8g"
        image: "bigtop/puppet:trunk-centos-7"
distro: centos
components: [hdfs, kms]
enable_local_repo: true
smoke_test_components: [kms]
```
```
$ ./docker-hadoop.sh -c 1 --smoke-tests
...(snip)
Now testing...
:bigtop-tests:smoke-tests:kms:test (Thread[Daemon worker,5,main]) completed. Took 10.312 secs.

BUILD SUCCESSFUL in 54s
39 actionable tasks: 7 executed, 32 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```

**Comment by sekikn** [comment]
+1

**Comment by iwasakims** [comment]
Thanks, @sekikn.

**Comment by evans-ye** [comment]
+1

**Pull request merged**
