### PR TITLE
BIGTOP-3632: Bump elasticsearch's log4j dependencies to 2.17.0

### PR DESCRIPTION
**Pull request by yoda-mon**
Update log4j2 version to 2.17.0 to keep up the issue https://issues.apache.org/jira/browse/BIGTOP-3613.

Tested by 
- `./gradlew elasticsearch-pkg` for bigtop
- `./gradlew precommit` on patched elasticsearch's source (cf. [TESTING.asciidoc](https://github.com/elastic/elasticsearch/blob/5.6/TESTING.asciidoc#running-verification-tasks))

### CODE REVIEW

**Comment by iwasakims** [comment]
Thanks for working on this, @yoda-mon. Could you update bigtop-packages/src/rpm/elasticsearch/SPECS/elasticsearch.spec too? like

```
$ git diff
diff --git a/bigtop-packages/src/rpm/elasticsearch/SPECS/elasticsearch.spec b/bigtop-packages/src/rpm/elasticsearch/SPECS/elasticsearch.spec
index c7f94f87..f3619375 100644
--- a/bigtop-packages/src/rpm/elasticsearch/SPECS/elasticsearch.spec
+++ b/bigtop-packages/src/rpm/elasticsearch/SPECS/elasticsearch.spec
@@ -53,6 +53,7 @@ Source1: do-component-build
 Source2: install_%{name}.sh
 Source3: elasticsearch.default
 Source4: elasticsearch.init
+#BIGTOP_PATCH_FILES
 Requires: bigtop-utils >= 0.7

 # CentOS 5 does not have any dist macro
@@ -71,6 +72,8 @@ an HTTP web interface and schema-free JSON documents.
 %prep
 %setup -n elasticsearch-%{elasticsearch_base_version}

+#BIGTOP_PATCH_COMMAND
+
 %build
 env FULL_VERSION=%{elasticsearch_base_version} bash %{SOURCE1}
```

The patch0-log4j2-2.17.0.diff is not applied without those lines for rpm packaging.

```
$ rpm -qlp output/elasticsearch/noarch/elasticsearch-5.6.14-2.el8.noarch.rpm | grep log4j
/etc/elasticsearch/conf.dist/log4j2.properties
/usr/lib/elasticsearch/lib/log4j-1.2-api-2.11.1.jar
/usr/lib/elasticsearch/lib/log4j-api-2.11.1.jar
/usr/lib/elasticsearch/lib/log4j-core-2.11.1.jar
```

**Comment by iwasakims** [comment]
The build script replaces `#BIGTOP_PATCH_FILES` with list of patches and `#BIGTOP_PATCH_COMMANDS` with patch command.
https://github.com/apache/bigtop/blob/master/packages.gradle#L589-L608

We don't need addtitional fix for deb packaging.

**Comment by yoda-mon** [comment]
updated, it seems to work.

```
$ ./gradlew elasticsearch-pkg
$ rpm -qlp output/elasticsearch/noarch/elasticsearch-5.6.14-2.el8.noarch.rpm | grep log4j
/etc/elasticsearch/conf.dist/log4j2.properties
/usr/lib/elasticsearch/lib/log4j-1.2-api-2.17.0.jar
/usr/lib/elasticsearch/lib/log4j-api-2.17.0.jar
/usr/lib/elasticsearch/lib/log4j-core-2.17.0.jar
```

**Comment by iwasakims** [comment]
Thanks for the update. smoke-tests of elasticsearch passed on CentOS8.

```
$ ./docker-hadoop.sh \
   --create 1 \
   --image bigtop/puppet:trunk-centos-8 \
   --memory 16g \
   --repo file:///bigtop-home/output \
   --disable-gpg-check \
   --stack elasticsearch \
   --smoke-tests elasticsearch
...
Now testing...
:bigtop-tests:smoke-tests:elasticsearch:test (Thread[Execution worker for ':',5,main]) completed. Took 2.366 secs.

BUILD SUCCESSFUL in 35s
34 actionable tasks: 7 executed, 27 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```

**Review by iwasakims — APPROVED** [review]
It worked on Ubuntu 20.04 too. +1.

```
$ dpkg-deb -c ./output/elasticsearch/elasticsearch_5.6.14-2_all.deb | grep log4j
-rw-r--r-- root/root      4456 2022-01-21 04:25 ./etc/elasticsearch/conf.dist/log4j2.properties
-rw-r--r-- root/root    208199 2022-01-21 04:25 ./usr/lib/elasticsearch/lib/log4j-1.2-api-2.17.0.jar
-rw-r--r-- root/root    301742 2022-01-21 04:25 ./usr/lib/elasticsearch/lib/log4j-api-2.17.0.jar
-rw-r--r-- root/root   1789297 2022-01-21 04:25 ./usr/lib/elasticsearch/lib/log4j-core-2.17.0.jar
```
```
$ ./docker-hadoop.sh \
   --create 1 \
   --image bigtop/puppet:trunk-ubuntu-20.04 \
   --memory 16g \
   --repo file:///bigtop-home/output/apt \
   --disable-gpg-check \
   --stack elasticsearch \
   --smoke-tests elasticsearch
...
Now testing...
:bigtop-tests:smoke-tests:elasticsearch:test (Thread[Execution worker for ':' Thread 7,5,main]) completed. Took 2.369 secs.

BUILD SUCCESSFUL in 34s
34 actionable tasks: 7 executed, 27 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```

**Comment by iwasakims** [comment]
I merged this to master and branch-3.0. Thanks for the contribution, @yoda-mon!

**Pull request merged**
