### PR TITLE
BIGTOP-3788: Fix Ambari-HDFS components fail to start when kerberos enabled

### PR DESCRIPTION
**Pull request by timyuer**
…nabled

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by timyuer** [comment]
fix_mapreduce_check

**Comment by guyuqi** [comment]
Thanks for working on it. @timyuer 
Would you like to offer the scripts(or Readme) to config, install and test Kerberis Clients using Ambari wizard?

**Comment by timyuer** [comment]
@guyuqi 
It has been offered by @kevinw66 in https://github.com/apache/bigtop/pull/940.

**Comment by guyuqi** [comment]
What I mean is about  `Enable Kerberos Wizard`:



like `Existing MIT KDC` or `Existing Active Directory` ?   `Realm name `or `KDC hosts` ?

**Comment by timyuer** [comment]
Sure

**Comment by timyuer** [comment]
@guyuqi 
I have added the README for Kerberos configuration.

**Comment by guyuqi** [comment]
May I ask which Hadoop version did you work based on?
It seems it failed to start namenode:

```
resource_management.core.exceptions.ExecutionFailed: Execution of 'hdfs --config /etc/hadoop/conf namenode -format -nonInteractive' returned 1. WARNING: HADOOP_SECURE_DN_USER has been replaced by HDFS_DATANODE_SECURE_USER. Using value of HADOOP_SECURE_DN_USER.
WARNING: HADOOP_NAMENODE_OPTS has been replaced by HDFS_NAMENODE_OPTS. Using value of HADOOP_NAMENODE_OPTS.
WARNING: /var/log/hadoop/hdfs does not exist. Creating.
22/08/29 08:20:12 INFO namenode.NameNode: STARTUP_MSG: 
....
..
Caused by: KrbException: Message stream modified (41)
	at sun.security.krb5.KrbKdcRep.check(KrbKdcRep.java:103)
	at sun.security.krb5.KrbAsRep.decrypt(KrbAsRep.java:159)
	at sun.security.krb5.KrbAsRep.decryptUsingKeyTab(KrbAsRep.java:121)
	at sun.security.krb5.KrbAsReqBuilder.resolve(KrbAsReqBuilder.java:310)
	at sun.security.krb5.KrbAsReqBuilder.action(KrbAsReqBuilder.java:498)
	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:782)
	... 20 more
22/08/29 08:20:12 INFO util.ExitUtil: Exiting with status 1: org.apache.hadoop.security.KerberosAuthException: failure to login: for principal: nn/ambari-agent-01@EXAMPLE.COM from keytab /etc/security/keytabs/nn.service.keytab javax.security.auth.login.LoginException: Message stream modified (41)
22/08/29 08:20:12 INFO namenode.NameNode: SHUTDOWN_MSG: 
/************************************************************
SHUTDOWN_MSG: Shutting down NameNode at ambari-agent-01/192.168.160.3
************************************************************/
```

**Comment by guyuqi** [comment]
Deploy HDFS, mapreduce, zookeeper services first, and then enable Kerberos.
It failed to start HDFS.

**Comment by timyuer** [comment]
> May I ask which Hadoop version did you work based on?
> It seems it failed to start namenode:
> ```
> resource_management.core.exceptions.ExecutionFailed: Execution of 'hdfs --config /etc/hadoop/conf namenode -format -nonInteractive' returned 1. WARNING: HADOOP_SECURE_DN_USER > has been replaced by HDFS_DATANODE_SECURE_USER. Using value of HADOOP_SECURE_DN_USER.
> WARNING: HADOOP_NAMENODE_OPTS has been replaced by HDFS_NAMENODE_OPTS. Using value of HADOOP_NAMENODE_OPTS.
> WARNING: /var/log/hadoop/hdfs does not exist. Creating.
> 22/08/29 08:20:12 INFO namenode.NameNode: STARTUP_MSG: 
> ....
> ..
> Caused by: KrbException: Message stream modified (41)
> 	at sun.security.krb5.KrbKdcRep.check(KrbKdcRep.java:103)
> 	at sun.security.krb5.KrbAsRep.decrypt(KrbAsRep.java:159)
> 	at sun.security.krb5.KrbAsRep.decryptUsingKeyTab(KrbAsRep.java:121)
> 	at sun.security.krb5.KrbAsReqBuilder.resolve(KrbAsReqBuilder.java:310)
> 	at sun.security.krb5.KrbAsReqBuilder.action(KrbAsReqBuilder.java:498)
> 	at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:782)
> 	... 20 more
> 22/08/29 08:20:12 INFO util.ExitUtil: Exiting with status 1: org.apache.hadoop.security.KerberosAuthException: failure to login: for principal: nn/ambari-agent-01@EXAMPLE.COM > from keytab /etc/security/keytabs/nn.service.keytab javax.security.auth.login.LoginException: Message stream modified (41)
> 22/08/29 08:20:12 INFO namenode.NameNode: SHUTDOWN_MSG: 
> /************************************************************
> SHUTDOWN_MSG: Shutting down NameNode at ambari-agent-01/192.168.160.3
> ************************************************************/
> ```

@guyuqi 
Please remember to comment this line for high version of JDK 1.8 when fill the KDC account
Kerberos_Ambari_wizard_4

**Comment by guyuqi** [comment]
+1

**Comment by guyuqi** [comment]
The solr and some other services would fail to start when enabling Kerberos.
Let's fix them in the subsequent separated PRs/Jiras.

**Comment by guyuqi** [comment]
Merged, thanks.

**Pull request merged**
