### PR TITLE
BIGTOP-3591: Upgrading Bigtop-Mpack services deploying scripts aligne…

### PR DESCRIPTION
**Pull request by guyuqi**
After upgrading Ambari to 2.7.5, it failed to install the services from the Bigtop-Mpack.
The patch is is to upgrade Bigtop-Mpack services deploying scripts and fix the related issues.
Successfully install ambari-2.7.5 and deploy related services on Centos-7. 

All modified files are under module:
`bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack`

### CODE REVIEW

**Comment by guyuqi** [comment]
Successfully deploy hdfs, mapreduce2, Yarn , zookeeper services on Centos-7.

ambari-version


services

**Review by iwasakims — APPROVED** [review]
Thanks for working on this, @guyuqi. I tested this on CentOS 7 container. I used local Repository (file:///bigtop-home/output) in the container on wizard of Ambari. While ZooKeeper and HDFS are deployed, I got error on starting YARN services.

I think we should merge this first then address error, nits and platforms other than CentOS 7 in follow-up JIRAs.

```
$ cd provisioner/docker
$ ./docker-hadoop.sh --create 1 --image bigtop/puppet:trunk-centos-7 --memory 16g --repo file:///bigtop-home/output --disable-gpg-check --stack ambari
$ ./docker-hadoop.sh --exec 1 /bin/bash
# yum install bigtop-ambari-mpack
# ambari-server install-mpack --mpack=/usr/lib/bigtop-ambari-mpack/bgtp-ambari-mpack-1.0.0.0-SNAPSHOT-bgtp-ambari-mpack.tar.gz
# systemctl restart ambari-server ambari-agent

(creating cluster by Ambari Web-UI using browser...)
```

**Comment by iwasakims** [comment]
I got following on starting up YARN daemons via Ambari.

```
...
WARNING: YARN_LOG_DIR has been replaced by HADOOP_LOG_DIR. Using value of YARN_LOG_DIR.
WARNING: YARN_LOGFILE has been replaced by HADOOP_LOGFILE. Using value of YARN_LOGFILE.
WARNING: YARN_PID_DIR has been replaced by HADOOP_PID_DIR. Using value of YARN_PID_DIR.
WARNING: YARN_OPTS has been replaced by HADOOP_OPTS. Using value of YARN_OPTS.
WARNING: Use of this script to start the MR JobHistory daemon is deprecated.
WARNING: Attempting to execute replacement "mapred --daemon start" instead.
ERROR: Cannot find configuration directory "/usr/lib/hadoop-yarn/conf"
Usage: mapred [OPTIONS] SUBCOMMAND [SUBCOMMAND OPTIONS]
 or    mapred [OPTIONS] CLASSNAME [CLASSNAME OPTIONS]
  where CLASSNAME is a user-provided Java class
```

**Comment by guyuqi** [comment]
> Thanks for working on this, @guyuqi. I tested this on CentOS 7 container. I used local Repository (file:///bigtop-home/output) in the container on wizard of Ambari. While ZooKeeper and HDFS are deployed, I got error on starting YARN services.
> 
> I think we should merge this first then address error, nits and platforms other than CentOS 7 in follow-up JIRAs.
> 
> ```
> $ cd provisioner/docker
> $ ./docker-hadoop.sh --create 1 --image bigtop/puppet:trunk-centos-7 --memory 16g --repo file:///bigtop-home/output --disable-gpg-check --stack ambari
> $ ./docker-hadoop.sh --exec 1 /bin/bash
> # yum install bigtop-ambari-mpack
> # ambari-server install-mpack --mpack=/usr/lib/bigtop-ambari-mpack/bgtp-ambari-mpack-1.0.0.0-SNAPSHOT-bgtp-ambari-mpack.tar.gz
> # systemctl restart ambari-server ambari-agent
> 
> (creating cluster by Ambari Web-UI using browser...)
> ```

@iwasakims Thank you for reviewing this PR. 
I tested it in three independent virtual machines and deployed Hadoop 2.10 by Ambari Web UI with Bigtop repo like `http://repos.bigtop.apache.org/releases/1.5.0/ubuntu/18.04/x86_64`.
It maybe the issue for deploying Hadoop 3.

Agree that let's merge it and then address the subsequent issues, thanks.

**Pull request merged**
