### PR TITLE
BIGTOP-3237: Add smoke tests for YCSB

### PR DESCRIPTION
**Pull request by guyuqi**

### CODE REVIEW

**Comment by evans-ye** [comment]
Patch looks great! Let me run through the CI and get back to you.

**Comment by evans-ye** [comment]
https://ci.bigtop.apache.org/job/Build-Deploy-Smoke-Test-Pull-Request-All-Distros/OS=centos-7-x86_64-deploy/27/console

Probably we need to add ycsb command lookup in provisioner?

**Comment by sekikn** [comment]
The PR worked in my environment, as follows. @evans-ye Would you kick the CI again? (Sorry that I'm not familar with the CI environment...)

```
~/bigtop/provisioner/docker$ cat config_ubuntu-16.04.yaml 

(snip)

components: [hdfs, yarn, mapreduce, hbase, ycsb]
enable_local_repo: true
smoke_test_components: [ycsb]
~/bigtop/provisioner/docker$ ./docker-hadoop.sh -C config_ubuntu-16.04.yaml -c 1 -s

(snip)

> Task :bigtop-tests:smoke-tests:ycsb:test
Task ':bigtop-tests:smoke-tests:ycsb:test' is not up-to-date because:
  No history is available.
Starting process 'Gradle Test Executor 2'. Working directory: /bigtop-home/bigtop-tests/smoke-tests/ycsb Command: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Dawt.toolkit=sun.awt.X11.XToolkit -Dfile.encoding.pkg=sun.io -Dfile.separator=/ -Djava.awt.graphicsenv=sun.awt.X11GraphicsEnvironment -Djava.awt.printerjob=sun.print.PSPrinterJob -Djava.class.path=/root/.gradle/wrapper/dists/gradle-4.10.3-bin/016e637c7ef47db2d3e632a3936ca351/gradle-4.10.3/lib/gradle-launcher-4.10.3.jar -Djava.class.version=52.0 -Djava.endorsed.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed -Djava.ext.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext -Djava.home=/usr/lib/jvm/java-8-openjdk-amd64/jre -Djava.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib -Djava.runtime.name=OpenJDK Runtime Environment -Djava.runtime.version=1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Djava.specification.name=Java Platform API Specification -Djava.specification.vendor=Oracle Corporation -Djava.specification.version=1.8 -Djava.vendor=Private Build -Djava.vendor.url=http://java.oracle.com/ -Djava.vendor.url.bug=http://bugreport.sun.com/bugreport/ -Djava.version=1.8.0_242 -Djava.vm.info=mixed mode -Djava.vm.name=OpenJDK 64-Bit Server VM -Djava.vm.specification.name=Java Virtual Machine Specification -Djava.vm.specification.vendor=Oracle Corporation -Djava.vm.specification.version=1.8 -Djava.vm.vendor=Private Build -Djava.vm.version=25.242-b08 -Dlibrary.jansi.path=/root/.gradle/native/jansi/1.14/linux64 -Dline.separator=
 -Dorg.gradle.appname=gradlew -Dorg.gradle.native=false -Dos.arch=amd64 -Dos.name=Linux -Dos.version=5.3.0-28-generic -Dpath.separator=: -Dsun.arch.data.model=64 -Dsun.boot.class.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes -Dsun.boot.library.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64 -Dsun.cpu.endian=little -Dsun.cpu.isalist -Dsun.io.unicode.encoding=UnicodeLittle -Dsun.java.command=org.gradle.launcher.daemon.bootstrap.GradleDaemon 4.10.3 -Dsun.java.launcher=SUN_STANDARD -Dsun.jnu.encoding=ANSI_X3.4-1968 -Dsun.management.compiler=HotSpot 64-Bit Tiered Compilers -Dsun.os.patch.level=unknown -Duser.dir=/bigtop-home -Duser.home=/root -Duser.name=root -Duser.timezone -Dfile.encoding=ANSI_X3.4-1968 -Djava.io.tmpdir=/tmp -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /root/.gradle/caches/4.10.3/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 2'
Successfully started process 'Gradle Test Executor 2'

Gradle Test Executor 2 finished executing tests.

> Task :bigtop-tests:smoke-tests:ycsb:test
Finished generating test XML results (0.018 secs) into: /bigtop-home/bigtop-tests/smoke-tests/ycsb/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.047 secs) into: /bigtop-home/bigtop-tests/smoke-tests/ycsb/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:ycsb:test (Thread[Task worker for ':' Thread 4,5,main]) completed. Took 13 mins 58.498 secs.

BUILD SUCCESSFUL in 16m 32s
37 actionable tasks: 8 executed, 29 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```

**Comment by JunHe77** [comment]
Also passed on my local test , let's merge this. Thans @guyuqi , @evans-ye , @sekikn .

**Comment by evans-ye** [comment]
LGTM +1.
https://ci.bigtop.apache.org/view/Test/job/Build-Deploy-Smoke-Test-Pull-Request-All-Distros/29/
(errors are due to CI server, not the PR)

BTW, @sekikn you can merge this as well. No need to wait Sorry for the late reply @guyuqi .

**Comment by evans-ye** [comment]
Oh. Just saw that @JunHe77 has it merged. Thanks!

**Pull request merged**
