### PR TITLE
BIGTOP-3425. Deploying Ambari fails on Fedora 31.

### PR DESCRIPTION
**Pull request by sekikn**

### CODE REVIEW

**Comment by iwasakims** [comment]
@sekikn ambari-server depends on initspripts but ambari-agent does not. Adding the dependency to ambari-agent too is the right fix?

```
$ rpm -q --requires -p output/ambari/noarch/ambari-server-2.6.1.0-1.el8.noarch.rpm
/bin/sh
/bin/sh
/bin/sh
/bin/sh
curl
initscripts
openssl
postgresql-server >= 8.1
python2 >= 2.6
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1

$ rpm -q --requires -p output/ambari/noarch/ambari-agent-2.6.1.0-1.el8.noarch.rpm
/bin/sh
/bin/sh
/bin/sh
/bin/sh
openssl
python2 >= 2.6
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
zlib
```

**Comment by iwasakims** [comment]
I guess distros other than Fedora 31 always have initscripts required by basic packages.

**Comment by sekikn** [comment]
Thank you for the comment @iwasakims, that's the right solution. I updated the PR, and confirmed Ambari deployment and smoke test succeeded with it.

```
[vagrant@localhost bigtop]$ cat /etc/redhat-release 
Fedora release 31 (Thirty One)
[vagrant@localhost bigtop]$ git diff
diff --git a/bigtop-packages/src/rpm/ambari/SPECS/ambari.spec b/bigtop-packages/src/rpm/ambari/SPECS/ambari.spec
index 60c943f8..9d82422b 100644
--- a/bigtop-packages/src/rpm/ambari/SPECS/ambari.spec
+++ b/bigtop-packages/src/rpm/ambari/SPECS/ambari.spec
@@ -260,7 +260,7 @@ exit 0
 %package agent
 Summary: Ambari Agent
 Group: Development/Libraries
-Requires: openssl, zlib, python2 >= 2.6
+Requires: openssl, zlib, python2 >= 2.6, initscripts
 AutoProv: no
 AutoReqProv: no
 %description agent
[vagrant@localhost bigtop]$ ./gradlew ambari-clean ambari-pkg repo -Dbuildwithdeps=true

(snip)

BUILD SUCCESSFUL in 1h 13m 58s
14 actionable tasks: 14 executed
[vagrant@localhost bigtop]$ rpm -qR output/ambari/noarch/ambari-agent-2.6.1.0-1.fc31.noarch.rpm 
/bin/sh
/bin/sh
/bin/sh
/bin/sh
initscripts
openssl
python2 >= 2.6
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
zlib
[vagrant@localhost docker]$ ./docker-hadoop.sh -d -C config_fedora-31.yaml --disable-gpg-check --enable-local-repo --repo file:///bigtop-home/output --stack 'bigtop-utils, ambari' --smoke-tests ambari -c 3

(snip)

Notice: /Stage[main]/Ambari::Agent/Package[ambari-agent]/ensure: created
Notice: /Stage[main]/Ambari::Agent/File[/etc/ambari-agent/conf/ambari-agent.ini]/content: content changed '{md5}21cca116446906eefe38ac81a4e065dc' to '{md5}b9b121ddde12096e451bd7bf60fb4cc2'
Notice: /Stage[main]/Jdk/Package[jdk]/ensure: created
Notice: /Stage[main]/Ambari::Agent/Service[ambari-agent]/ensure: ensure changed 'stopped' to 'running'
Notice: Applied catalog in 188.72 seconds
Notice: /Stage[main]/Hadoop_cluster_node/User[jenkins]/ensure: created
Notice: /Stage[main]/Hadoop_cluster_node/User[testuser]/ensure: created
Notice: /Stage[main]/Hadoop_cluster_node/User[hudson]/ensure: created
Notice: /Stage[main]/Ambari::Agent/Package[ambari-agent]/ensure: created
Notice: /Stage[main]/Ambari::Agent/File[/etc/ambari-agent/conf/ambari-agent.ini]/content: content changed '{md5}21cca116446906eefe38ac81a4e065dc' to '{md5}b9b121ddde12096e451bd7bf60fb4cc2'
Notice: /Stage[main]/Ambari::Agent/Service[ambari-agent]/ensure: ensure changed 'stopped' to 'running'
Notice: Applied catalog in 215.53 seconds
Notice: /Stage[main]/Ambari::Server/Package[ambari-server]/ensure: created
Notice: /Stage[main]/Ambari::Server/Exec[mpack install]/returns: executed successfully
Notice: /Stage[main]/Ambari::Server/Exec[server setup]/returns: executed successfully
Notice: /Stage[main]/Ambari::Server/Service[ambari-server]/ensure: ensure changed 'stopped' to 'running'
Notice: /Stage[main]/Ambari::Agent/Package[ambari-agent]/ensure: created
Notice: /Stage[main]/Ambari::Agent/File[/etc/ambari-agent/conf/ambari-agent.ini]/content: content changed '{md5}21cca116446906eefe38ac81a4e065dc' to '{md5}b9b121ddde12096e451bd7bf60fb4cc2'
Notice: /Stage[main]/Ambari::Agent/Service[ambari-agent]/ensure: ensure changed 'stopped' to 'running'

(snip)

===== START TO RUN SMOKE TESTS: ambari =====

(snip)

org.apache.bigtop.itest.ambari.TestAmbariSmoke > testBlueprints STANDARD_OUT
    [href:http://localhost:8080/api/v1/blueprints, items:[]]

org.apache.bigtop.itest.ambari.TestAmbariSmoke > testStackNameVersion STANDARD_OUT
    [versions:[[Versions:[stack_version:2.0, stack_name:ODPi], href:http://localhost:8080/api/v1/stacks/ODPi/versions/2.0]], Stacks:[stack_name:ODPi], href:http://localhost:8080/api/v1/stacks/ODPi]

Gradle Test Executor 2 finished executing tests.

> Task :bigtop-tests:smoke-tests:ambari:test
Finished generating test XML results (0.026 secs) into: /bigtop-home/bigtop-tests/smoke-tests/ambari/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.046 secs) into: /bigtop-home/bigtop-tests/smoke-tests/ambari/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:ambari:test (Thread[Daemon worker,5,main]) completed. Took 3.911 secs.

BUILD SUCCESSFUL in 2m 37s
```

**Review by iwasakims — APPROVED** [review]
+1

**Comment by iwasakims** [comment]
merged to master and branch-1.5.

**Pull request merged**
