### PR TITLE
BIGTOP-3799: Support parent directory configuration for Hive rpm build script

### PR DESCRIPTION
**Pull request by kevinw66**
### How was this patch tested?
diff result:
```
501198 blocks
501198 blocks
1d0
< ./etc/hive
241 blocks
241 blocks
1171 blocks
1172 blocks
1d0
< ./etc/hive-hcatalog
12 blocks
12 blocks
164587 blocks
164587 blocks
12 blocks
12 blocks
12 blocks
12 blocks
7013 blocks
7014 blocks
1d0
< ./etc/hive-webhcat
12 blocks
12 blocks
```

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by sekikn** [comment]
@kevinw66 Would you resolve the conflicts?

**Comment by kevinw66** [comment]
> @kevinw66 Would you resolve the conflicts?

resolved

**Comment by sekikn** [comment]
+1, No problematic difference in the rpm packages between the original and the patched versions (without the `parentDir` option). The smoke test also passed.

```
$ ./gradlew hive-clean hive-pkg -Dbuildwithdeps=true

...

BUILD SUCCESSFUL in 24m 55s
37 actionable tasks: 37 executed
$ mv output/hive ~
$ curl -sL https://patch-diff.githubusercontent.com/raw/apache/bigtop/pull/998.diff | git apply
$ git diff --stat 
 bigtop-packages/src/common/hive/install_hive.sh | 200 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------------------------------------------------------------------
 bigtop-packages/src/deb/hive/rules              |   2 +-
 bigtop-packages/src/rpm/hive/SPECS/hive.spec    | 105 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------
 3 files changed, 175 insertions(+), 132 deletions(-)
$ ./gradlew hive-clean hive-pkg repo

...

BUILD SUCCESSFUL in 6m 10s                                                                                             
9 actionable tasks: 9 executed                                                                                         
$ for i in $(ls output/hive/noarch); do diff <(rpm -qlp output/hive/noarch/$i) <(rpm -qlp ~/hive/noarch/$i); done
1d0
< /etc/hive
1d0
< /etc/hive-hcatalog
1d0
< /etc/hive-webhcat
$ cd provisioner/docker
$ ./docker-hadoop.sh -d -C config_centos-7.yaml -r file:///bigtop-home/output -G -k hdfs,yarn,hive -s hive -c 3

...

> Task :bigtop-tests:smoke-tests:hive:test
Finished generating test XML results (0.016 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hive/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.032 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hive/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:hive:test (Thread[Daemon worker,5,main]) completed. Took 17.587 secs.

BUILD SUCCESSFUL in 1m 34s
30 actionable tasks: 7 executed, 23 up-to-date
```

The `parentDir` option works as expected too.

```
$ ./gradlew hive-clean hive-pkg -PparentDir=/usr/bigtop

...

BUILD SUCCESSFUL in 6m 40s
7 actionable tasks: 7 executed
$ for i in $(ls output/hive/noarch); do echo $i; rpm -qlpv output/hive/noarch/$i; echo; done                                                                                                                          

...

hive-3.1.3-1.el7.noarch.rpm                                                                                                                                                                                                                   
drwxr-xr-x    2 hive    hive                        0  9月 12 14:39 /etc/hive                                                                                                                                                                 
drwxr-xr-x    2 root    root                        0  9月 12 14:39 /usr/bigtop/etc/hive/conf.dist                                                                                                                                            

...

-rw-r--r--    1 root    root                     2662 10月 24  2019 /usr/bigtop/etc/hive/conf.dist/parquet-logging.properties                                                                                                                 
-rwxr-xr-x    1 root    root                      423  9月 12 14:39 /usr/bigtop/usr/bin/beeline                                                                                                                                               
-rwxr-xr-x    1 root    root                      420  9月 12 14:39 /usr/bigtop/usr/bin/hive                                                                                                                                                  
-rwxr-xr-x    1 root    root                      427  9月 12 14:39 /usr/bigtop/usr/bin/hiveserver2                                                                                                                                           
drwxr-xr-x    2 root    root                        0  9月 12 14:39 /usr/bigtop/usr/lib/hive/bin                                                                                                                                              

...

-rw-r--r--    1 root    root                      265  3月 28 19:39 /usr/bigtop/usr/lib/hive/scripts/metastore/upgrade/postgres/upgrade.order.postgres                                                                                        
drwxr-xr-x    2 root    root                        0  9月 12 14:39 /usr/bigtop/usr/share/doc/hive-3.1.3                                                                                                                                      

...

-rw-r--r--    1 root    root                      224  3月 28 19:39 /usr/bigtop/usr/share/doc/hive-3.1.3/examples/queries/union.q                                                                                                             
-rw-r--r--    1 root    root                     1943  9月 12 14:39 /usr/bigtop/usr/share/man/man1/hive.1.gz                                                                                                                                  
drwxr-xr-x    2 hive    hive                        0  9月 12 14:39 /usr/bigtop/var/lib/hive                                                                                                                                                  
drwxrwxrwt    2 hive    hive                        0  9月 12 14:39 /usr/bigtop/var/lib/hive/metastore                                                                                                                                        
drwxr-xr-x    2 hive    hive                        0  9月 12 14:39 /var/log/hive                                                                                                                                                             
drwxr-xr-x    2 hive    hive                        0  9月 12 14:39 /var/run/hive                                                                                                                                                             
                                                                                                                                                                                                                                              
hive-hbase-3.1.3-1.el7.noarch.rpm                                                                                                                                                                                                             
lrwxrwxrwx    1 root    root                       42  9月 12 14:39 /usr/bigtop/usr/lib/hive/lib/hbase-client.jar -> /usr/bigtop/usr/lib/hbase/hbase-client.jar                                                                               
lrwxrwxrwx    1 root    root                       42  9月 12 14:39 /usr/bigtop/usr/lib/hive/lib/hbase-common.jar -> /usr/bigtop/usr/lib/hbase/hbase-common.jar                                                                               
lrwxrwxrwx    1 root    root                       49  9月 12 14:39 /usr/bigtop/usr/lib/hive/lib/hbase-hadoop-compat.jar -> /usr/bigtop/usr/lib/hbase/hbase-hadoop-compat.jar                                                                 
lrwxrwxrwx    1 root    root                       50  9月 12 14:39 /usr/bigtop/usr/lib/hive/lib/hbase-hadoop2-compat.jar -> /usr/bigtop/usr/lib/hbase/hbase-hadoop2-compat.jar                                                               
lrwxrwxrwx    1 root    root                       45  9月 12 14:39 /usr/bigtop/usr/lib/hive/lib/hbase-procedure.jar -> /usr/bigtop/usr/lib/hbase/hbase-procedure.jar                                                                         
lrwxrwxrwx    1 root    root                       44  9月 12 14:39 /usr/bigtop/usr/lib/hive/lib/hbase-protocol.jar -> /usr/bigtop/usr/lib/hbase/hbase-protocol.jar                                                                           
lrwxrwxrwx    1 root    root                       42  9月 12 14:39 /usr/bigtop/usr/lib/hive/lib/hbase-server.jar -> /usr/bigtop/usr/lib/hbase/hbase-server.jar                                                                               
-rw-r--r--    1 root    root                   121352  9月 12 14:38 /usr/bigtop/usr/lib/hive/lib/hive-hbase-handler-3.1.3.jar                                                                                                                 
lrwxrwxrwx    1 root    root                       28  9月 12 14:39 /usr/bigtop/usr/lib/hive/lib/hive-hbase-handler.jar -> hive-hbase-handler-3.1.3.jar                                                                                       
                                                                                                                                                                                                                                              
hive-hcatalog-3.1.3-1.el7.noarch.rpm                                                                                                                                                                                                          
drwxrwxr-x    2 hive    hive                        0  9月 12 14:39 /etc/hive-hcatalog                                                                                                                                                        
drwxr-xr-x    2 root    root                        0  9月 12 14:39 /usr/bigtop/etc/hive-hcatalog/conf.dist                                                                                                                                   
-rwxr-xr-x    1 root    root                     1505  3月 28 19:39 /usr/bigtop/etc/hive-hcatalog/conf.dist/jndi.properties                                                                                                                   
-rwxr-xr-x    1 root    root                     4593 10月 24  2019 /usr/bigtop/etc/hive-hcatalog/conf.dist/proto-hive-site.xml                                                                                                               
-rwxr-xr-x    1 root    root                      616  9月 12 14:39 /usr/bigtop/usr/bin/hcat                                                                                                                                                  
drwxr-xr-x    2 root    root                        0  9月 12 14:39 /usr/bigtop/usr/lib/hive-hcatalog

...

lrwxrwxrwx    1 root    root                       33  9月 12 14:39 /usr/bigtop/usr/lib/hive-hcatalog/share/hcatalog/hive-hcatalog-streaming.jar -> hive-hcatalog-streaming-3.1.3.jar                                                         
-rw-r--r--    1 root    root                     1347  9月 12 14:39 /usr/bigtop/usr/share/man/man1/hive-hcatalog.1.gz                                                                                                                         
drwxrwxr-x    2 hive    hive                        0  9月 12 14:39 /usr/bigtop/var/lib/hive-hcatalog                                                                                                                                         
drwxrwxr-x    2 hive    hive                        0  9月 12 14:39 /var/log/hive-hcatalog                                                                                                                                                    
                                                                                                                                                                                                                                              
hive-hcatalog-server-3.1.3-1.el7.noarch.rpm                                                                                                                                                                                                   
-rwxr-xr-x    1 root    root                     4380  9月 12 14:39 /etc/rc.d/init.d/hive-hcatalog-server
-rw-r--r--    1 root    root                     1123  9月 12 14:39 /usr/bigtop/etc/default/hive-hcatalog-server

hive-jdbc-3.1.3-1.el7.noarch.rpm
drwxr-xr-x    2 root    root                        0  9月 12 14:39 /usr/bigtop/usr/lib/hive
drwxr-xr-x    2 root    root                        0  9月 12 14:39 /usr/bigtop/usr/lib/hive/jdbc
-rw-r--r--    1 root    root                 84267953  9月 12 14:37 /usr/bigtop/usr/lib/hive/jdbc/hive-jdbc-3.1.3-standalone.jar

hive-metastore-3.1.3-1.el7.noarch.rpm
-rwxr-xr-x    1 root    root                     4610  9月 12 14:39 /etc/rc.d/init.d/hive-metastore
-rw-r--r--    1 root    root                      932  9月 12 14:39 /usr/bigtop/etc/default/hive-metastore

hive-server2-3.1.3-1.el7.noarch.rpm
-rwxr-xr-x    1 root    root                     4606  9月 12 14:39 /etc/rc.d/init.d/hive-server2
-rw-r--r--    1 root    root                      930  9月 12 14:39 /usr/bigtop/etc/default/hive-server2

hive-webhcat-3.1.3-1.el7.noarch.rpm
drwxrwxr-x    2 hive    hive                        0  9月 12 14:39 /etc/hive-webhcat
drwxr-xr-x    2 root    root                        0  9月 12 14:39 /usr/bigtop/etc/hive-webhcat/conf.dist
-rwxr-xr-x    1 root    root                    13847  9月 12 14:39 /usr/bigtop/etc/hive-webhcat/conf.dist/webhcat-default.xml
-rwxr-xr-x    1 root    root                     2708  9月 12 14:39 /usr/bigtop/etc/hive-webhcat/conf.dist/webhcat-log4j2.properties
lrwxrwxrwx    1 root    root                       22  9月 12 14:39 /usr/bigtop/usr/lib/hive-hcatalog/etc/webhcat -> /etc/hive-webhcat/conf

...

-rw-r--r--    1 root    root                   194354  6月  9 14:25 /usr/bigtop/usr/lib/hive-hcatalog/share/webhcat/svr/lib/xml-apis-1.3.04.jar
                                                                                                                                                                                                                                              
hive-webhcat-server-3.1.3-1.el7.noarch.rpm                                                                                                                                                                                                    
-rwxr-xr-x    1 root    root                     4379  9月 12 14:39 /etc/rc.d/init.d/hive-webhcat-server                                                                                                                                      
-rw-r--r--    1 root    root                     1045  9月 12 14:39 /usr/bigtop/etc/default/hive-webhcat-server                                                                                                                               
```

**Comment by sekikn** [comment]
Merged into master. Thanks @kevinw66!

**Pull request merged**
