### PR TITLE
BIGTOP-4032: Drop Oozie in 3.3.0

### PR DESCRIPTION
**Pull request by MacChen01**
https://issues.apache.org/jira/browse/BIGTOP-4032

Drop Oozie based on the discussion in https://issues.apache.org/jira/browse/BIGTOP-3909

There is no new release of Oozie for a long time, so we will drop Oozie from 3.3.0 release.

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (BIGTOP-4032)
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by MacChen01** [comment]
@guyuqi @sekikn pls help review the code, thanks.

**Comment by MacChen01** [comment]
The associated components hdfs/yarn is ok, the log file:
https://gitee.com/macchen1/bigtop/blob/master/drop/hdfs.log
https://gitee.com/macchen1/bigtop/blob/master/drop/yarn.log

**Comment by sekikn** [comment]
+1, tested on CentOS 7, Rocky 8 and Ubuntu 22.04. Thanks @MacChen01!

**Comment by MacChen01** [comment]
> +1, tested on CentOS 7, Rocky 8 and Ubuntu 22.04. Thanks @MacChen01!

Thanks for you review and test. @sekikn

**Comment by uscxiexing** [comment]
> +1, tested on CentOS 7, Rocky 8 and Ubuntu 22.04. Thanks @MacChen01!

Thanks.we testd.Here's the result of our  @sekikn 
**centos7:**
https://gitee.com/macchen1/bigtop/blob/master/drop/centos-7-log/hdfs,hcfs-centos-7.log
https://gitee.com/macchen1/bigtop/blob/master/drop/centos-7-log/mapreduce-centos-7.log
https://gitee.com/macchen1/bigtop/blob/master/drop/centos-7-log/yarn-centos-7.log
**rocky8:**
https://gitee.com/macchen1/bigtop/blob/master/drop/rockylinux-8-log/hdfs,hcfs-rockylinux-8.log
https://gitee.com/macchen1/bigtop/blob/master/drop/rockylinux-8-log/mapreduce-rockylinux-8.log
https://gitee.com/macchen1/bigtop/blob/master/drop/rockylinux-8-log/yarn-rockylinux-8.log
**ubuntu22.04**
https://gitee.com/macchen1/bigtop/blob/master/drop/ubuntu-22.04-log/hdfs,hcfs-ubuntu-22.04.log
https://gitee.com/macchen1/bigtop/blob/master/drop/ubuntu-22.04-log/mapreduce-ubuntu-22.04.log
https://gitee.com/macchen1/bigtop/blob/master/drop/ubuntu-22.04-log/yarn-ubuntu-22.04.log

**Pull request merged**
