### PR TITLE
BIGTOP-3598. Bump HBase to 2.4.8.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3598

HBase 2.4 is current stable release line.

### CODE REVIEW

**Comment by iwasakims** [comment]
I got no issue on running smoke-tests of hbase on CentOS 8 x86_64. (We need the fix of https://github.com/apache/bigtop/pull/828 to to build Hadoop in current master branch.)

```
$ ./docker-hadoop.sh \
  --create 3 \
  --image bigtop/puppet:trunk-centos-8 \
  --memory 8g \
  --repo file:///bigtop-home/output \
  --disable-gpg-check \
  --stack hdfs,yarn,mapreduce,hbase \
  --smoke-tests hbase
...
:bigtop-tests:smoke-tests:hbase:test (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 3 mins 37.721 secs.

BUILD SUCCESSFUL in 4m 57s
36 actionable tasks: 9 executed, 27 up-to-date
```

**Comment by elukey** [comment]
Trying to build the new HBase version on debian-10 x86, I am seeing a ton of time spent in the `dh_strip_nondeterminism ` step, more specifically:
```
	Normalizing debian/hbase/usr/lib/hbase/hbase-hbtop-2.4.8.jar using File::StripNondeterminism::handlers::jar
```

**Comment by elukey** [comment]
I am trying to run the smoke tests via `docker-hadoop.sh` on Debian 11, and I keep getting `Failed to connect to bus: No such file or directory` when udev/systemd are installed, and then everything else fails afterwards (hadoop daemons don't come up, etc..).
It is probably something related to my docker compose version and os combination, anybody else with the same issue?

**Comment by iwasakims** [comment]
@elukey
I can reproduce the issues on my local Debian 11 and Fedora 33. I guess we need additional configuration for running recent systemd inside container like

* https://developers.redhat.com/blog/2014/05/05/running-systemd-within-docker-container
* https://developers.redhat.com/blog/2019/04/24/how-to-run-systemd-in-a-container

If CI env is OK, we can refer to the settings?

**Comment by iwasakims** [comment]
While systemd inside container is not generally recommended, we want to use it for testing init scripts and systemd configuraiton.

**Comment by elukey** [comment]
@iwasakims opened https://issues.apache.org/jira/browse/BIGTOP-3614, I found a workaround but I still need to work on the docker-compose yaml config.

**Comment by elukey** [comment]
@iwasakims I was finally able to run the smoke tests on debian 11 x86, all good!

+1 to proceed :)

**Comment by iwasakims** [comment]
Thanks, @elukey. I merged this.

**Pull request merged**
