### PR TITLE
BIGTOP-3741:Add Flink support for Bigtop 3.1.0 Mpack

### PR DESCRIPTION
**Pull request by smallyao**
### Description of PR
Add Flink support for Bigtop 3.1.0 Mpack

### How was this patch tested?
Tested in local vms , including enabling kerberos authentication.
Flink version is 1.15.0

1 Summary
image

2 Configs
image

3 Service Check
image

4 Quicklink
image

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by kevinw66** [comment]
Can we have custom configs like other components?
image
image

**Comment by kevinw66** [comment]
I can still see errors while running service_check
image

**Comment by smallyao** [comment]
Thanks for your review.
In current flink configs web， we can directly add/delete/update configuration in flink-conf template or log4j related textarea.


> Can we have custom configs like other components? image image

**Comment by smallyao** [comment]
Thanks for your review.
In current flink configs web， we can directly add/delete/update configuration in flink-conf template or log4j related textarea.


> Can we have custom configs like other components? image image

**Comment by smallyao** [comment]
> Can we have custom configs like other components? image image

Thanks for your review.
In current flink configs web， we can directly add/delete/update configuration in flink-conf template or log4j related textarea.

**Comment by smallyao** [comment]
> I can still see errors while running service_check image

Fixed, thanks @kevinw66

**Comment by kevinw66** [comment]
+1 LGTM, @guyuqi Could you please take a look, thanks!

**Comment by guyuqi** [comment]
Verified on the local host enabling Kerberos, +1

**Comment by guyuqi** [comment]
Merged, thanks @smallyao

**Pull request merged**
