### PR TITLE
BIGTOP-2260. Fix CI url link in REAME

### PR DESCRIPTION
**Pull request by AkihiroSuda**
This fix is very trivial, please let me know if I have to open JIRA.

### CODE REVIEW

**Comment by c0s** [comment]
It is very trivial, yet it is a good catch! Could you please open a ticket for this so we can commit it? All changes are going though the JIRAs in the project. Thanks!

**Comment by AkihiroSuda** [comment]
@c0s Thanks, opened JIRA: https://issues.apache.org/jira/browse/BIGTOP-2260

**Comment by c0s** [comment]
I have commit this, so please feel free to close the PR.

**Comment by AkihiroSuda** [comment]
@c0s Thank you!

**Pull request closed without merging**
