### PR TITLE
BIGTOP-3925: Ranger  support

### PR DESCRIPTION
**Pull request by JiaLiangC**
### Description of PR
ranger packaging is missing configuration setup, and the RPM name prefix has not been set.

https://issues.apache.org/jira/browse/BIGTOP-3925
### How was this patch tested?
manual test
image
image

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by guyuqi** [comment]
@JiaLiangC 
Thanks for working on it.
Let me verify it on Fedora-36/Rockylinux-8 (x86/Arm64).

By the way,  the title of the PR is "Ranger support".
Would you like to add Debian support for Ranger  as well?

**Comment by JiaLiangC** [comment]
@guyuqi 
OK, there are three PRs related to Ranger support in Bigtop:

BIGTOP-3925 mainly addresses the issue of Ranger RPM packaging and includes a patch to fix the problem of HBase not starting after integrating with Ranger.
BIGTOP-3923 mainly addresses the missing dependency issue when running the Ranger command "java -cp '/usr/bigtop/current/ranger-usersync/lib/*' org.apache.ranger.credentialapi.buildks create ranger.usersync.policymgr.password -value [PROTECTED] -provider jceks://file/usr/bigtop/current/ranger-usersync/conf/ugsync.jceks".
BIGTOP-3910 adds Bigtop-select support for Ranger.
In addition, patch0 in BIGTOP-3925 mainly addresses the issue of HBase not starting after integrating with Ranger due to class loading order. For more details and root cause analysis, please see https://issues.apache.org/jira/browse/RANGER-4201.

I will also add support for testing Ranger on Debian systems.

**Comment by guyuqi** [comment]
> @guyuqi OK, there are three PRs related to Ranger support in Bigtop:
> 
> [BIGTOP-3925](https://issues.apache.org/jira/browse/BIGTOP-3925) mainly addresses the issue of Ranger RPM packaging and includes a patch to fix the problem of HBase not starting after integrating with Ranger. [BIGTOP-3923](https://issues.apache.org/jira/browse/BIGTOP-3923) mainly addresses the missing dependency issue when running the Ranger command "java -cp '/usr/bigtop/current/ranger-usersync/lib/*' org.apache.ranger.credentialapi.buildks create ranger.usersync.policymgr.password -value [PROTECTED] -provider jceks://file/usr/bigtop/current/ranger-usersync/conf/ugsync.jceks". [BIGTOP-3910](https://issues.apache.org/jira/browse/BIGTOP-3910) adds Bigtop-select support for Ranger. In addition, patch0 in [BIGTOP-3925](https://issues.apache.org/jira/browse/BIGTOP-3925) mainly addresses the issue of HBase not starting after integrating with Ranger due to class loading order. For more details and root cause analysis, please see https://issues.apache.org/jira/browse/RANGER-4201.
> 
> I will also add support for testing Ranger on Debian systems.

Thanks for your elaboration. That's informative.
I'll first test this PR #1100 and #1099 together.

**Comment by JiaLiangC** [comment]
@guyuqi  Here we have fixed another issue with starting Kafka after integrating with Ranger due to missing packages. With this, the testing of Ranger integration with Hadoop YARN, HDFS, HBase, Hive, and Kafka is now complete. 
Please see the related issue for more details: https://issues.apache.org/jira/browse/RANGER-4228

**Comment by guyuqi** [comment]
Failed to run the ranger smoke tests on Fedora-36:
```
./docker-hadoop.sh -d --create 3 --image bigtop/puppet:3.2.0-fedora-36 \
--memory 16g --repo file:///bigtop-home/output --disable-gpg-check --enable-local-repo \ 
--stack bigtop-utils,ranger \
--smoke-tests ranger
```
Log:
```
> Task :bigtop-tests:smoke-tests:ranger:test FAILED

org.apache.bigtop.itest.ranger.TestRangerSmoke > testServiceDefs FAILED
    java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:6080/service/public/v2/api/servicedef
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.configuredInputStream(ResourceGroovyMethods.java:2218)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.newReader(ResourceGroovyMethods.java:2319)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:692)
        at org.codehaus.groovy.runtime.ResourceGroovyMethods.getText(ResourceGroovyMethods.java:660)
        at org.codehaus.groovy.runtime.dgm$1017.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.apache.bigtop.itest.ranger.TestRangerSmoke.testServiceDefs(TestRangerSimple.groovy:39)
```

Would you like help adjusting [tests file](https://github.com/apache/bigtop/blob/master/bigtop-tests/smoke-tests/ranger/TestRangerSimple.groovy) for Ranger-2.8 correspondingly? 
Thanks. @JiaLiangC

**Comment by JiaLiangC** [comment]
@guyuqi Sure, I can help adjust the tests file for Ranger

**Comment by JiaLiangC** [comment]
@guyuqi To run this test, do I need to merge this PR locally and compile and package all other components using 3.2.0-fedora-36 docker images? Then should I configure "-repo" to the output directory of the Bigtop project?

**Comment by guyuqi** [comment]
> @guyuqi To run this test, do I need to merge this PR locally and compile and package all other components using 3.2.0-fedora-36 docker images? Then should I configure "-repo" to the output directory of the Bigtop project?

Just re-build ranger and set up the yum-repo in your local environment in a container which is built from `bigtop/slaves:3.2.0-fedora-36` like:

`./gradlew ranger-clean ranger-pkg yum`

**Comment by guyuqi** [comment]
The comand line: 
```
docker run --rm -u jenkins -v `pwd`:/ws bigtop/slaves:3.2.0-fedora-36 bash -l -c 'cd /ws ; ./gradlew ranger-clean ranger-pkg yum'
```

**Comment by JiaLiangC** [comment]
> The comand line:
> 
> ```
> docker run --rm -u jenkins -v `pwd`:/ws --workdir /ws bigtop/slaves:3.2.0-fedora-36 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew ranger-clean ranger-pkg yum'
> ```

@guyuqi  Thank you very much for your patient explanation. I'll give it a try.

**Comment by JiaLiangC** [comment]
@guyuqi  It seems that I have passed the smoke test for Ranger. The testing command and the results are shown in the image below.
[root@gs-server-12223 docker]# bash docker-hadoop.sh -d --create 3 --image bigtop/puppet:3.2.0-fedora-36 --memory 16g --repo file:///home/jenkins/bigtop/output --disable-gpg-check --enable-local-repo --stack bigtop-utils,ranger --smoke-tests ranger

image

**Comment by guyuqi** [comment]
> @guyuqi It seems that I have passed the smoke test for Ranger. The testing command and the results are shown in the image below. [root@gs-server-12223 docker]# bash docker-hadoop.sh -d --create 3 --image bigtop/puppet:3.2.0-fedora-36 --memory 16g --repo file:///home/jenkins/bigtop/output --disable-gpg-check --enable-local-repo --stack bigtop-utils,ranger --smoke-tests ranger
> 
> image

Yes, it seems like I am having network issues with my local environment.
I verified this PR on my another node and the smoke tests were passed.
+1

**Comment by guyuqi** [comment]
Merged, thanks @JiaLiangC

**Pull request merged**
