### PR TITLE
BIGTOP-3786: Improve the build scripts to append suffix to the rpm package name

### PR DESCRIPTION
**Pull request by timyuer**
### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by timyuer** [comment]
Tested success by `. /etc/profile.d/bigtop.sh; ./gradlew zookeeper-clean zookeeper-pkg -PpkgSuffix -PparentDir=/usr/bigtop`.

**Comment by timyuer** [comment]
Tested success by `. /etc/profile.d/bigtop.sh ; ./gradlew bigtop-select-clean bigtop-select-pkg -PpkgSuffix` in Centos7(x86_64).

**Comment by timyuer** [comment]
Tested successful in Ambari.

**Comment by kevinw66** [comment]
Build success on RockyLinux 8 without suffix
```
. /etc/profile.d/bigtop.sh ; ./gradlew allclean zookeeper-pkg kafka-pkg flink-pkg hadoop-pkg hbase-pkg hive-pkg solr-pkg spark-pkg tez-pkg zeppelin-pkg
```

image

**Comment by timyuer** [comment]
When modifying spark, I added the `spark` rpm package to ensure the consistency of the format. All contents except components are stored in the `spark` RPM package. The `spark-core` only contains `README.md` and sets the dependency relationship to `spark-master -> spark-core -> spark -> hadoop-yarn`.  
Is there any problem with that?

**Comment by kevinw66** [comment]
Build success on RockyLinux8 with suffix
```
. /etc/profile.d/bigtop.sh ; ./gradlew allclean spark-pkg zookeeper-pkg kafka-pkg flink-pkg hadoop-pkg hbase-pkg hive-pkg solr-pkg tez-pkg zeppelin-pkg -PpkgSuffix
```
image

**Comment by guyuqi** [comment]
@timyuer 
Would any other commits be added to this PR？

**Comment by timyuer** [comment]
> @timyuer Would any other commits be added to this PR？

No.

**Comment by guyuqi** [comment]
> > @timyuer Would any other commits be added to this PR？
> 
> No.


Thanks. LGTM +1.

As talked with @kevinw66 ,  I'd like merge this to master.
Because `bigtop-select` is just only used for Ambari-2.8 and it only supports RPMs in Bigtop, I would disable the component [bigtop-select](https://github.com/apache/bigtop/blob/master/bigtop.bom#L261) in Bigtop-3.2 (Branch-3.2).  
Ambari guys could fetch our Bigtop-3.2 release source code and enbale `bigtop-select` component  by themselves.

**Pull request merged**
