### PR TITLE
BIGTOP-3348. Fix Hive test failures caused by NoSuchMethodError of ApplicationId.fromString.

### PR DESCRIPTION
**Pull request by iwasakims**

### CODE REVIEW

**Comment by sekikn** [comment]
I've already merged #633, so would you rename the new patch in this PR to a name starting with "patch4" to clarify their application order (though it doesn't matter which one is applied first in this case)?

**Comment by iwasakims** [comment]
@sekikn Sure. I renamed the added file.

**Comment by iwasakims** [comment]
`./docker-hadoop.sh -c 3 --smoke-tests` passed with the following configuration.
```
docker:
        memory_limit: "12g"
        image: "bigtop/puppet:trunk-centos-7"
distro: centos
components: [hdfs, yarn, mapreduce, tez, hive]
enable_local_repo: true
smoke_test_components: [hive]
```

**Comment by evans-ye** [comment]
+1. Thanks!

**Comment by iwasakims** [comment]
Thanks, @evans-ye.

**Pull request merged**
