### PR TITLE
BIGTOP-3920. Upgrade Hadoop to 3.3.5.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3920

* bumped the version and reset the release number.
* removed 2 patches already contained in Hadoop 3.3.5.

ran smoke-tests of hdfs,yarn,mapreduce on Rocky Linux 8 (x86_64 and aarch64).

While this breaks building HBase and Hive, I will address the issue in follow-up JIRAs ([BIGTOP-3926](https://issues.apache.org/jira/browse/BIGTOP-3926) and [BIGTOP-3927](https://issues.apache.org/jira/browse/BIGTOP-3927)).

### CODE REVIEW

**Comment by guyuqi** [comment]
Thanks for working on it.  Let me give it a shot on Arm platform, thanks.

**Comment by guyuqi** [comment]
It failed to build Hbase (running `Hadoop`, `Hive `smoke tests ) when I applied PR #1101, #1102 and #1103 on Ubuntu-22.04 (x86_64/Arm64).
```
[INFO] --- exec-maven-plugin:1.6.0:exec (check-jar-contents-for-stuff-with-hadoop) @ hbase-shaded-with-hadoop-check-invariants ---
[ERROR] Found artifact with unexpected contents: '/ws/bigtop/output/hbase/hbase-2.4.13/hbase-shaded/hbase-shaded-client/target/hbase-shaded-client-2.4.13.jar'
.........
....
    com/sun/xml/txw2/output/XMLWriter.class
    com/sun/xml/txw2/output/XmlSerializer.class
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
...
..
.
[INFO] Apache HBase - Assembly ............................ SUCCESS [ 36.068 s]
[INFO] Apache HBase - Shaded - Testing Util ............... SUCCESS [ 51.800 s]
[INFO] Apache HBase - Shaded - Testing Util Tester ........ SUCCESS [  3.054 s]
[INFO] Apache HBase Shaded Packaging Invariants ........... SUCCESS [  2.608 s]
[INFO] Apache HBase Shaded Packaging Invariants (with Hadoop bundled) FAILURE [  1.547 s]
[INFO] Apache HBase - Archetypes .......................... SKIPPED
[INFO] Apache HBase - Exemplar for hbase-client archetype . SKIPPED
[INFO] Apache HBase - Exemplar for hbase-shaded-client archetype SKIPPED
[INFO] Apache HBase - Archetype builder ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:48 min
[INFO] Finished at: 2023-04-17T08:23:28Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec 
(check-jar-contents-for-stuff-with-hadoop) on project hbase-shaded-with-hadoop-check-invariants: 
Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

**Comment by iwasakims** [comment]
@guyuqi Are you ok to move this forward for the ease of reviewers of BIGTOP-3927 and BIGTOP-3929? BIGTOP-3930 should be separately addressed since the issue is not related to upgrading Hadoop and other products is affected.

**Comment by sekikn** [comment]
+1, tested on master with CentOS 7 and Ubuntu 20.04 using the following commands:

```
$ ./docker-hadoop.sh -d -C config_centos-7.yaml -L -k hdfs,yarn,mapreduce -s hdfs,yarn,mapreduce -c 3
```

```
$ ./docker-hadoop.sh -d -C config_ubuntu-20.04.yaml -L -k hdfs,yarn,mapreduce -s hdfs,yarn,mapreduce -c 3
```

and on branch-3.2 with Ubuntu 22.04 using the following one:

```
$ ./docker-hadoop.sh -d -C config_ubuntu-22.04.yaml -F docker-compose-cgroupv2.yml -L -k hdfs,yarn,mapreduce -s hdfs,yarn,mapreduce -c 3
```

I've only tested it on x86_64, but let's address if there's any error on other platforms. @guyuqi

**Comment by sekikn** [comment]
Merged into master and branch-3.2.

**Pull request merged**
