### PR TITLE
BIGTOP-2802. Some packages don't create necessary groups on debian-based system if the users correspond to them already exist

### PR DESCRIPTION
**Pull request by sekikn**

### CODE REVIEW

**Comment by sekikn** [comment]
Thanks! In addition to that, this fix also covers the case that a user already exists but its group is not created. In such a case, the original scripts don't create the groups, so the final state differs from the normal case. It's undesirable.

**Comment by oflebbe** [comment]
adduser on centos-7 does not have that flag '--ingroup'. Sadly.

**Comment by oflebbe** [comment]
IMHO ambari should be fixed. Why does it create broken user/group configs?

**Comment by rvs** [comment]
@sekikn I think the patch looks reasonable, @oflebbe did you mistype? This patch only applies on Debian side -- so if you know any caveats of using --ingroup on that platform -- please let us know. Otherwise -- I guess the patch can go in?

**Comment by oflebbe** [comment]
Oh yes, it was too late that night. The patch looks very good for debian. Please apply

**Comment by sekikn** [comment]
@c0s @oflebbe @rvs thanks for the reviews! I'm going to check this in.

**Pull request closed without merging**
