### PR TITLE
BIGTOP-3556: Minimum chnages for upgrading Bigtop-ambari-mpack aligne…

### PR DESCRIPTION
**Pull request by guyuqi**
1. minimum changes for bumping Mpack version.
2. upgrade repo to 1.5.0 release.

### CODE REVIEW

**Comment by guyuqi** [comment]
The PR is just to bumping Mpack version algined to Ambari 2.7.5 and update packages repo to 1.5.0 release.

The next is to update HDFS, YARN ,zookeeper service in this mapck. I'm working on it.

**Review by iwasakims — APPROVED** [review]
+1. Thanks, @guyuqi!

**Comment by andrewvaliev** [comment]
good afternoon, please tell me. We build bigtop hadoop from the master branch, do build and deploy with puppet, at the end of the installation hadoop 3 rises, and ambari offers version 2.x of hadoop, how to make ambari friends with existing installed services? Or you don't need to do sudo puppet apply -d --modulepath = "bigtop-deploy / puppet / modules: / etc / puppet / modules: / opt / puppetlabs / puppet / modules" bigtop-deploy / puppet / manifests --confdir = / etc / puppet /? Thanks

**Comment by guyuqi** [comment]
@andrewvaliev 
Thanks for your interest.

This PR is to minimum changes for bumping Mpack version and upgrade repo to Bigtop 1.5.0 release.
In 1.5.0 release, we just support Hadoop-2.10, and haven't supported Hadoop-3.x yet.
So the Mpack based on 1.5.0 release also do not support Hadoop-3.x .

But in the upcoming Bigtop-3.0 release, Bigtop would support Hadoop-3.x. and I'll start to work
on upgrading Hadoop-3.0 services in this Mpack.  Or if you're interested in Bigtop-Mapck, welcome to contribution. :) Thanks.

**Pull request merged**
