### PR TITLE
[Puppet] Make GPG check for repos a configuration and default to true

### PR DESCRIPTION
**Pull request by evans-ye**
Tested via:
```
./docker-hadoop.sh -d -C config_debian-9.yaml -c 3
./docker-hadoop.sh -d -C config_centos-7.yaml -c 3
```
Also changes the value of gpg_check to true/false and see whether the change reflected to the deployed env.

### CODE REVIEW

**Comment by elukey** [comment]
I am not super familiar with the puppet code but it looks good! Any downside or things that you don't particularly like about the solution?

**Comment by iwasakims** [comment]
@evans-ye, I got following error
```
E: Package 'gpg' has no installation candidate
local apt = false ; NOT Enabling local apt. Packages will be pulled from remote...
Error: Evaluation Error: Error while evaluating a Function Call, Could not find data item bigtop::bigtop_repo_uri in any Hiera data file and no default supplied at /bigtop-home/bigtop-deploy/puppet/manifests/bigtop_repo.pp:55:35 on node e1e950fca651.bigtop.apache.org
Error: Evaluation Error: Error while evaluating a Function Call, Could not find data item bigtop::bigtop_repo_uri in any Hiera data file and no default supplied at /bigtop-home/bigtop-deploy/puppet/manifests/bigtop_repo.pp:55:35 on node e1e950fca651.bigtop.apache.org
```

on docker provisioning with the configuration like
```
docker:
        memory_limit: "12g"
        image:  "bigtop/puppet:trunk-ubuntu-16.04"
distro: debian
components: [hdfs, yarn, mapreduce]
enable_local_repo: false
smoke_test_components: [hdfs, yarn, mapreduce]
```

**Comment by sekikn** [comment]
@evans-ye As @iwasakims pointed out, `gnupg` instead of `gpg` in setup-env-debian.sh seems to work on Ubuntu 16.04 in addition to Debian 9. Otherwise LGTM!

**Comment by evans-ye** [comment]
Sorry. My bad. Let me work on a fix. Thanks for discovering the bug and the suggestion @iwasakims @sekikn .

**Comment by sekikn** [comment]
@evans-ye I think it's one of the blockers for the 1.5.0 release. May I submit a revised PR to proceed?

**Comment by evans-ye** [comment]
Oh. Sure no problem. Sorry to block the release. If you have time you can just proceed and refine it. Or if you need help I can find time in next week to refine it. Thanks!!!

**Comment by sekikn** [comment]
Thanks Evans, will merge #649 and close this PR :)

**Comment by evans-ye** [comment]
NP. Thanks for picking that up.

**Pull request closed without merging**
