### PR TITLE
BIGTOP-4043: Remove Ambari Dependency bigtop-select from Codebase

### PR DESCRIPTION
**Pull request by JiaLiangC**
### Description of PR

Remove the bigtop-select Ambari Dependency from Codebase

The bigtop-select was mainly introduced as a stack tool for Ambari  Mpack in this PR: 

https://github.com/apache/bigtop/pull/1030

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by JiaLiangC** [comment]
@iwasakims @sekikn Could you help review the pr?

**Comment by iwasakims** [comment]
@JiaLiangC While we dropped Ambari packaging based on the discussion in [BIGTOP-3909](https://issues.apache.org/jira/browse/BIGTOP-3909), [Bigtop Mpack is still living in Ambari](https://github.com/apache/ambari/tree/trunk/ambari-server/src/main/resources/stacks/BIGTOP) after migration from Bigtop to Ambari. The bigtop-select is needed for the Mpack. You should raise `[DISCUSS]` thread in dev ML of both Ambari and Bigtop if you want to move them to Ambari then remove.

**Comment by JiaLiangC** [comment]
> @JiaLiangC While we dropped Ambari packaging based on the discussion in [BIGTOP-3909](https://issues.apache.org/jira/browse/BIGTOP-3909), [Bigtop Mpack is still living in Ambari](https://github.com/apache/ambari/tree/trunk/ambari-server/src/main/resources/stacks/BIGTOP) after migration from Bigtop to Ambari. The bigtop-select is needed for the Mpack. You should raise `[DISCUSS]` thread in dev ML of both Ambari and Bigtop if you want to move them to Ambari then remove.

thanks for you cl

**Comment by JiaLiangC** [comment]
@iwasakims 
Thank you for your explanation. I misunderstood the previous discussion and thought that both Ambari and mpack was no longer supported

**Pull request closed without merging**
