### PR TITLE
BIGTOP-3457. Add libhdfspp packages to hadoop.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3457

tested hadoop-pkg on CentOS 8.

```
$ rpm -qlp output/hadoop/x86_64/hadoop-libhdfspp-3.2.2-1.el8.x86_64.rpm
/usr/lib64/libhdfspp.so
/usr/lib64/libhdfspp.so.0.1.0

$ rpm -qlp output/hadoop/x86_64/hadoop-libhdfspp-devel-3.2.2-1.el8.x86_64.rpm
/usr/include/hdfspp
/usr/include/hdfspp/block_location.h
/usr/include/hdfspp/config_parser.h
/usr/include/hdfspp/content_summary.h
/usr/include/hdfspp/events.h
/usr/include/hdfspp/fsinfo.h
/usr/include/hdfspp/hdfs_ext.h
/usr/include/hdfspp/hdfspp.h
/usr/include/hdfspp/ioservice.h
/usr/include/hdfspp/locks.h
/usr/include/hdfspp/log.h
/usr/include/hdfspp/options.h
/usr/include/hdfspp/statinfo.h
/usr/include/hdfspp/status.h
/usr/include/hdfspp/uri.h
```

### CODE REVIEW

**Comment by elukey** [comment]
Built the patch for debian10, successful! Inspected with dpkg -c the new packages for libhdfspp, all good as far as I can see (tried also to install them on Docker).

**Comment by sekikn** [comment]
@iwasakims This PR seems to fail on CentOS 7. Would you take a look?

```
+ for library in libhdfs.so.0.0.0 libhdfspp.so.0.1.0
+ cp /home/vagrant/bigtop/build/hadoop/rpm/BUILD/hadoop-3.2.2-src/build/lib/native/libhdfspp.so.0.1.0 /home/vagrant/bigtop/build/hadoop/rpm/BUILDROOT/hadoop-3.2.2-1.el7.x86_64/usr/lib64/
cp: cannot stat '/home/vagrant/bigtop/build/hadoop/rpm/BUILD/hadoop-3.2.2-src/build/lib/native/libhdfspp.so.0.1.0': No such file or directory


RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.7V2ozY (%install)
    Bad exit status from /var/tmp/rpm-tmp.7V2ozY (%install)

> Task :hadoop-rpm FAILED
```

**Comment by iwasakims** [comment]
@elukey @sekikn Thanks for the feedback. I can reproduce the issue on my local CentOS 7. looking into the cause.

**Comment by iwasakims** [comment]
With HADOOP-17196, libhdfspp is skipped on CentOS 7. Since HADOOP-17196 is just addressing compiler warnings on Windows, adding patch to revert it on Bigtop side should cause no issue.

**Comment by sekikn** [comment]
+1, I succeeded in building hadoop with this PR on all distros we support. Thanks @iwasakims!

**Pull request merged**
