### PR TITLE
BIGTOP-3771. Fix failure of sqlline.py bundled with Phoenix.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3771 

```
# python3 /usr/lib/phoenix/bin/sqlline.py
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.phoenix.shaded.org.jline.reader.impl.completer.StringsCompleter.<init>([Lorg/apache/phoenix/shaded/org/jline/reader/Candidate;)V
        at sqlline.SqlLineOpts.setOptionCompleters(SqlLineOpts.java:160)
        at sqlline.Application.getCommandHandlers(Application.java:294)
        at sqlline.SqlLine$Config.<init>(SqlLine.java:1946)
        at sqlline.SqlLine.setAppConfig(SqlLine.java:1875)
        at sqlline.SqlLine.<init>(SqlLine.java:229)
        at sqlline.SqlLine.start(SqlLine.java:266)
        at sqlline.SqlLine.main(SqlLine.java:206)
```

### CODE REVIEW

**Comment by iwasakims** [comment]
The stack trace implies that [the constructor of StringsCompleter which is not exists in 3.9.0](https://www.javadoc.io/static/org.jline/jline-reader/3.12.1/org/jline/reader/impl/completer/StringsCompleter.html#StringsCompleter-org.jline.reader.Candidate...-) was called.

* https://www.javadoc.io/static/org.jline/jline-reader/3.9.0/org/jline/reader/impl/completer/StringsCompleter.html
* https://www.javadoc.io/static/org.jline/jline-reader/3.12.1/org/jline/reader/impl/completer/StringsCompleter.html

compile scope dependency on org.jline:jline:jar:3.9.0 is pulled from Hadoop (after YARN-8778).

```
$ mvn dependency:tree -DskipTests -Dhadoop.version=3.3.4 -Dhbase.version=2.4.13 -Dhbase.profile=2.4 | grep jline
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:provided
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:provided
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:provided
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:provided
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:provided
[INFO] |  |  \- org.jline:jline:jar:3.9.0:compile
[INFO] |  \- jline:jline:jar:0.9.94:compile
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:compile
[INFO] |  |  \- jline:jline:jar:0.9.94:compile
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:compile
[INFO] |  |  \- jline:jline:jar:0.9.94:compile
[INFO]    +- org.jline:jline-terminal:jar:3.12.1:runtime
[INFO]    +- org.jline:jline-reader:jar:3.12.1:runtime
[INFO]    +- org.jline:jline-terminal-jansi:jar:3.12.1:runtime
[INFO]    +- org.jline:jline-terminal-jna:jar:3.12.1:runtime
[INFO]    \- org.jline:jline-builtins:jar:3.12.1:runtime
[INFO]       \- org.jline:jline-style:jar:3.12.1:runtime
[INFO] |  |  \- jline:jline:jar:0.9.94:compile
[INFO] |  |  \- org.jline:jline:jar:3.9.0:provided
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:provided
[INFO] |  |  \- jline:jline:jar:0.9.94:provided
[INFO] |  |  |  |  \- org.jline:jline:jar:3.9.0:compile
[INFO] |  |  |  \- jline:jline:jar:0.9.94:compile
[INFO] |     +- org.jline:jline-terminal:jar:3.12.1:runtime
[INFO] |     +- org.jline:jline-reader:jar:3.12.1:runtime
[INFO] |     +- org.jline:jline-terminal-jansi:jar:3.12.1:runtime
[INFO] |     +- org.jline:jline-terminal-jna:jar:3.12.1:runtime
[INFO] |     \- org.jline:jline-builtins:jar:3.12.1:runtime
[INFO] |        \- org.jline:jline-style:jar:3.12.1:runtime
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:compile
[INFO] |  |  \- jline:jline:jar:0.9.94:compile
[INFO] |  |  |  \- org.jline:jline:jar:3.9.0:compile
[INFO] |  |  \- jline:jline:jar:0.9.94:compile
[INFO]    +- org.jline:jline-terminal:jar:3.12.1:runtime
[INFO]    +- org.jline:jline-reader:jar:3.12.1:runtime
[INFO]    +- org.jline:jline-terminal-jansi:jar:3.12.1:runtime
[INFO]    +- org.jline:jline-terminal-jna:jar:3.12.1:runtime
[INFO]    \- org.jline:jline-builtins:jar:3.12.1:runtime
[INFO]       \- org.jline:jline-style:jar:3.12.1:runtime
```

org.jline:jline is bundled jar. It contains duplicate classes of org.jline:jline-*:3.12.1 (which are transitive dependencies of sqlline).

**Comment by iwasakims** [comment]
manually tested on Rocky Linux 8 x86_64:

```
$ ./docker-hadoop.sh \
          --create 1 \
          --image bigtop/puppet:trunk-rockylinux-8 \
          --memory 16g \
          --repo file:///bigtop-home/output \
          --disable-gpg-check \
          --stack hdfs,yarn,mapreduce,hbase
$ ./docker-hadoop.sh --exec 1 /bin/bash
[root@3c8e98456fa2 /]# yum install -y phoenix python3
[root@3c8e98456fa2 /]# ln -s /usr/lib/phoenix/phoenix-server.jar /usr/lib/hbase/lib/phoenix-server.jar
[root@3c8e98456fa2 /]# systemctl restart hbase-master hbase-regionserver
[root@3c8e98456fa2 /]# python3 /usr/lib/phoenix/bin/psql.py /usr/share/doc/phoenix-5.1.2/examples/STOCK_SYMBOL.sql /usr/share/doc/phoenix-5.1.2/examples/STOCK_SYMBOL.csv
[root@3c8e98456fa2 /]# python3 /usr/lib/phoenix/bin/sqlline.py
...
0: jdbc:phoenix:> SELECT * FROM stock_symbol;
+--------+----------------------+
| SYMBOL |       COMPANY        |
+--------+----------------------+
| AAPL   | APPLE Inc.           |
| CRM    | SALESFORCE           |
| GOOG   | Google               |
| HOG    | Harlet-Davidson Inc. |
| HPQ    | Hewlett Packard      |
| INTC   | Intel                |
| MSFT   | Microsoft            |
| WAG    | Walgreens            |
| WMT    | Walmart              |
+--------+----------------------+
9 rows selected (0.052 seconds)
```

**Comment by iwasakims** [comment]
I refreshed the patch based on the review process of [PHOENIX-6766](https://issues.apache.org/jira/browse/PHOENIX-6766). Manual test passed as expected.

**Comment by guyuqi** [comment]
+1,  LGTM.

Tested it following your test procedures on my local Arm64 Rockylinux-8 against Hadoop-3.3.4:
```
[root@c8b0eb43e96e /]# arch
aarch64
```
```
[root@c8b0eb43e96e /]# python3 /usr/lib/phoenix/bin/psql.py /usr/share/doc/phoenix-5.1.2/examples/STOCK_SYMBOL.sql /usr/share/doc/phoenix-5.1.2/examples/STOCK_SYMBOL.csv
....
..
csv columns from database.
CSV Upsert complete. 9 rows upserted
Time: 0.034 sec(s)
```
```
[root@c8b0eb43e96e /]# python3 /usr/lib/phoenix/bin/sqlline.py
....
..
sqlline version 1.9.0
0: jdbc:phoenix:> SELECT * FROM stock_symbol;
+--------+----------------------+
| SYMBOL |       COMPANY        |
+--------+----------------------+
| AAPL   | APPLE Inc.           |
| CRM    | SALESFORCE           |
| GOOG   | Google               |
| HOG    | Harlet-Davidson Inc. |
| HPQ    | Hewlett Packard      |
| INTC   | Intel                |
| MSFT   | Microsoft            |
| WAG    | Walgreens            |
| WMT    | Walmart              |
+--------+----------------------+
9 rows selected (0.057 seconds)
0: jdbc:phoenix:>
```

**Comment by guyuqi** [comment]
Merged, thanks @iwasakims

**Pull request merged**
