### PR TITLE
BIGTOP-3475. Bump ZooKeeper to 3.4.14.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3475

* addressed changes made by [ZOOKEEPER-3021](https://issues.apache.org/jira/browse/ZOOKEEPER-3021).

### CODE REVIEW

**Comment by iwasakims** [comment]
packaging and smoke-tests worked on CentOS 8 on my local.

**Comment by guyuqi** [comment]
+1,
Verified it on Ubuntu 18.04 on x86/Arm64.

**Comment by iwasakims** [comment]
Thanks, @guyuqi. This seems to break build of hadoop-3.2.x due to similar reason reported in [BIGTOP-3473](https://issues.apache.org/jira/browse/BIGTOP-3473). I'm going to address this in https://github.com/apache/bigtop/pull/711.

**Comment by guyuqi** [comment]
ok, got it.

**Pull request merged**
