### PR TITLE
BIGTOP-3474. Bump Hadoop to 3.2.2.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3474

* removed the [HADOOP-16739](https://issues.apache.org/jira/browse/HADOOP-16739) patch included in 3.2.2.
* added patch reverting [HADOOP-16598](https://issues.apache.org/jira/browse/HADOOP-16598) for the same reason of [BIGTOP-3449](https://issues.apache.org/jira/browse/BIGTOP-3449).

### CODE REVIEW

**Comment by iwasakims** [comment]
I need to address the issue brought by https://github.com/apache/bigtop/pull/712.
```
[ERROR] Found artifact with unexpected contents: '/home/centos/srcs/bigtop/build/hadoop/rpm/BUILD/hadoop-3.2.2-src/hadoop-client-modules/hadoop-client-minicluster/target/hadoop-client-minicluster-3.2.2.jar'
    Please check the following and either correct the build or update
    the allowed list with reasoning.

    edu/
    edu/umd/
    edu/umd/cs/
    edu/umd/cs/findbugs/
    edu/umd/cs/findbugs/annotations/
    edu/umd/cs/findbugs/annotations/NonNull.class
    edu/umd/cs/findbugs/annotations/CheckForNull.class
    edu/umd/cs/findbugs/annotations/DefaultAnnotationForFields.class
    edu/umd/cs/findbugs/annotations/PossiblyNull.class
    edu/umd/cs/findbugs/annotations/OverrideMustInvoke.class
    edu/umd/cs/findbugs/annotations/DesireNoWarning.class
    edu/umd/cs/findbugs/annotations/DischargesObligation.class
    edu/umd/cs/findbugs/annotations/DefaultAnnotationForMethods.class
    edu/umd/cs/findbugs/annotations/CreatesObligation.class
    edu/umd/cs/findbugs/annotations/DefaultAnnotationForParameters.class
    edu/umd/cs/findbugs/annotations/ExpectWarning.class
    edu/umd/cs/findbugs/annotations/NoWarning.class
    edu/umd/cs/findbugs/annotations/ReturnValuesAreNonnullByDefault.class
    edu/umd/cs/findbugs/annotations/CleanupObligation.class
    edu/umd/cs/findbugs/annotations/SuppressWarnings.class
    edu/umd/cs/findbugs/annotations/CheckReturnValue.class
    edu/umd/cs/findbugs/annotations/DesireWarning.class
    edu/umd/cs/findbugs/annotations/SuppressFBWarnings.class
    edu/umd/cs/findbugs/annotations/When.class
    edu/umd/cs/findbugs/annotations/DefaultAnnotation.class
    edu/umd/cs/findbugs/annotations/UnknownNullness.class
    edu/umd/cs/findbugs/annotations/Priority.class
    edu/umd/cs/findbugs/annotations/Confidence.class
    edu/umd/cs/findbugs/annotations/Nullable.class
```

**Comment by iwasakims** [comment]
I added patch2-exclude-spotbugs-annotations.diff to fix the issue brought by zookeeper-3.4.14.

**Comment by guyuqi** [comment]
The smoke tests seems to failed in Ubuntu-18.04

**Comment by iwasakims** [comment]
> The smoke tests seems to failed in Ubuntu-18.04

Yes. We need to fix puppet manifests and smoke-tests as follow-up of [BIGTOP-3280](https://issues.apache.org/jira/browse/BIGTOP-3280). I'm addressing only packaging here. I filed [BIGTOP-3477](https://issues.apache.org/jira/browse/BIGTOP-3477) for puppet manifests.

**Comment by guyuqi** [comment]
ok, this PR is for packaging support.  
+1

**Comment by guyuqi** [comment]
Let me rebuild it on Deian-9 and fedora-31 first before merged it, thanks.

**Comment by guyuqi** [comment]
+1

**Comment by guyuqi** [comment]
merged.
Thanks, @iwasakims

**Pull request merged**
