### PR TITLE
Support openEuler's toolchain and docker images

### PR DESCRIPTION
**Pull request by MacChen01**
### Description of PR
The PR support the OpenEuler 22.03, include building puppet and slaves docker env for compile and smoke test etc.

### How was this patch tested?
I confirmed that some of components were successfully compiled on OpenEuler 22.03, including ZK, oozie, hive etc.

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (BIGTOP-3876)
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by guyuqi** [comment]
It seems this PR was based on `master`,  not on `openEuler-support`.

**Comment by MacChen01** [comment]
> It seems this PR was based on `master`, not on `openEuler-support`.

@guyuqi It changed from master to openEuler-support branch.

**Comment by MacChen01** [comment]
@guyuqi  This PR is ok, the test result like this:

image

image

**Comment by guyuqi** [comment]
LGTM，+1

**Comment by guyuqi** [comment]
Merged to branch `openEuler-support`.
Thanks @MacChen01

**Pull request merged**
