### PR TITLE
BIGTOP-2468: Add Juju hadoop-processing bundle

### PR DESCRIPTION
**Pull request by kwmonroe**
We split the original Juju enablement issue (BIGTOP-2435) into multiple components for ease of review.  This is the proposal to include the hadoop-processing bundle in ./bigtop-deploy/juju.

### CODE REVIEW

**Comment by c0s** [comment]
This commit seems to have conflict now #108 is committed

**Comment by c0s** [comment]
Also, please make the name of the PR matches the JIRA title exactly, otherwise the latter won't get updated

**Comment by kwmonroe** [comment]
Conflicts with #108 resolved

**Comment by johnsca** [comment]
Conflict resolved.  It was the addition of a couple of lines to `pom.xml` and `build.gradle` for the RAT fixes.  They were both added lines, but git didn't have quite enough common context to resolve it automatically.

**Comment by c0s** [comment]
Everything seems to be in order. +1

**Comment by johnsca** [comment]
Thanks for merging this as c04e3d4

**Comment by kwmonroe** [comment]
Thanks c0s and Cory!

**Pull request closed without merging**
