### PR TITLE
BIGTOP-3486. Fix version mismatch of Jetty between Hadoop and HBase.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3486

This sets Jetty version to the latest of 9.3.

### CODE REVIEW

**Comment by iwasakims** [comment]
Unit tests of Hadoop and HBase worked as expected with the patch applied.

hadoop::
```
mvn test -Dzookeeper.version=3.4.14 -Djetty.version=9.3.29.v20201019 -Dmaven.test.failure.ignore=true 
```

hbase::
```
mvn test -Phadoop-3.0 -Dhadoop-three.version=3.2.2 -Dslf4j.version=1.7.25 -Djetty.version=9.3.29.v20201019 -Dzookeeper.version=3.4.14 -Dsurefire.testFailureIgnore=true
```

**Comment by sekikn** [comment]
@iwasakims I tried to test this PR locally but it couldn't be applied as it is after merging #723. Would you rebase this?

**Comment by iwasakims** [comment]
I rebased this. Thanks, @sekikn.

**Comment by sekikn** [comment]
+1, building HBase with this PR succeeded on CentOS 7, Debian 10 and Ubuntu 18.04. Its smoke test also passed on CentOS 7. Thanks @iwasakims!

**Pull request merged**
