### PR TITLE
BIGTOP-3220: Add deb build for Elasticsearch

### PR DESCRIPTION
**Pull request by JunHe77**
Change-Id: Ia08ae5d6f00799469c8ee44ad73d5440a00e329e
Signed-off-by: Jun He <jun.he@linaro.org>

### CODE REVIEW

**Comment by evans-ye** [comment]
Nice! Let me look into this.

**Comment by JunHe77** [comment]
Hi, @evans-ye , any thought on this?

**Comment by evans-ye** [comment]
@JunHe77 sorry for the super late reply. The patch looks good however I'm not familiar w/ elasticsearch.
I've fired up a CI testing build:
https://ci.bigtop.apache.org/view/Test/job/Build-Deploy-Smoke-Test-Pull-Request-Single-Distro/10/console

Can you also give it a look and tell me whether that's a tool you can leverage for testing?

**Comment by JunHe77** [comment]
Hi, @evans-ye , I had a quick look at the jenkins job. Seems it has some problem in the BUILD script.(see https://ci.bigtop.apache.org/view/Test/job/Build-Deploy-Smoke-Test-Pull-Request-All-Distros/8/OS=centos-7-x86_64-deploy/console)
`/tmp/jenkins349940921246219538.sh: line 3: syntax error near unexpected token `else'`
I'll try to see if I can fix that job configuration later.

Following is the output of my local build and deployment:
`Notice: /Stage[main]/Bigtop_repo/Exec[bigtop-apt-update]/returns: executed successfully
Notice: /Stage[main]/Bigtop_repo/Exec[bigtop-apt-update]/returns: executed successfully
Notice: /Stage[main]/Bigtop_repo/Exec[bigtop-apt-update]/returns: executed successfully
Notice: /Stage[main]/Elasticsearch::Server/Package[elasticsearch]/ensure: ensure changed 'purged' to 'latest'
Notice: /Stage[main]/Elasticsearch::Server/File[/etc/elasticsearch/conf/elasticsearch.yml]/content: content changed '{md5}31655f8d9bce94581724510ebc90ed75' to '{md5}16ed44f2c1eb07c74f3c09b29631e173'
Notice: /Stage[main]/Elasticsearch::Server/Package[elasticsearch]/ensure: ensure changed 'purged' to 'latest'
Notice: /Stage[main]/Elasticsearch::Server/File[/etc/elasticsearch/conf/elasticsearch.yml]/content: content changed '{md5}31655f8d9bce94581724510ebc90ed75' to '{md5}4555771ae9398b9db59a48959c91df6d'
Notice: /Stage[main]/Elasticsearch::Server/Package[elasticsearch]/ensure: ensure changed 'purged' to 'latest'
Notice: /Stage[main]/Elasticsearch::Server/File[/etc/elasticsearch/conf/elasticsearch.yml]/content: content changed '{md5}31655f8d9bce94581724510ebc90ed75' to '{md5}3537d927ab37155b82325b68442a006b'
Notice: /Stage[main]/Jdk/Package[jdk]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Jdk/Package[jdk]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Jdk/Package[jdk]/ensure: ensure changed 'purged' to 'present'
Notice: /Stage[main]/Elasticsearch::Server/Service[elasticsearch]/ensure: ensure changed 'stopped' to 'running'
Notice: Finished catalog run in 96.82 seconds
Notice: /Stage[main]/Elasticsearch::Server/Service[elasticsearch]/ensure: ensure changed 'stopped' to 'running'
Notice: Finished catalog run in 98.49 seconds
Notice: /Stage[main]/Elasticsearch::Server/Service[elasticsearch]/ensure: ensure changed 'stopped' to 'running'
Notice: Finished catalog run in 99.84 seconds
linux@x86-hp:~/junhe/bigtop/provisioner/docker$ curl -XGET 'http://172.17.0.2:9200/_cluster/state?pretty'
{
  "cluster_name" : "bigtop-es",
  "version" : 3,
  "state_uuid" : "nOsvKCTkRfG_0Uom3QX2gw",
  "master_node" : "9vK6sByvSiWW4z_U4kZv_A",
  "blocks" : { },
  "nodes" : {
    "9vK6sByvSiWW4z_U4kZv_A" : {
      "name" : "c661bec49d04",
      "ephemeral_id" : "e5r4AGyASfuzFKFV-vkA_g",
      "transport_address" : "172.17.0.4:9300",
      "attributes" : { }
    },
    "FUz1jpO5SvW-eXgq4hnPkw" : {
      "name" : "7869948d591f",
      "ephemeral_id" : "88_eD_keQsavl89ofuKQdg",
      "transport_address" : "172.17.0.2:9300",
      "attributes" : { }
    },
    "uxSwLVCRRe6wZjotiIPQ0A" : {
      "name" : "661877af45b0",
      "ephemeral_id" : "-7sxosjwRW2nzG7or_baWA",
      "transport_address" : "172.17.0.3:9300",
      "attributes" : { }
    }
  },
  "metadata" : {
    "cluster_uuid" : "0dWKAeh1RjeJv14LRELo9g",
    "templates" : { },
    "indices" : { },
    "index-graveyard" : {
      "tombstones" : [ ]
    }
  },
  "routing_table" : {
    "indices" : { }
  },
  "routing_nodes" : {
    "unassigned" : [ ],
    "nodes" : {
      "uxSwLVCRRe6wZjotiIPQ0A" : [ ],
      "9vK6sByvSiWW4z_U4kZv_A" : [ ],
      "FUz1jpO5SvW-eXgq4hnPkw" : [ ]
    }
  }
}`

**Comment by evans-ye** [comment]
Sorry. My bad. I've fixed it.

**Comment by evans-ye** [comment]
+1. I found the CI still has some bug and resource issue. However the build seems OK across different platform. Thanks for the patch @JunHe77 .

**Comment by JunHe77** [comment]
@evans-ye , added smoke tests for Elasticsearch. Pls review.

**Comment by JunHe77** [comment]
@evans-ye , verified in https://ci.bigtop.apache.org/job/Build-Deploy-Smoke-Test-Pull-Request-All-Distros/19/

**Comment by evans-ye** [comment]
Sure. Great work & thanks! Please go ahead and merge it!

**Comment by evans-ye** [comment]
BTW you can actually separate the Puppet and Smoke test into different JIRA and make it 3 commits. I should reply to you earlier however I was too busy on my paid work. Thanks anyway for making a complete feature set of adding a new component.

**Pull request merged**
