### PR TITLE
BIGTOP-3727: Add HBase support for Bigtop 3.1.0 Mpack

### PR DESCRIPTION
**Pull request by yzydhf**
### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by guyuqi** [comment]
Phoenix query server failed to start:

```
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/HBASE/package/scripts/phoenix_queryserver.py", line 91, in <module>
    PhoenixQueryServer().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/HBASE/package/scripts/phoenix_queryserver.py", line 48, in start
    phoenix_service('start')
  File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/HBASE/package/scripts/phoenix_service.py", line 42, in phoenix_service
    environment=env)
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
    returns=self.resource.returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/usr/bgtp/current/phoenix-server/bin/queryserver.py start' returned 127. -bash: /usr/bgtp/current/phoenix-server/bin/queryserver.py: No such file or directory
```

**Comment by yzydhf** [comment]
> Phoenix query server failed to start:
> 
> ```
> Traceback (most recent call last):
>   File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/HBASE/package/scripts/phoenix_queryserver.py", line 91, in <module>
>     PhoenixQueryServer().execute()
>   File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
>     method(env)
>   File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/HBASE/package/scripts/phoenix_queryserver.py", line 48, in start
>     phoenix_service('start')
>   File "/var/lib/ambari-agent/cache/stacks/BGTP/1.0/services/HBASE/package/scripts/phoenix_service.py", line 42, in phoenix_service
>     environment=env)
>   File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
>     self.env.run()
>   File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
>     self.run_action(resource, action)
>   File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
>     provider_action()
>   File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
>     returns=self.resource.returns)
>   File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
>     result = function(command, **kwargs)
>   File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
>     tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
>   File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
>     result = _call(command, **kwargs_copy)
>   File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
>     raise ExecutionFailed(err_msg, code, out, err)
> resource_management.core.exceptions.ExecutionFailed: Execution of '/usr/bgtp/current/phoenix-server/bin/queryserver.py start' returned 127. -bash: /usr/bgtp/current/phoenix-server/bin/queryserver.py: No such file or directory
> ```

Fixed

**Comment by guyuqi** [comment]
May I ask why did you remove phoenix here?

**Comment by yzydhf** [comment]
> May I ask why did you remove phoenix here?

Phoenix is another service, we shouldn't include phoenix here, it'll be added in a separate PR

**Comment by guyuqi** [comment]
HBase has been bumped to 2.4.13. Let me rebuild and deploy 2.4.13 with this PR before merging it, thanks.

**Review by guyuqi — APPROVED** [review]
+1.
Test Hbase-2.4.13 deployment  with Hadoop-3.3.4 (https://github.com/apache/bigtop/pull/964) for both x86_64 and Arm64.

**Comment by guyuqi** [comment]
Merged, thanks @yzydhf

**Pull request merged**
