### PR TITLE
BIGTOP-3485. Bump Solr to v8.7.0.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3485

* Solr 8.7.0 contains SOLR-14663.
* solr-uima was removed by SOLR-11694.
* logging library was migrated.

### CODE REVIEW

**Comment by iwasakims** [comment]
Packaging and Puppet manifests worked on CentOS 8.

```
$ ./gradlew solr-clean solr-pkg repo
$ cd provisioner/docker
$ ./docker-hadoop.sh --create 1 --image bigtop/puppet:trunk-centos-8 --memory 16g --repo file:///bigtop-home/output --disable-gpg-check --stack zookeeper,hdfs,solrcloud
```

**Comment by iwasakims** [comment]
I got error on the smoke-tests. I'm looking into the cause.
```
> Task :bigtop-tests:smoke-tests:solr:test FAILED

org.apache.bigtop.itest.solr.smoke.TestIndexing > classMethod FAILED
    java.io.IOException: Server returned HTTP response code: 400 for URL: http://localhost:8983/solr/smoke/update/json?stream.body=[{"id":"doc1","name":"first+test+document"},{"id":"doc2","name":"second+test+document"}]&commit=true&wt=json
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.http.HttpURLConnection$getInputStream.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)
        at org.apache.bigtop.itest.solr.smoke.SolrTestBase.doReq(SolrTestBase.groovy:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1491)
        at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.callStatic(StaticMetaClassSite.java:64)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:208)
        at org.apache.bigtop.itest.solr.smoke.TestIndexing.before(TestIndexing.groovy:30)
```

**Comment by iwasakims** [comment]
`-Dlog4j.configuration=file:///etc/solr/conf/log4j.properties` must be updated

```
ERROR StatusLogger Unable to access file:///etc/solr/conf/log4j.properties
 java.io.FileNotFoundException: /etc/solr/conf/log4j.properties (No such file or directory)
```

**Comment by iwasakims** [comment]
got another error. https://github.com/apache/lucene-solr/pull/2304/files says we need `SOLR_OPTS=-XX:-UseLargePages`.
```
OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
```

**Comment by iwasakims** [comment]
```
# curl -G --data 'stream.body=[{"id":"doc1","name":"first+test+document"},{"id":"doc2","name":"second+test+document"}]&commit=true&wt=json' http://localhost:8983/solr/smoke/update/json
{
  "error":{
    "metadata":[
      "error-class","org.apache.solr.common.SolrException",
      "root-error-class","org.apache.solr.common.SolrException"],
    "msg":"Stream Body is disabled. See http://lucene.apache.org/solr/guide/requestdispatcher-in-solrconfig.html for help",
    "code":400}}
```

**Comment by iwasakims** [comment]
https://solr.apache.org/guide/8_8/requestdispatcher-in-solrconfig.html describes the way to update the required configuration.
```
# curl http://localhost:8983/solr/smoke/config -H 'Content-type:application/json' -d '{"set-property": {"requestDispatcher.requestParsers.enableRemoteStreaming": true}, "set-property": {"requestDispatcher.requestParsers.enableStreamBody": true}}'
{
  "responseHeader":{
    "status":0,
    "QTime":323},
  "WARNING":"This response format is experimental.  It is likely to change in the future."}

# curl -G --data 'stream.body=[{"id":"doc1","name":"first+test+document"},{"id":"doc2","name":"second+test+document"}]' --data 'commit=true' --data 'wt=json' http://localhost:8983/solr/smoke/update/json
{
  "responseHeader":{
    "rf":1,
    "status":0,
    "QTime":242}}
```

**Comment by iwasakims** [comment]
Smoke test of Solr passed.
```
$ ./docker-hadoop.sh --create 1 --image bigtop/puppet:trunk-centos-8 --memory 16g --repo file:///bigtop-home/output --disable-gpg-check --stack zookeeper,hdfs,solrcloud --smoke-tests solr
...(snip)
Now testing...
:bigtop-tests:smoke-tests:solr:test (Thread[Execution worker for ':' Thread 4,5,main]) completed. Took 8.27 secs.

BUILD SUCCESSFUL in 55s
35 actionable tasks: 7 executed, 28 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```

**Comment by iwasakims** [comment]
The smoke-tests passed on Ubuntu 18.04 too.
```
$ ./docker-hadoop.sh --create 1 --image bigtop/puppet:trunk-ubuntu-18.04 --memory 16g --repo file:///bigtop-home/output/apt --disable-gpg-check --stack zookeeper,hdfs,solrcloud --smoke-tests solr
...
:bigtop-tests:smoke-tests:solr:test (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 8.759 secs.

BUILD SUCCESSFUL in 54s
35 actionable tasks: 9 executed, 26 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```

**Comment by JunHe77** [comment]
Thanks, @iwasakims . I've verified this PR with ubuntu-18.04 on Arm. There are still some references of solr-uima in bigtop-tests/test-artifacts/package/src/main/resources/{apt,yum,zypper}/solr*.xml. It would be good to also remove these references.

And pls squash these commits so it could be one record in master. Thanks.

**Comment by iwasakims** [comment]
Thanks, @JunHe77. I removed the references from packaging test resources. While the resources (of all products) are not updated at all for years, I left other part as is. I will file a JIRA issue to update or remove those ignored test resources. I prefer removing to updating because manually maintaining list of all files of all packages does not make sense at all.

**Comment by iwasakims** [comment]
> And pls squash these commits so it could be one record in master. Thanks.

Yeah, I will do it by putting "Squash and merge" button of GitHub. (I usually do it when I review and merge PRs. It is the only allowed option on Hadoop development, FWIW. Other buttons are disabled by infra settings.)

**Comment by sekikn** [comment]
+1, also tested on Fedora 33. Thanks @iwasakims!

**Pull request merged**
