### PR TITLE
BIGTOP-2119: Bump Mahout version to 0.11.1

### PR DESCRIPTION
**Pull request by andrewmusselman**
Updated mahout version in bigtop.bom, built mahout-pkg, installed .deb, and ran a recommender job as well as checked the spark-shell works.

### CODE REVIEW

**Comment by c0s** [comment]
Hey Andrew, thanks! What about some of the missing files in the package you've mentioned on the dev@ or JIRA? Is this issue gone away somehow?

**Comment by andrewmusselman** [comment]
All cleared up, those were just not in 0.11.0.

**Comment by c0s** [comment]
Ah, makes sense. The patch looks good to me. 
+1 and I will run the build as well before pushing this into the master. Thanks!

**Comment by andrewmusselman** [comment]
Thank you!

**Comment by c0s** [comment]
Unfortunately, the rpm build failed
  http://ci.bigtop.apache.org/view/Packages/job/Bigtop-trunk-packages-manual-component-test/BUILD_ENVIRONMENTS=centos-7,label=docker-slave/6/console

**Comment by andrewmusselman** [comment]
Will take a look later tonight; that's weird.

**Comment by andrewmusselman** [comment]
I had a successful local build via:

`$ sudo docker run --rm -v `pwd`:/ws --workdir /ws bigtop/slaves:trunk-centos-7 bash -l -c './gradlew --stacktrace mahout-clean mahout-rpm'`

What would we look at next?

**Comment by andrewmusselman** [comment]
I can reproduce the error with mahout 0.11.1 and do not get the error with 0.11.0 so this does look like a regression.

**Comment by c0s** [comment]
The reason for the error is in the commit 
  347c2f2ec61f6a83e06c00c19d069acaf3a938b7
README.txt has been renamed to README.md

**Comment by andrewmusselman** [comment]
Good catch; strange it's not a problem with the deb build though.  I'll fix it.

**Comment by c0s** [comment]
The deb build is using logic encoded in install_mahout.sh - and that works. We can improve this separately (hint: open a JIRA for that ;)

**Comment by c0s** [comment]
Looks like bigtop CI is busy with nightly build, but I have kicked off mahout build here
  http://ci.bigtop.apache.org/job/Bigtop-trunk-packages-manual-component-test/BUILD_ENVIRONMENTS=centos-7,label=docker-slave/
with the change in the file name. If this works fine - we should be good to go.

**Comment by andrewmusselman** [comment]
Alright, adding the .md version to the SPEC for now.

**Comment by andrewmusselman** [comment]
Builds correctly locally via `$ sudo docker run --rm -v `pwd`:/ws --workdir /ws bigtop/slaves:trunk-centos-7 bash -l -c './gradlew --stacktrace mahout-clean mahout-rpm'`

**Comment by c0s** [comment]
This could be closed as the commit is pushed to the upstream

**Comment by andrewmusselman** [comment]
Closing

**Pull request closed without merging**
