### PR TITLE
BIGTOP-3624: Bump alluxio's log4j dependencies to 2.17.0

### PR DESCRIPTION
**Pull request by elukey**

### CODE REVIEW

**Comment by elukey** [comment]
Testing building + smoke tests, will report once done.

**Comment by elukey** [comment]
The package built fine, but as far as I can see inside the .deb there is no trace of log4j jars..

**Review by iwasakims — APPROVED** [review]
LGTM. I ran smoke-tests on CentOS 8 x86_64.

**Comment by iwasakims** [comment]
I merged this to master and branch-3.0. Thanks, @elukey.

**Pull request merged**
