### PR TITLE
BIGTOP-2477: Add Juju charm for spark component

### PR DESCRIPTION
**Pull request by johnsca**
This is to add a Juju charm for the Apache Spark component, with an optional relation to the Apache Hadoop component.

### CODE REVIEW

**Comment by petevg** [comment]
When I run bundletester on this charm, on AWS, I get a failure during 02-smoke-test.py, and the sparkscale machines are blocked waiting for the relation to java.

Will dig into it further -- I suspect that it's just an issue w/ a test not setting up a relation.

Here's the failure:

ERROR: spark::02-smoke-test.py
[/tmp/bundletester-oB8F_D/spark/tests/02-smoke-test.py exit 1]
2016-08-01 17:35:51 Starting deployment of local.aws-test:miles
2016-08-01 17:35:52 Deploying services...
2016-08-01 17:37:00 Config specifies num units for subordinate: openjdk
2016-08-01 17:37:01 Adding relations...
2016-08-01 17:37:02  Adding relation spark:java <-> openjdk:java
2016-08-01 17:39:30 Deployment complete in 219.51 seconds
/home/petevg/.local/lib/python3.5/site-packages/path.py:1717: DeprecationWarning
: path is deprecated. Use Path instead.                                        
  warnings.warn(msg, DeprecationWarning)
F
======================================================================
FAIL: test_deploy (__main__.TestDeploy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/bundletester-oB8F_D/spark/tests/02-smoke-test.py", line 41, in test
_deploy                                                                        
    assert "completed" in output['status']
AssertionError

----------------------------------------------------------------------
Ran 1 test in 474.559s

FAILED (failures=1)

**Comment by petevg** [comment]
I merged some fixes for the tests. They "HA" test still fails, but I believe that is related to outstanding issues w/ hadoop HA, which is one of the things that our team is currently working on.

All other tests should pass when run w/ bundletester. Code looks good, too.

**Comment by ktsakalozos** [comment]
Thank you Pete.

More work on HA + fixes are under review here: https://github.com/juju-solutions/bigtop/pull/37

**Comment by ktsakalozos** [comment]
With the latest patch from https://github.com/juju-solutions/bigtop/pull/37 the HA tests are fixed. I am going to squash the commits in preparation for upstream merging

**Pull request closed without merging**
