### PR TITLE
BIGTOP-3416. Fix YCSB to work with CentOS 8 and Fedora 31.

### PR DESCRIPTION
**Pull request by sekikn**
Tested on CentOS 7/8 and Fedora 31.

### CODE REVIEW

**Comment by iwasakims** [comment]
The patch fixed "nothing provides python needed by ycsb-0.12.0-1.el8.noarch" error on deployment on my CentOS 8.

I got following error on smoke-test even with the patch applied.
```
TestYcsbSmoke > BasicDBTest STANDARD_OUT
    Failed command: ycsb load basic -P /usr/lib/ycsb/workloads/workloada -p recordcount=500000 -s > load_basic.dat
        error code: 127
        stdout: []
        stderr: [env: 'python': No such file or directory]

Gradle Test Executor 2 finished executing tests.

> Task :bigtop-tests:smoke-tests:ycsb:test FAILED

TestYcsbSmoke > BasicDBTest FAILED
    java.lang.AssertionError: YCSB basic load failed.[] [env: 'python': No such file or directory]
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert$assertTrue.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216)
        at TestYcsbSmoke.BasicDBTest(TestYcsbSmoke.groovy:65)
```

It looks like `python` is used in the scripts of ycsb. We may need to create symlink same as done for toolchain manifest:
https://github.com/apache/bigtop/blob/master/bigtop_toolchain/manifests/packages.pp#L264-L269

**Comment by sekikn** [comment]
Sorry, I just noticed the newly added patch was not applied for the same reason as #677. Will update the PR soon.

**Review by iwasakims — APPROVED** [review]
+1. It worked for my CentOS 8 env.

**Comment by sekikn** [comment]
Thanks! Merged into master.

**Pull request merged**
