### PR TITLE
BIGTOP-1769. Zeppelin Integration

### PR DESCRIPTION
**Pull request by ejono**

### CODE REVIEW

**Comment by c0s** [comment]
Patch doesn't apply to the current master anymore. Could you please fix/rebase it again? Thanks!

**Comment by c0s** [comment]
Another issue with this patch: how I suppose to build it? The definition of the new component needs to be added to the bigtop.bom file

**Comment by bzz** [comment]
Shall this one be closed, as soon as [BIGTOP-1769](https://issues.apache.org/jira/browse/BIGTOP-1769) is resolved?

**Comment by c0s** [comment]
I guess...

**Pull request closed without merging**
