### PR TITLE
BIGTOP-3825: remove debug messages on Solr build script

### PR DESCRIPTION
**Pull request by kevinw66**
### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by sekikn** [comment]
Oh sorry, my comment may have been misleading. I meant L155 and L157 is unnecessary, but I'm not sure if we could remove L156 without any problem. Can we remove it @kevinw66?

**Comment by kevinw66** [comment]
> Oh sorry, my comment may have been misleading. I meant L155 and L157 is unnecessary, but I'm not sure if we could remove L156 without any problem. Can we remove it @kevinw66?

Yes, that's debug code which I'm trying to view the files under conf dir

**Comment by sekikn** [comment]
+1, sorry for my late response.

**Comment by sekikn** [comment]
Merged into master. Thanks @kevinw66!

**Pull request merged**
