### PR TITLE
BIGTOP-3776. spark-thriftserver should work without external hive-met…

### PR DESCRIPTION
**Pull request by vivostar**
…astore

### Description of PR
Spark thrift server work without external hive-metadata

### How was this patch tested?
1. docker-hadoop deploy stack
```shell
./docker-hadoop.sh \
       -d \
       --create 2 \
       --image bigtop/puppet:trunk-centos-7 \
       --memory 8g \
       --repo http://repos.bigtop.apache.org/releases/3.1.0/centos/7/\$basearch \
       --disable-gpg-check \
       --stack hdfs,yarn,mapreduce,spark
```
2. add spark user folder(if you have built your own local repo, feel free to skip the step)
```shell
sudo -u hdfs hdfs dfs -mkdir /user/spark
sudo -u hdfs hdfs dfs -chmod 777 /user/spark
sudo -u hdfs hdfs dfs -chown spark:spark /user/spark
future="--parser future"
bash -c "puppet apply --detailed-exitcodes $future --hiera_config=/etc/puppet/hiera.yaml --modulepath=/bigtop-home/bigtop-deploy/puppet/modules:/etc/puppet/modules:/usr/share/puppet/modules:/etc/puppetlabs/code/modules:/etc/puppet/code/modules /bigtop-home/bigtop-deploy/puppet/manifests"

```
3. test spark thrift server
```shell
root@26aee8bba11a:/# netstat -an | grep 1200
tcp        0      0 0.0.0.0:12000           0.0.0.0:*               LISTEN
root@26aee8bba11a:/# spark-class org.apache.hive.beeline.BeeLine
...
beeline> !connect jdbc:hive2://localhost:12000
Connecting to jdbc:hive2://localhost:12000
Enter username for jdbc:hive2://localhost:12000: spark
Enter password for jdbc:hive2://localhost:12000: 
0: jdbc:hive2://localhost:12000> show databases;
+------------+
| namespace  |
+------------+
| default    |
+------------+
1 row selected (0.939 seconds)
0: jdbc:hive2://localhost:12000> create database tmp;
+---------+
| Result  |
+---------+
+---------+
No rows selected (0.254 seconds)
0: jdbc:hive2://localhost:12000> create table tmp.person(id string, name string);
+---------+
| Result  |
+---------+
+---------+
No rows selected (0.745 seconds)
0: jdbc:hive2://localhost:12000> insert overwrite table tmp.person select 'test', 'test';
+---------+
| Result  |
+---------+
+---------+
No rows selected (5.358 seconds)
0: jdbc:hive2://localhost:12000> select * from tmp.person;
+-------+-------+
|  id   | name  |
+-------+-------+
| test  | test  |
+-------+-------+
1 row selected (0.468 seconds)
```
### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [x] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by vivostar** [comment]
tested on centos-7, ubuntu-20.04(x86_64)

**Comment by vivostar** [comment]
tested on debian-10, debian-11, fedora-35, rockylinux-8

**Comment by iwasakims** [comment]
Can we use [embedded mode](https://db.apache.org/derby/papers/DerbyTut/embedded_intro.html) instead of network server? Since Spark already contains derby jar (under /usr/lib/spark/jars/), we do not need to bundle derby by ourselves.

I think we just need this for running smoke-tests of Spark alone. Users can use hive-metastore server for practical deployment.

**Comment by vivostar** [comment]
@iwasakims, thanks for your advice, I see what you mean. I will fix this.

**Comment by vivostar** [comment]
I updatet the pr, and tested on all destros.

**Review by iwasakims — APPROVED** [review]
LGTM. Thanks, @vivostar.

**Pull request merged**
