### PR TITLE
BIGTOP-3398. Fix GPDB puppet manifest to work.

### PR DESCRIPTION
**Pull request by sekikn**
Tested on all target distros.

### CODE REVIEW

**Comment by guyuqi** [comment]
+1

**Comment by iwasakims** [comment]
@sekikn I got error on CentOS 8. The cause seems to be hard coded OS version in the URL of epel. Can we fix this here?
https://github.com/apache/bigtop/blob/master/bigtop-deploy/puppet/modules/gpdb/manifests/init.pp#L100

**Comment by sekikn** [comment]
@guyuqi Thank you for reviewing!
@iwasakims Thank you for catching this, I'll update the PR.

**Comment by sekikn** [comment]
Updated the PR, tested on CentOS 7 and 8.

**Review by iwasakims — APPROVED** [review]
+1. Thanks, @sekikn.

**Pull request merged**
