### PR TITLE
BIGTOP-3596. Bump ZooKeeper to 3.5.9.

### PR DESCRIPTION
**Pull request by iwasakims**
This is prerequisite of bumping products using ZooKeeper 3.5 like Hadoop 3.3 and HBase 2.4.

* followed the prefix change of contents of zookeeper-3.5.9-lib.tar.gz.
* addressed the change of output of `zkServer.sh status`.
* We can remove patch0-ZOOKEEPER-3079.diff since ZOOKEEPER-3719 covers the issue.
* We can remove patch1-ZOOKEEPER-3302.diff since 3.5.9 does not have compilation issue reported in ZOOKEEPER-3302.
* We can remove patch2-ZOOKEEPER-2654.diff since ZOOKEEPER-3034 obsoletes the fix.

### CODE REVIEW

**Comment by iwasakims** [comment]
I ran smoke-tests of zookeeper on CentOS 8 (x86_64) and Ubuntu 18.04 (x86_64).

**Comment by iwasakims** [comment]
I got following error on starting zookeeper-server on Fedora 33. I will push additional commit if I can fix this shortly.

```
[root@d0f55e8a6312 /]# systemctl start zookeeper-server
Failed to connect to bus: No such file or directory
```

**Comment by iwasakims** [comment]
> Failed to connect to bus: No such file or directory

I got the above when I provisioned fedora-33 container on fedora-33. I got no issue on using ubuntu-18.04 as hosting environment. It should be my docker setup issue on Fedora 33.

```
$ cat /etc/os-release | grep VERSION=
VERSION="18.04.3 LTS (Bionic Beaver)"

$ ./gradlew bigtop-groovy-pkg-ind bigtop-jsvc-pkg-ind bigtop-utils-pkg-ind zookeeper-pkg-ind repo-ind -POS=fedora-33 -Pprefix=trunk
$ cd provisioner/docker
$ rm config.yaml
$ ./docker-hadoop.sh --create 1 --image bigtop/puppet:trunk-fedora-33 --memory 8g --repo file:///bigtop-home/output --disable-gpg-check --stack zookeeper --smoke-tests zookeeper
```

**Comment by guyuqi** [comment]
LGTM, +1

**Comment by iwasakims** [comment]
Thanks, @guyuqi. I merged this.

**Pull request merged**
