### PR TITLE
BIGTOP-3755. Bump HBase to 2.4.13.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3755

Bumping to 2.4.13 would be nice to have since it contains major fix like [HBASE-27108](https://issues.apache.org/jira/browse/HBASE-27108).

### CODE REVIEW

**Comment by iwasakims** [comment]
tested on Rocky Linux 8 x86_64:

```
$ ./docker-hadoop.sh \
       --create 3 \
       --image bigtop/puppet:trunk-rockylinux-8 \
       --memory 8g \
       --repo file:///bigtop-home/output \
       --disable-gpg-check \
       --stack hdfs,yarn,mapreduce,hbase \
       --smoke-tests hbase
...
Now testing...
:bigtop-tests:smoke-tests:hbase:test (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 3 mins 53.7 secs.

BUILD SUCCESSFUL in 5m 28s
36 actionable tasks: 9 executed, 27 up-to-date
```

**Comment by iwasakims** [comment]
and on CentOS 7 aarch64:

```
$ ./docker-hadoop.sh \
       --create 1 \
       --image bigtop/puppet:trunk-centos-7 \
       --memory 7g \
       --repo file:///bigtop-home/output \
       --disable-gpg-check \
       --stack hdfs,yarn,mapreduce,hbase \
       --smoke-tests hbase
...
Now testing...
:bigtop-tests:smoke-tests:hbase:test (Thread[Execution worker for ':' Thread 3,5,main]) completed. Took 7 mins 54.805 secs.

BUILD SUCCESSFUL in 10m 51s
```

**Comment by guyuqi** [comment]
Tested it on aarch64 Rocklinux8.

**Comment by guyuqi** [comment]
Merged, thanks @iwasakims .

**Pull request merged**
