### PR TITLE
BIGTOP-3448. Building Alluxio fails on all distros.

### PR DESCRIPTION
**Pull request by sekikn**
Tested on Ubuntu 18.04.

### CODE REVIEW

**Review by iwasakims — APPROVED** [review]
+1. worked on CentOS 8 (x86_64).

**Comment by evans-ye** [comment]
Looks good. +1.

**Comment by elukey** [comment]
+1 tested as well on debian 10 :)

**Comment by sekikn** [comment]
Thanks everyone! Merged into master and branch-1.5.

**Pull request merged**
