### PR TITLE
BIGTOP-2980: Hama does not build on DEB type systems

### PR DESCRIPTION
**Pull request by JunHe77**
The rules file doesn't specify patches to apply. Add
missing steps.

Change-Id: I5aaaf89eb6f0a043bac45f4a4a610cbbdef1b91c
Signed-off-by: Jun He <jun.he@linaro.org>

### CODE REVIEW

**Comment by hrw** [comment]
Argh...

Convert those patches into quilt series and use Debian format "3.0 (quilt)" so they get applied automatically.

**Comment by oflebbe** [comment]
Like @hrw said. -1 to this patch. Please convert the whole rules file to a conforming one.
Please consult any other rules file within bigtop for a template. That was the intention of BIGTOP-2980.

**Comment by JunHe77** [comment]
Ah, I'm sorry that I didn't realize the purpose is to use quilt. Have updated the change. Pls review.

**Comment by oflebbe** [comment]
This LGTM, though untested.

**Comment by JunHe77** [comment]
Close this as it has been merged.

**Pull request closed without merging**
