### PR TITLE
BIGTOP-3325. Spark LICENSE files should be exempted by RAT check

### PR DESCRIPTION
**Pull request by evans-ye**

### CODE REVIEW

**Comment by oflebbe** [comment]
Interesting. Isn't Spark Apache ASLv2?

**Comment by evans-ye** [comment]
@oflebbe please see https://github.com/apache/bigtop/pull/597#issuecomment-586547392 ;)

**Comment by oflebbe** [comment]
Oh wow, someone really did the due diligence ;-) Thanks

**Comment by oflebbe** [comment]
Patch LGTM +1

**Pull request merged**
