### PR TITLE
BIGTOP-3595: Fix missing webui module for building Alluxio RMP package and failure to create alluxio user after installing Alluxio

### PR DESCRIPTION
**Pull request by cdyo**

### CODE REVIEW

**Comment by cdyo** [comment]
1. The Alluxio Web cannot be accessed,the WEB UI module is missing in the RPM package;
2. Failed to create the alluxio user,because the var_lib_alluxio variable was not defined;

**Comment by guyuqi** [comment]
@cdyo Thanks for your contribution. 
Could please create a Jira ticket to help to track the issue and change the PR title linked to the related ticket? Thanks.
`https://issues.apache.org/jira/projects/BIGTOP/issues`

**Review by iwasakims — APPROVED** [review]
LGTM. The smoke-tests worked on CentOS 8 (x86_64) and Ubuntu 20.02 (x86_64). I can see the Web UI of Alluxio running in the container by connecting to port 19999.

```
$ ./docker-hadoop.sh --create 1 --image bigtop/puppet:trunk-centos-8 --memory 16g --repo file:///bigtop-home/output --disable-gpg-check --stack hdfs,yarn,mapreduce,alluxio --smoke-tests alluxio
...
BUILD SUCCESSFUL in 52s
34 actionable tasks: 7 executed, 27 up-to-date
```

**Comment by iwasakims** [comment]
I merged this. Thanks for the contribution, @cdyo.

**Pull request merged**
