### PR TITLE
BIGTOP-3376: Make Mpack as a standalone component in Bigtop

### PR DESCRIPTION
**Pull request by guyuqi**
As discussed in #555, launch this new pr to make Mpack as a standalone component in Bigtop.

For users/Bigtopers could easily modify Mapck and make contributions to it like bugfix
and adding more services, the task is to decouple Mpack from Ambari and
put Mpack as a standalone component in Bigtop, like bigtop-packages/src/common/bigtop-mpack.

### CODE REVIEW

**Comment by guyuqi** [comment]
@mattAndruff  This PR is to put Mpack source code as a standalone component.
Please fell free to give comments adn feedback. It would be apreciated if you want fix the issues you found basing on this loop, thank you very much.

**Comment by JunHe77** [comment]
Reviewed and tested with Ambari-2.6.1 included in Bigtop. Let's use this as a start point to add more components. Thanks @guyuqi

**Comment by mattAndruff** [comment]
I''ll try and take a crack at committing my fixes this week.

**Comment by dongqiu** [comment]
has it been tested in Ambari 2.7.5?

**Comment by guyuqi** [comment]
Hi @dongqiu, this Bigtop-Mpack is based on Ambari-2.6.1 and it hasn't been tested based on Ambari 2.7.5 yet . But We did plan to upgrade it to 2.7.x.
By the way, this Mpack just contains some basic components like hdfs, yarn, maprd and Zookeeper. May I ask which components would you like to adopt in your cluster?

**Comment by dongqiu** [comment]
@guyuqi, Thanks for getting back.  You guys are fantastic making this mpack release. A few components in one mpack is exactly what we need to build in my area.  I am looking at separate this mpack make it just contain hdfs yarn maprd only, make it hadoop-mapck, and build other multiple mpacks like zookeeper-mpack, hive-mpack, spark-mpack, hbase-mpack etc.. We have use cases in my organization upgrade the full hdp stack failed because hdp stacks are all of nothing upgrade. We are looking at build open source stack with bigtop components, I would very like to contribute on making mpacks and testing on Ambari 2.7.x.

**Comment by guyuqi** [comment]
Nice to meet you in Bigtop, @dongqiu
It would be awesome if you join us and contribute more to Bigtop. The mpack is a standalone component under path `bigtop-packages/src/common/bigtop-mpack`
Pls also join the Bigtop-Developer-mailing-list:  dev@bigtop.apache.org.
More details:  https://bigtop.apache.org/mail-lists.html
We can discuss more about features, roadmap and bugfix via this mail list.
Welcome to Bigtop, thanks.

**Comment by dongqiu** [comment]
@guyuqi Hi Yuqi, Thanks for the replay i did signed up the mail list.
i am testing with this mpack with newly installed ambari 2.6.1 and run into same issue as below link, The BGTP-1.0 is not showing up in Select Version screen . Can you tell where was issue? 

[https://github.com/apache/bigtop/pull/555#issuecomment-576024282](url)

Steps to test

1. Cloned https://github.com/guyuqi/bigtop-mpack
2. mvn clean package -DskipTests build bgtp-ambari-mpack-1.0.0.0-SNAPSHOT-bgtp-ambari-mpack.tar.gz
3. install ambari-server and agent in 4 hosts
4. ambari-server install-mpack --purge --verbose --mpack=/tmp/bgtp-ambari-mpack-1.0.0.0-SNAPSHOT-bgtp-ambari-mpack.tar.gz
5. ambari-server setup
6. ambari-server start, and all agents
7. launch UI and with Wizard and BGTP 1.0 is not available in Select Version screen.

**Comment by dongqiu** [comment]
@guyuqi Never mind, the issue is gone when switch to PR 
https://github.com/apache/bigtop/tree/master/bigtop-packages/src/common/bigtop-ambari-mpack/bgtp-ambari-mpack

**Comment by hesamd108** [comment]
Hi, I installed apache ambari from: 
https://cwiki.apache.org/confluence/display/AMBARI/Installation+Guide+for+Ambari+2.7.6
and now i want to install your just mpack,
i follow these steps: 
- git clone https://github.com/guyuqi/bigtop-mpack
- cd bgtp bgtp-ambari-mpack
- mvn clean package -DskipTests build bgtp-ambari-mpack-1.0.0.0-SNAPSHOT-bgtp-ambari-mpack.tar.gz

and it return this error: 

[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/hadoop/bigtop-mpack). Please verify you invoked Maven from the correct directory. -> [Help 1]


How Can I solve this problem? 

unnamed

**Comment by guyuqi** [comment]
@hesamd108 

Please build Ambari RPMs from our Bigtop source code:
docker run --rm -v `pwd`:/ws --workdir /ws bigtop/slaves:trunk-centos-7 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew allclean bigtop-utils-pkg bigtop-groovy-pkg bigtop-jsvc-pkg ambari-pkg'

The RPMs would be in BIGTOP_SOURCE/output.

Then, Pls follow the deployment steps: https://github.com/apache/bigtop/pull/555#issuecomment-562415260.

**Comment by truongbk24** [comment]
@guyuqi: after spending 2 weeks to figure out how to build the bigtop mpack but it seems not clear how to pack all the of hadoop component into one tar file. I followed as the below steps:
  - use gradlew and docker container to build the hadoop package
  - use gradlew and docker container to build the spark package
  - use gradlew and docker container to build the zookeeper package
  - use gradlew and docker container to build the hive package
  - use gradlew and docker container to build the ambari package and the mpack
But when i run the ambari webUI, i still see only the default service not the new one service i've just built (lack of the document)
image
One more thing, when i tried to remove the ambari server, i finished to clean everything but when i reinstall it i alway got the error which is no ambari.properties file on folder "/etc/ambari-server/conf/". Pls help me to overcome this. Thank you

**Pull request merged**
