### PR TITLE
BIGTOP-3410. Fix bigtop-tomcat build failure due to downloading problem.

### PR DESCRIPTION
**Pull request by sekikn**

### CODE REVIEW

**Comment by iwasakims** [comment]
I tried `./gradlew bigtop-tomcat-rpm`.  The added patch did not applied since bigtop-tomcat.spec does not contain  the `#BIGTOP_PATCH_FILES` line.

**Comment by sekikn** [comment]
I totally forgot that, thanks @iwasakims! Just updated the PR.

**Review by iwasakims — APPROVED** [review]
+1.

**Comment by iwasakims** [comment]
I would be nice if we can fallback to archive.apache.org for getting not-newest dependencies in follow-up JIRA.

**Comment by sekikn** [comment]
Filed as https://issues.apache.org/jira/browse/BIGTOP-3412 :wink:

**Pull request merged**
