### PR TITLE
BIGTOP-3888: Bump Spark to 3.2.3

### PR DESCRIPTION
**Pull request by kevinw66**
### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by guyuqi** [comment]
Thanks for working on it.
Let me build and test it on Debian11/Rocky 8/Fedora 36.

**Comment by guyuqi** [comment]
@kevinw66 

Sucessfully built Spark on `Rockylinux8` and `Debian11-arm64`.
The smoke tests are also passed on these Distros respectively. 

**But** It **failed** to run Spark smoke tests on Fedora-36:
```
org.apache.bigtop.itest.spark.TestSpark > testSparkSQL STANDARD_OUT
    SPARK_MASTER isn't set. yarn will be used as the master URL. Refer to smoke-tests/README If this isn't what you you expect.
    Failed command: timeout 300 /usr/lib/spark/bin/spark-shell --master yarn --class org.apache.spark.examples.sql.SparkSQLExample  --jars /usr/lib/spark/examples/jars/spark-examples*.jar > /tmp/TestSpark_testSparkSQL.log 2>&1
        error code: 124
        stdout: []
        stderr: []

org.apache.bigtop.itest.spark.TestSpark > testSparkSQL FAILED
    java.lang.AssertionError: Failed ...
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert$assertTrue$0.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216)
        at org.apache.bigtop.itest.spark.TestSpark.testSparkSQL(TestSpark.groovy:91)

org.apache.bigtop.itest.spark.TestSpark > testSparkR STANDARD_OUT
    SPARK_MASTER isn't set. yarn will be used as the master URL. Refer to smoke-tests/README If this isn't what you you expect.
    Failed command: timeout 300 /usr/lib/spark/bin/spark-submit --master yarn /tmp/dataframe.R > /tmp/TestSpark_testSparkR.log 2>&1
        error code: 124
        stdout: []
        stderr: []

org.apache.bigtop.itest.spark.TestSpark > testSparkR FAILED
    java.lang.AssertionError: Failed to execute SparkR script
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert$assertTrue$0.callStatic(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216)
        at org.apache.bigtop.itest.spark.TestSpark.testSparkR(TestSpark.groovy:113)

Gradle Test Executor 2 finished executing tests.

> Task :bigtop-tests:smoke-tests:spark:test FAILED
```



**Rocky8:**
```
$ ./docker-hadoop.sh --create 3 --image bigtop/puppet:trunk-rockylinux-8 \
--memory 16g --repo file:///bigtop-home/output --disable-gpg-check \
--enable-local-repo \
--stack hdfs,yarn,mapreduce,spark \
--smoke-tests spark
```
```
> Task :bigtop-tests:smoke-tests:spark:test
Finished generating test XML results (0.011 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.022 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:spark:test (Thread[Execution worker for ':' Thread 15,5,main]) completed. Took 1 mins 35.486 secs.

BUILD SUCCESSFUL in 2m 39s
```


**Debian-11**
`config_debian-11.yaml`

```
components: [hdfs, yarn, mapreduce, spark]
enable_local_repo: true
smoke_test_components: [spark]
```

```
$ uname -a
5.13.0-40-generic #45~20.04.1-Ubuntu SMP Mon Apr 4 09:40:54 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
$ ./docker-hadoop.sh -C config_debian-11.yaml -c 3 -s -d
.....
...
..
Gradle Test Executor 2 finished executing tests.

> Task :bigtop-tests:smoke-tests:spark:test
Finished generating test XML results (0.027 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.043 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:spark:test (Thread[Execution worker for ':' Thread 8,5,main]) completed. Took 2 mins 21.73 secs.

BUILD SUCCESSFUL in 3m 32s
```

**Comment by kevinw66** [comment]
@guyuqi Thanks for your review, but the smoke tests succeed on my machine for Fedora-36
```
./docker-hadoop.sh -d -C config_fedora-36.yaml --create 3 --memory 4g --repo file:///bigtop-home/output --disable-gpg-check --enable-local-repo --stack yarn,hdfs,spark --smoke-tests spark
```

```
Gradle Test Executor 2 started executing tests.

> Task :bigtop-tests:smoke-tests:spark:test

org.apache.bigtop.itest.spark.TestSpark > testSparkSQL STANDARD_OUT
    SPARK_MASTER isn't set. yarn will be used as the master URL. Refer to smoke-tests/README If this isn't what you you expect.

org.apache.bigtop.itest.spark.TestSpark > testSparkR STANDARD_OUT
    SPARK_MASTER isn't set. yarn will be used as the master URL. Refer to smoke-tests/README If this isn't what you you expect.

Gradle Test Executor 2 finished executing tests.

> Task :bigtop-tests:smoke-tests:spark:test
Finished generating test XML results (0.01 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.019 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:spark:test (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 1 mins 20.387 secs.

BUILD SUCCESSFUL in 3m 21s
30 actionable tasks: 7 executed, 23 up-to-date
Stopped 1 worker daemon(s).
+ rm -rf buildSrc/build/test-results/binary
+ rm -rf /bigtop-home/.gradle
```

**Comment by guyuqi** [comment]
> @guyuqi Thanks for your review, but the smoke tests succeed on my machine for Fedora-36
> 
> ```
> ./docker-hadoop.sh -d -C config_fedora-36.yaml --create 3 --memory 4g --repo file:///bigtop-home/output --disable-gpg-check --enable-local-repo --stack yarn,hdfs,spark --smoke-tests spark
> ```
> 
> ```
> Gradle Test Executor 2 started executing tests.
> 
> > Task :bigtop-tests:smoke-tests:spark:test
> 
> org.apache.bigtop.itest.spark.TestSpark > testSparkSQL STANDARD_OUT
>     SPARK_MASTER isn't set. yarn will be used as the master URL. Refer to smoke-tests/README If this isn't what you you expect.
> 
> org.apache.bigtop.itest.spark.TestSpark > testSparkR STANDARD_OUT
>     SPARK_MASTER isn't set. yarn will be used as the master URL. Refer to smoke-tests/README If this isn't what you you expect.
> 
> Gradle Test Executor 2 finished executing tests.
> 
> > Task :bigtop-tests:smoke-tests:spark:test
> Finished generating test XML results (0.01 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/test-results/test
> Generating HTML test report...
> Finished generating test html results (0.019 secs) into: /bigtop-home/bigtop-tests/smoke-tests/spark/build/reports/tests/test
> Now testing...
> :bigtop-tests:smoke-tests:spark:test (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 1 mins 20.387 secs.
> 
> BUILD SUCCESSFUL in 3m 21s
> 30 actionable tasks: 7 executed, 23 up-to-date
> Stopped 1 worker daemon(s).
> + rm -rf buildSrc/build/test-results/binary
> + rm -rf /bigtop-home/.gradle
> ```

The timeout of Spark smoke tests was expired. Maybe it caused by my limited hardware resource in my local host.(VM)
Thank you for verify this PR on Fedora 36.  

+1 LGTM.

**Comment by guyuqi** [comment]
Merged. Thanks @kevinw66

**Pull request merged**
