### PR TITLE
BIGTOP-3460. Extend timeout for Ambari Server setup.

### PR DESCRIPTION
**Pull request by sekikn**

### CODE REVIEW

**Review by iwasakims — APPROVED** [review]
+1. Thanks, @sekikn.

**Comment by elukey** [comment]
@sekikn feel free to discard this, but would a comment explaining why 600 has been chosen good in this case? Otherwise it looks good :)

**Comment by sekikn** [comment]
@elukey Thanks! I added a comment about that.

**Comment by sekikn** [comment]
Merged into master and branch-1.5. Thank you for reviewing @iwasakims @elukey!

**Pull request merged**
