### PR TITLE
BIGTOP-3810: Fix wrong home configuration for HTTPFS on build scripts

### PR DESCRIPTION
**Pull request by kevinw66**
### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by iwasakims** [comment]
@kevinw66 Could you update [the script for deb](https://github.com/apache/bigtop/blob/fb9ef5da82d6528eef649f594faf87ea2edd7854/bigtop-packages/src/deb/hadoop/hadoop-httpfs.preinst#L40) too?

**Comment by kevinw66** [comment]
> @kevinw66 Could you update [the script for deb](https://github.com/apache/bigtop/blob/fb9ef5da82d6528eef649f594faf87ea2edd7854/bigtop-packages/src/deb/hadoop/hadoop-httpfs.preinst#L40) too?

@iwasakims Updated

**Comment by iwasakims** [comment]
Fix for the spec looks good.

```
$ rpm -q --scripts -p output/hadoop/x86_64/hadoop-httpfs-3.3.4-1.el8.x86_64.rpm | grep home
getent passwd httpfs >/dev/null || /usr/sbin/useradd --comment "Hadoop HTTPFS" --shell /bin/bash -M -r -g httpfs -G httpfs --home /var/lib/hadoop-httpfs httpfs
```

**Review by iwasakims — APPROVED** [review]
LGTM. Thanks, @kevinw66.

**Comment by iwasakims** [comment]
oops. I missed something for deb packaging. I filed [BIGTOP-3815](https://issues.apache.org/jira/browse/BIGTOP-3815) as follow-up. will submit a PR.

```
Setting up hadoop-httpfs (3.3.4-1) ...
chown: cannot access '/var/run/hadoop-httpfs': No such file or directory
dpkg: error processing package hadoop-httpfs (--configure):
```

**Pull request merged**
