### PR TITLE
BIGTOP-2180: Add smoke-test scripts using gradle for Apache Tajo. (This commit depends on BIGTOP-2179) 

### PR DESCRIPTION
**Pull request by yeongeon**

### CODE REVIEW

**Comment by jayunit100** [comment]
Looks like this has come along nicely.  I can't review it myself because I don't have the time, but I think it's close to being mergeable now. Puppet recipes are optional I guess although we prefer to have submitted with the packaging a lot of the time.  Thanks a lot for doing this :).!

**Comment by yeongeon** [comment]
Thanks for your mention. Please let me know if there are any other problems at this commits.
The deployment using the puppet also was included in my plan so, it would be to see next time.

**Comment by jayunit100** [comment]
Thanks again.   

- i think this looks good for a first pass provided its tested.
- @c0s or @oflebbe or anyone else want to review ? To be honest, id be +1 to merging it if others are ok.
- I dont actively work on bigtop right now so Im hesitant to give it a +1 with no other review.

**Comment by youngwookim** [comment]
Oops... I left minor comments on PR/66.

**Comment by yeongeon** [comment]
Thanks guys. I have pushed two fixed.

**Pull request closed without merging**
