### PR TITLE
BIGTOP-3692: Upgrade flink version to 1.15.0

### PR DESCRIPTION
**Pull request by yoda-mon**
### Description of PR
Upgrade flink version to [1.15.0](https://flink.apache.org/news/2022/05/05/1.15-announcement.html).

- From v1.14 Flink uses [husky](https://www.npmjs.com/package/husky) and the library have to be executed by the path that `.git` exists. (ref. https://github.com/typicode/husky/tree/v8.0.1/docs#custom-directory).
- On RPM, `brp-python-bytecompile` tries to compile python 3 code by python 2 and failed. To avoid this, I add an annotation to spec file.

### How was this patch tested?
- **Build**
I checked that the build succeeded on centos-7(arm64) and ubuntu 20.04(amd64)

```sh
./gradlew flink-pkg
```

- **Smoke test**
Before the flink test I built hadoop by

```sh
./gradlew hadoop-pkg
```
and after the flink build I did

```sh
./gradlew repo
```

I tested on docker provisioner.

On centos-7(arm64)
```
./docker-hadoop.sh -d \
  -C config_centos-7.yaml \
  --create 3 \
  --memory 8g \
  --enable-local-repo \
  --repo file:///bigtop-home/output \
  --disable-gpg-check \
  --stack yarn,hdfs,flink \
  --smoke-tests flink
```

On ubuntu-20.04(amd64)
```
./docker-hadoop.sh -d \
  -C config_ubuntu-20.04.yaml \
  --create 3 \
  --memory 8g \
  --enable-local-repo \
  --repo file:///bigtop-home/output/apt \
  --disable-gpg-check \
  --stack yarn,hdfs,flink \
  --smoke-tests flink
```

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [x] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by yoda-mon** [comment]
Unfortunately I could not test on PPC64 environment. 
NodeJS version will be upgrade to `v16.13.2`, so I think the patched problem would be solved, and remove the patch.
I would like to ask administrators to test on PPC64 environment.

**Comment by guyuqi** [comment]
+1
 Verified the PR on Arm64 Centos-8.

**Comment by sekikn** [comment]
I'll try it on ppc64le and feedback the result later.

**Comment by sekikn** [comment]
+1, tested on Fedora 35 ppc64le. Thank you for the contribution @yoda-mon!

**Pull request merged**
