### PR TITLE
BIGTOP-3506. Update hadoop-httpfs resources based on hadoop-3.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3506

Resrouces for hadoop-httpfs such as init scripts, service configuration and puppet manifests should be updated based on hadoop-3 same as done for hadoop-kms in [BIGTOP-3501](https://issues.apache.org/jira/browse/BIGTOP-3501) and [BIGTOP-3505](https://issues.apache.org/jira/browse/BIGTOP-3505).

### CODE REVIEW

**Comment by iwasakims** [comment]
I tested this by following command on CentOS 8. `--smoke-tests httpfs` seems not to work since there is no resouces under bigtop-tests/smoke-tests/https while there is code under bigtop-tests/test-artifacts/httpfs.

```
$ ./docker-hadoop.sh \
   --create 1 \
   --image bigtop/puppet:trunk-centos-8 \
   --memory 16g \
   --repo file:///bigtop-home/output \
   --disable-gpg-check \
   --stack hdfs,httpfs

$ ./docker-hadoop.sh --exec 1 curl -i GET "http://localhost:14000/webhdfs/v1/?user.name=root&op=LISTSTATUS"
curl: (6) Could not resolve host: GET
HTTP/1.1 200 OK
Date: Mon, 22 Feb 2021 10:06:46 GMT
Cache-Control: no-cache
Expires: Mon, 22 Feb 2021 10:06:46 GMT
Date: Mon, 22 Feb 2021 10:06:46 GMT
Pragma: no-cache
Content-Type: application/json
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Set-Cookie: hadoop.auth="u=root&p=root&t=simple-dt&e=1614024406086&s=zDyncElMPPUnIvcqbuahEUuNfKl0etD2EIQlrGfJ2h8="; Path=/; HttpOnly
Transfer-Encoding: chunked

{"FileStatuses":{"FileStatus":[{"pathSuffix":"apps","type":"DIRECTORY","length":0,"owner":"hdfs","group":"hadoop","permission":"755","accessTime":0,"modificationTime":1613987721791,"blockSize":0,"replication":0,"childrenNum":1,"fileId":16415,"storagePolicy":0},{"pathSuffix":"benchmarks","type":"DIRECTORY","length":0,"owner":"hdfs","group":"hadoop","permission":"777","accessTime":0,"modificationTime":1613987721651,"blockSize":0,"replication":0,"childrenNum":0,"fileId":16394,"storagePolicy":0},{"pathSuffix":"hbase","type":"DIRECTORY","length":0,"owner":"hbase","group":"hbase","permission":"755","accessTime":0,"modificationTime":1613987721642,"blockSize":0,"replication":0,"childrenNum":0,"fileId":16392,"storagePolicy":0},{"pathSuffix":"solr","type":"DIRECTORY","length":0,"owner":"solr","group":"solr","permission":"755","accessTime":0,"modificationTime":1613987721646,"blockSize":0,"replication":0,"childrenNum":0,"fileId":16393,"storagePolicy":0},{"pathSuffix":"tmp","type":"DIRECTORY","length":0,"owner":"hdfs","group":"hadoop","permission":"1777","accessTime":0,"modificationTime":1613987721622,"blockSize":0,"replication":0,"childrenNum":1,"fileId":16386,"storagePolicy":0},{"pathSuffix":"user","type":"DIRECTORY","length":0,"owner":"hdfs","group":"hadoop","permission":"755","accessTime":0,"modificationTime":1613987920595,"blockSize":0,"replication":0,"childrenNum":15,"fileId":16395,"storagePolicy":0},{"pathSuffix":"var","type":"DIRECTORY","length":0,"owner":"hdfs","group":"hadoop","permission":"755","accessTime":0,"modificationTime":1613987721609,"blockSize":0,"replication":0,"childrenNum":1,"fileId":16387,"storagePolicy":0}]}}
```

**Comment by iwasakims** [comment]
I got following error on Ubuntu 18.04. I'm looking into the cause.

```
Error: Systemd start for hadoop-httpfs failed!
journalctl log for hadoop-httpfs:
-- Logs begin at Mon 2021-02-22 10:09:24 UTC, end at Mon 2021-02-22 10:11:13 UTC. --
Feb 22 10:11:08 65add4f9bec9 systemd[1]: Starting LSB: Hadoop httpfs...
Feb 22 10:11:08 65add4f9bec9 runuser[5252]: pam_unix(runuser:session): session opened for user httpfs by (uid=0)
Feb 22 10:11:08 65add4f9bec9 hadoop-httpfs[5231]: WARNING: httpfs.sh is deprecated, please use 'hdfs [--daemon start|status|stop] httpfs'.
Feb 22 10:11:08 65add4f9bec9 hadoop-httpfs[5231]: /usr/lib/hadoop/sbin/httpfs.sh: line 64: /bin/hdfs: No such file or directory
Feb 22 10:11:08 65add4f9bec9 runuser[5252]: pam_unix(runuser:session): session closed for user httpfs
Feb 22 10:11:13 65add4f9bec9 hadoop-httpfs[5231]:  * Failed to start Hadoop httpfs. Return value: 3
Feb 22 10:11:13 65add4f9bec9 systemd[1]: hadoop-httpfs.service: Control process exited, code=exited status=3
Feb 22 10:11:13 65add4f9bec9 systemd[1]: hadoop-httpfs.service: Failed with result 'exit-code'.
Feb 22 10:11:13 65add4f9bec9 systemd[1]: Failed to start LSB: Hadoop httpfs.
```

**Comment by iwasakims** [comment]
I got expected result on both CentOS 8 and Ubuntu 18.04 by the last commit.

**Comment by sekikn** [comment]
+1, the same check also succeeded on CentOS 7 and Debian 10. Thanks @iwasakims!

**Pull request merged**
