### PR TITLE
BIGTOP-3778: Fix Hive3.1.3 WebHCat service compatible issue with Hadoop3.3.x

### PR DESCRIPTION
**Pull request by kevinw66**
### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by guyuqi** [comment]
Thanks for working on it, @kevinw66 

What about adding JIRA number prefix to the patch name like `patch11-HIVE-24083-webhcat-xxxx.diff` ?
It could be convenient for us to track the Hive issues and reduce our maintenance burden in Bigtop.  If it was merged to Hive trunk, we could easily remove it from Bigtop.
Thanks.

**Comment by kevinw66** [comment]
@guyuqi Done

**Comment by guyuqi** [comment]
Let me test it by Hive building and Hive deployment in Mapck.

**Comment by guyuqi** [comment]
+1. 
Tested build and smoke tests on Rockylinux-8:
```
Successfully started process 'Gradle Test Executor 2'

Gradle Test Executor 2 started executing tests.
Gradle Test Executor 2 finished executing tests.

> Task :bigtop-tests:smoke-tests:hive:test
Finished generating test XML results (0.023 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hive/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.028 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hive/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:hive:test (Thread[Execution worker for ':',5,main]) completed. Took 24.281 secs.

BUILD SUCCESSFUL in 1m 34s
```

Verified Hive Mapck deployment on Arm64/x86_64:


hive_mpack

**Comment by guyuqi** [comment]
Merged, thanks. @kevinw66

**Pull request merged**
