### PR TITLE
BIGTOP-3688. Bump Hadoop to 2.10.2 in branch-1.5.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3688

Hadoop 2.10.2 is under release vote.

### CODE REVIEW

**Comment by iwasakims** [comment]
This is a draft using Hadoop 2.10.2-RC0. I will update the bigtop.bom to use released artifacts later.

**Comment by iwasakims** [comment]
I built HBase 1.5.0, Hive 2.3.6, Spark 2.4.5 against Hadoop 2.10.2-RC0 and ran smoke-tests on CentOS 7 x86_64.

```
$ ./gradlew bigtop-groovy-pkg bigtop-jsvc-pkg bigtop-tomcat-pkg bigtop-utils-pkg zookeeper-pkg hadoop-pkg hbase-pkg hive-pkg spark-pkg repo

$ ./docker-hadoop.sh \
       --create 3 \
       --image bigtop/puppet:trunk-centos-7 \
       --memory 8g \
       --repo file:///bigtop-home/output \
       --disable-gpg-check \
       --stack hdfs,yarn,mapreduce,hbase,hive,spark \
       --smoke-tests hdfs,yarn,mapreduce,hbase,hive,spark
...
BUILD SUCCESSFUL in 17m 4s
55 actionable tasks: 20 executed, 35 up-to-date
```

**Comment by sekikn** [comment]
+1, tested on Debian 10 x86_64.

**Comment by sekikn** [comment]
Merged into branch-1.5. Thanks @iwasakims!

**Comment by tullis** [comment]
> +1, tested on Debian 10 x86_64.

@sekikn - Would you be able to share your build and testing method for Debian 10 please?

I'm getting a build failure for Debian 10 x86_64 and I'd be interested to know if I'm doing something wrong before I go and create a JIRA ticket.

The command I'm using is as follows:

```
docker run --rm  -v `pwd`:/ws --workdir /ws bigtop/slaves:1.5.0-debian-10 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew allclean hadoop-pkg'
```

The errors I'm getting are when it's packaging the hdfs-native-client, I think.
Looks like missing binaries, so perhaps there was an earlier linker error.
```
+ cp '/build/libexec/*' debian/tmp/usr/lib/hadoop/libexec//
cp: cannot stat '/build/libexec/*': No such file or directory
make[1]: *** [debian/rules:55: override_dh_auto_install] Error 1
make[1]: Leaving directory '/ws/output/hadoop/hadoop-2.10.2'
make: *** [debian/rules:27: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b
 failed

> Task :hadoop-deb FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/ws/packages.gradle' line: 354

* What went wrong:
Execution failed for task ':hadoop-deb'.
```

Many thanks.

**Comment by sekikn** [comment]
@tullis Thank you for the information. I was also able to reproduce it.
Maybe I ran the command without patch before.

```
$ docker run -it -v `pwd`:/ws -w /ws bigtop/slaves:1.5.0-debian-10 bash
Unable to find image 'bigtop/slaves:1.5.0-debian-10' locally
1.5.0-debian-10: Pulling from bigtop/slaves

...

Digest: sha256:71edd9f9fd6816795a28ae5b45624cd8024bf076c66a592f46bd13277ec221b8
Status: Downloaded newer image for bigtop/slaves:1.5.0-debian-10
root@8cf4af83e82e:/ws# . /etc/profile.d/bigtop.sh 
root@8cf4af83e82e:/ws# ./gradlew allclean hadoop-pkg repo -Dbuildwithdeps=true

...

+ install -d -m 0755 debian/tmp/usr/lib/hadoop/libexec/                                                                                                                      
+ cp '/build/libexec/*' debian/tmp/usr/lib/hadoop/libexec//                                                                                                                  
cp: cannot stat '/build/libexec/*': No such file or directory                                                                                                                
```

@iwasakims Could you take a look?

**Comment by iwasakims** [comment]
@tullis @sekikn 
I guess the `${PWD}` in the value of `--build-dir` was not expanded as expected.
https://github.com/apache/bigtop/blob/branch-1.5/bigtop-packages/src/deb/hadoop/rules#L59

```
bash debian/install_hadoop.sh \
  --prefix=debian/tmp/ \
  --distro-dir=debian \
  --build-dir=/build \
  --httpfs-dir=debian/tmp/usr/lib/hadoop-httpfs \
  --httpfs-etc-dir=debian/tmp/etc/hadoop-httpfs \
  --kms-dir=debian/tmp/usr/lib/hadoop-kms \
  --kms-etc-dir=debian/tmp/etc/hadoop-kms \
  --system-lib-dir=debian/tmp/usr/lib/ \
  --system-libexec-dir=debian/tmp/usr/lib/hadoop/libexec/ \
  --system-include-dir=debian/tmp/usr/include \
  --doc-dir=debian/tmp/usr/share/doc/hadoop-doc \
          --man-dir=debian/tmp/usr/share/man \
  --example-dir=debian/tmp/usr/share/doc/hadoop/examples \
  --native-build-string=Linux-amd64-64 \
  --installed-lib-dir=/usr/lib/hadoop
```

**Comment by iwasakims** [comment]
`./gradlew hadoop-pkg-ind -POS=debian-10 -Pprefix=1.5.0` (i.e. without manually launching container) worked as expected.

```
bash debian/install_hadoop.sh \
  --prefix=debian/tmp/ \
  --distro-dir=debian \
  --build-dir=/bigtop/output/hadoop/hadoop-2.10.2/build \
  --httpfs-dir=debian/tmp/usr/lib/hadoop-httpfs \
  --httpfs-etc-dir=debian/tmp/etc/hadoop-httpfs \
  --kms-dir=debian/tmp/usr/lib/hadoop-kms \
  --kms-etc-dir=debian/tmp/etc/hadoop-kms \
  --system-lib-dir=debian/tmp/usr/lib/ \
  --system-libexec-dir=debian/tmp/usr/lib/hadoop/libexec/ \
  --system-include-dir=debian/tmp/usr/include \
  --doc-dir=debian/tmp/usr/share/doc/hadoop-doc \
          --man-dir=debian/tmp/usr/share/man \
  --example-dir=debian/tmp/usr/share/doc/hadoop/examples \
  --native-build-string=Linux-amd64-64 \
  --installed-lib-dir=/usr/lib/hadoop
```

**Comment by sekikn** [comment]
@iwasakims You are right, replacing `${PWD}` with `$(CURDIR)` seems to work since the rules file is a Makefile. Thanks a lot!
(But I'm still not sure why it succeeds without changes when executed via `./gradlew hadoop-pkg-ind`...)
I'll submit a PR after testing with some distros additionally.

**Comment by sekikn** [comment]
I've just noticed that Luca has already addressed this issue in BIGTOP-3527 (#760). I'll backport it to branch-1.5.

**Pull request merged**
