### PR TITLE
BIGTOP-3857: Support parent directory default configuration for Hadoop rpm

### PR DESCRIPTION
**Pull request by timyuer**
BIGTOP-3857: Support parent directory default configuration for Hadoop rpm

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by kevinw66** [comment]
+1, tested on Ambari.

**Comment by iwasakims** [comment]
bigtop-packages/src/common/hadoop/hadoop.default should be removed if it is not used anymore? @timyuer.

**Comment by timyuer** [comment]
> bigtop-packages/src/common/hadoop/hadoop.default should be removed if it is not used anymore? @timyuer.

This is a missing point, and I'll fix it soon

**Comment by timyuer** [comment]
bigtop-packages/src/common/hadoop/hadoop.default has been removed, and tested in Centos7(x86_64) and Ubuntu20.04(x86_64).  @iwasakims

**Review by iwasakims — APPROVED** [review]
LGTM. Thanks, @timyuer.

**Pull request merged**
