### PR TITLE
BIGTOP-2426. Bump Flink version to 1.0.3

### PR DESCRIPTION
**Pull request by mbalassi**
Just a missing whitespace and line number updates.

### CODE REVIEW

**Comment by mbalassi** [comment]
Unfortunately the build still fails, I will continue investigating tomorrow.

```
dpkg-source: info: building flink using existing ./flink_1.0.0.orig.tar.gz
dpkg-source: info: local changes detected, the modified files are:
 flink-1.0.0/docs/setup/config.md
 flink-1.0.0/flink-dist/src/main/flink-bin/bin/config.sh
dpkg-source: error: aborting due to unexpected upstream changes, see /tmp/flink_1.0.0-1.diff.uU9FvM
dpkg-source: info: you can integrate the local changes with dpkg-source --commit
dpkg-buildpackage: error: dpkg-source -b flink-1.0.0 gave error exit status 2
:flink-sdeb FAILED
```

**Comment by mbalassi** [comment]
I have checked in the meantime, the rpm package builds successfully.

**Comment by c0s** [comment]
Are you changing the source code of the project during the build time? That's what the error message implies.

**Comment by rmetzger** [comment]
The Flink project just released version 1.0.3, which contains a fix for the issue we are patching here.
By bumping the Flink version to 1.0.3 in bigtop, we can get rid of the patch entirely.

Do you agree to rename the JIRA to "Bump Flink to 1.0.3" ?

**Comment by oflebbe** [comment]
@rmetzger : No problem. Just rename JIRA and patch subject.

**Comment by mbalassi** [comment]
Thanks, @rmetzger & @oflebbe. I am renaming the JIRA and updating the PR accordingly.

**Comment by mbalassi** [comment]
I am still testing the change, will let you know when I can confirm the builds.

**Comment by mbalassi** [comment]
Both of the builds finished fine. 👍

**Comment by rmetzger** [comment]
+1 to merge

I tested the build and the final artifact on debian and it works!

**Pull request merged**
