### PR TITLE
BIGTOP-3520. Drop ignite-hadoop.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3520

### CODE REVIEW

**Comment by iwasakims** [comment]
I tested Zeppelin packaging and smoke-tests after the ignite-hadoop removal.

```
./docker-hadoop.sh \
  --create 1 \
  --image bigtop/puppet:trunk-centos-8 \
  --memory 16g \
  --repo file:///bigtop-home/output \
  --disable-gpg-check \
  --stack hdfs,yarn,mapreduce,spark,zeppelin \
  --smoke-tests zeppelin
```

**Comment by sekikn** [comment]
It seems that ignite-hadoop is still in the "component" section in bigtop.bom even with PR.

**Comment by iwasakims** [comment]
> It seems that ignite-hadoop is still in the "component" section in bigtop.bom even with this PR.

Oops. Thanks, @sekikn . I addressed the comment and rebased.

**Comment by sekikn** [comment]
+1, thanks @iwasakims!

**Pull request merged**
