### PR TITLE
WIP: BIGTOP-3698: Bump Hive to 3.1.3

### PR DESCRIPTION
**Pull request by yoda-mon**
### Description of PR
Upgrade Hive version to 3.1.3.
Mainly remove and fix patches because Hive's log4j2 version is updated on v3.1.3.

### How was this patch tested?
I checked on CentOS 7/arm64 and Ubuntu 20.04/amd64.

**Build**
```sh
./gradlew hive-pkg -Dbuildwithdeps=true
```

**Smoke Test**
```sh
./docker-hadoop.sh -d \
  -C config_centos-7.yaml \
  --create 3 \
  --memory 8g \
  --enable-local-repo \
  --repo file:///bigtop-home/output \
  --disable-gpg-check \
  --stack yarn,hdfs,mapreduce,spark,hive \
  --smoke-tests hive

./docker-hadoop.sh -d \
  -C config_ubuntu-20.04.yaml \
  --create 3 \
  --memory 8g \
  --enable-local-repo \
  --repo file:///bigtop-home/output/apt \
  --disable-gpg-check \
  --stack yarn,hdfs,mapreduce,spark,hive \
  --smoke-tests hive
```

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [x] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Review by iwasakims — APPROVED** [review]
+1. smoke-tests passed on Rocky Linux 8 x86_64 on my local.

**Comment by iwasakims** [comment]
I merged this. Thanks, @yoda-mon.

**Comment by iwasakims** [comment]
Oops. I missed that you changed the title to WIP. Could you file follow-up JIRA if you need? @yoda-mon.

**Comment by yoda-mon** [comment]
@iwasakims I'm really sorry for confusing.
After I created this PR, I noticed that there is a discussion about upgrading Hadoop 3.3.x and this PR is still staying on Hadoop 3.2 and I changed the title to WIP in a hurry.
After thinking about it, we can separate this PR and upgrading to Hadoop 3.3.x. I would like to remove WIP status later.

**Pull request merged**
