### PR TITLE
BIGTOP-3680: Update jruby's version to fix the smoke test failure on ppc64le

### PR DESCRIPTION
**Pull request by yoda-mon**
### Description of PR
To fix the smoke test failure on ppc64le, update the version of jruby on power pc.

### How was this patch tested?
No, I would like to ask the administrators to redo the test environment.

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [x] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by sekikn** [comment]
Thanks, I'll try your PR on ppc64le.

**Comment by yoda-mon** [comment]
I would like to ask the Jenkins administrators to test this PR work (cc @sekikn ).

**Comment by sekikn** [comment]
+1, tested on ppc64le and confirmed the PR worked. Thanks for the contribution @yoda-mon!

```
jenkins@bigtop1slave:~/bigtop$ sudo chown -R 1000:1000 .
jenkins@bigtop1slave:~/bigtop$ docker run -it -v $PWD:/bigtop bigtop/slaves:3.1.0-centos-7-ppc64le bash
[root@19bf67f49530 /]# facter architecture
ppc64le
[root@19bf67f49530 /]# cd bigtop
[root@19bf67f49530 bigtop]# curl -sL https://github.com/apache/bigtop/pull/900.patch | git apply
[root@19bf67f49530 bigtop]# git diff
diff --git a/bigtop-packages/src/common/hbase/do-component-build b/bigtop-packages/src/common/hbase/do-component-build
index be6d8ef..ed8493d 100644
--- a/bigtop-packages/src/common/hbase/do-component-build
+++ b/bigtop-packages/src/common/hbase/do-component-build
@@ -35,7 +35,6 @@ fi
 if [ $HOSTTYPE = "powerpc64le" ] ; then
   sed -i "s|<asciidoctor.plugin.version>.*</asciidoctor.plugin.version>|<asciidoctor.plugin.version>1.5.3</asciidocto
   sed -i 's|<asciidoctorj.pdf.version>.*</asciidoctorj.pdf.version>|<asciidoctorj.pdf.version>1.5.0-alpha.11</asciido
-  sed -i 's|<jruby.version>.*</jruby.version>|<jruby.version>1.7.23</jruby.version>|' pom.xml
   mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=2.5.0 \
       -Dclassifier=linux-ppcle_64 -Dpackaging=exe -Dfile=/usr/local/bin/protoc
   mvn install:install-file -DgroupId=com.google.protobuf -DartifactId=protoc -Dversion=3.17.3 \
[root@19bf67f49530 bigtop]# ./gradlew allclean hbase-pkg repo -Dbuildwithdeps=true

...

BUILD SUCCESSFUL in 2h 1m 41s
79 actionable tasks: 79 executed
[root@19bf67f49530 bigtop]# exit
$ sudo chown -R jenkins:jenkins .
$ cd provisioner/docker
$ ./docker-hadoop.sh -d -k hdfs,hbase -r file:///bigtop-home/output -s hbase -G -c 1

...

> Task :bigtop-tests:smoke-tests:hbase:test
Finished generating test XML results (0.072 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hbase/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.073 secs) into: /bigtop-home/bigtop-tests/smoke-tests/hbase/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:hbase:test (Thread[Execution worker for ':' Thread 7,5,main]) completed. Took 5 mins 25.713 secs.

BUILD SUCCESSFUL in 6m 28s
36 actionable tasks: 9 executed, 27 up-to-date
```

**Comment by sekikn** [comment]
Merged into master and branch-3.1.

**Pull request merged**
