### PR TITLE
BIGTOP-4298: Upgrade Ranger  to 2.5.0

### PR DESCRIPTION
**Pull request by JiaLiangC**
### Description of PR
upgrade ranger to 2.5.0

The Ranger plugin does not support Kafka 3, and including Kafka 3 will cause compilation failures. Kafka 3 has its own permission/authorization system, so the Kafka plugin compilation has been removed.

### How was this patch tested?
build successfully in  rocky-8
. /etc/profile.d/bigtop.sh;./gradlew ranger-clean ranger-pkg  -PbuildThreads=2C repo
image

smote test run successfully on rocky-8
./docker-hadoop.sh -d -dcp -C config_rockylinux-8.yaml -F docker-compose-cgroupv2.yml -r file:///bigtop-home/output -L -G -k bigtop-utils,ranger  -s ranger -c 1
image

build successfully in  debian-11
image

smote test run successfully on debian-11
./docker-hadoop.sh -d -dcp -C config_debian-11.yaml -F docker-compose-cgroupv2.yml -r file:///bigtop-home/output -L -G -k bigtop-utils,ranger  -s ranger -c 1
image

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by iwasakims** [comment]
Hmm. Packaging fails due to unresolved dependency. I will retry this tomorrow to see if it is server side issue.

```
[ERROR] Failed to execute goal on project ranger-knox-plugin: Could not resolve dependencies for project org.apache.ranger:ranger-knox-plugin:jar:2.5.0: The following artifacts could not be resolved: org.jetbrains.pty4j:pty4j:jar:0.11.4, org.jetbrains.pty4j:purejavacomm:jar:0.0.11.1: Could not find artifact org.jetbrains.pty4j:pty4j:jar:0.11.4 in apache.snapshots.https (https://repository.apache.org/content/repositories/snapshots) -> [Help 1]
```

**Comment by JiaLiangC** [comment]
> Hmm. Packaging fails due to unresolved dependency. I will retry this tomorrow to see if it is server side issue.
> 
> ```
> [ERROR] Failed to execute goal on project ranger-knox-plugin: Could not resolve dependencies for project org.apache.ranger:ranger-knox-plugin:jar:2.5.0: The following artifacts could not be resolved: org.jetbrains.pty4j:pty4j:jar:0.11.4, org.jetbrains.pty4j:purejavacomm:jar:0.0.11.1: Could not find artifact org.jetbrains.pty4j:pty4j:jar:0.11.4 in apache.snapshots.https (https://repository.apache.org/content/repositories/snapshots) -> [Help 1]
> ```

I encountered similar dependency download issues when compiling Ranger. I resolved it by replacing all Maven mirror repositories in Ranger's root pom file with China's domestic mirrors, and then it worked fine. I didn't make this commit because it's likely due to China's network isolation issues.

**Comment by iwasakims** [comment]
@JiaLiangC We need [the patch](https://github.com/apache/ranger/commit/8bb2053) of [RANGER-4919](https://issues.apache.org/jira/browse/RANGER-4919) to fix the build failure. Could add the patch file to bigtop-packages/src/common/ranger?

**Comment by iwasakims** [comment]
@JiaLiangC Are you willing to keep working on this?

**Comment by JiaLiangC** [comment]
@iwasakims  Of course, my personal repository was too messy, so I closed it and forked the repository again, which resulted in the PR being closed.

**Pull request closed without merging**
