### PR TITLE
BIGTOP-1888. Upgrade Flume to 1.6.0

### PR DESCRIPTION
**Pull request by youngwookim**

### CODE REVIEW

**Comment by jayunit100** [comment]
Looks like there are some kite changes in here? Maybe accidental?

**Comment by youngwookim** [comment]
Jay, Kite in the Bigtop stack! 

https://issues.apache.org/jira/browse/BIGTOP-1149

**Comment by jayunit100** [comment]
Ah ok so flume is reading a kite version.  That makes sense. +1

**Comment by youngwookim** [comment]
Thanks Jay for reviewing the patch! I'll commit it shortly.

**Pull request closed without merging**
