### PR TITLE
BIGTOP-3913:The path information is incorrect in the zookeeper-client script file by building with -PparentDir

### PR DESCRIPTION
**Pull request by guluo2016**
### Description of PR

fix bug, see:  [BIGTOP-3913](https://issues.apache.org/jira/browse/BIGTOP-3913)

### How was this patch tested?

Building package with -PparentDir=/usr/bigtop for zk, 
and installing zookeeper, 
and testing by executing zookeeper-client,zookeeper-server,zookeeper-server-cleanup,zookeeper-server-initialize

### For code changes:
install_zookeeper.sh

Please review @iwasakims thanks

### CODE REVIEW

**Comment by iwasakims** [comment]
@guluo2016 Could you increment [the release number of the package](https://github.com/apache/bigtop/blob/dc4fe2d6655b3b3f1257f947203fd851a51c1b08/bigtop.bom#L138) to 3? Already released Bigtop 3.2.0 [bundles zookeeper as zookeeper-3.5.9-2](https://issues.apache.org/jira/browse/BIGTOP-3724).

**Comment by guluo2016** [comment]
>

**Comment by guluo2016** [comment]
@iwasakims   Increaseing [the release number of zookeeper](https://github.com/apache/bigtop/blob/dc4fe2d6655b3b3f1257f947203fd851a51c1b08/bigtop.bom#L138) to 3. Does this mean that other components also need to be updated? For example, hadoop, hive, etc.
Because [the release number of hadoop](https://github.com/apache/bigtop/blob/master/bigtop.bom#L154) is not 3

**Comment by iwasakims** [comment]
@guluo2016
> Does this mean that other components also need to be updated? For example, hadoop, hive, etc.

No.

We need to increment the release number if we modify package contents without bumping the version of the product. The version of ZooKeeper packaged by Bigtop 3.2.0 is 3.5.9-2. If we release Bigtop 3.2.1 now, the version will be 3.5.9-3. It implies that the package contents was changed within zookeeper-3.5.9 and we can upgrade installed package by `rpm -U zookeeper` or `yum update zookeeper` (for RPM as example).

We don't need increment the release number of ZooKeeper again before releasing Bigtop 3.2.1 (or Biptop 3.3.0). We can reset the release number to 1 if we bump the ZooKeeper to 3.5.10 or later.

**Comment by guluo2016** [comment]
> @guluo2016
> 
> > Does this mean that other components also need to be updated? For example, hadoop, hive, etc.
> 
> No.
> 
> We need to increment the release number if we modify package contents without bumping the version of the product. The package version of ZooKeeper packaged by Bigtop 3.2.0 is 3.5.9-2. If we release Bigtop 3.2.1 now, the version will be 3.5.9-3. It implies that the package contents was changed within zookeeper-3.5.9 and we can upgrade installed package by `rpm -U zookeeper` or `yum update zookeeper` (for RPM as example).
> 
> We don't need increment the release number of ZooKeeper again before releasing Bigtop 3.2.1 (or Biptop 3.3.0). We can reset the release number to 1 if we bump the ZooKeeper to 3.5.10 or later.

Understanded!  thank you

**Pull request merged**
