### PR TITLE
BIGTOP-3158. [Test] Fix test specification with maven failsafe plugin

### PR DESCRIPTION
**Pull request by evans-ye**

### CODE REVIEW

**Comment by oflebbe** [comment]
Would you like to introduce a variable for surefire version plugin  ?

**Comment by evans-ye** [comment]
Hey @oflebbe let me try to understand. Are you proposing to add version variable for failsafe plugin in parrent pom.xml and utilized that in child pom.xml?

**Comment by oflebbe** [comment]
exactlz

**Comment by evans-ye** [comment]
@oflebbe Patch updated. Please review ;)

**Pull request merged**
