### PR TITLE
BIGTOP-4278. Upgrade Kafka to 3.4.1.

### PR DESCRIPTION
**Pull request by sekikn**
### Description of PR

This PR upgrades Kafka to 3.9.0 for the Bigtop 3.4.0 release.

### How was this patch tested?

Tested on Debian 11 and Rocky 9, as follows:

```
$ ./gradlew kafka-clean kafka-pkg repo -Dbuildwithdeps=true
$ cd provisioner/docker
$ ./docker-hadoop.sh -d -dcp -C config_debian-11.yaml -F docker-compose-cgroupv2.yml -G -L -k zookeeper,kafka -s kafka -c 3

...

> Task :bigtop-tests:smoke-tests:kafka:test
Finished generating test XML results (0.003 secs) into: /bigtop-home/bigtop-tests/smoke-tests/kafka/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.01 secs) into: /bigtop-home/bigtop-tests/smoke-tests/kafka/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:kafka:test (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 6.02 secs.

BUILD SUCCESSFUL in 48s
27 actionable tasks: 7 executed, 20 up-to-date
```

```
$ ./gradlew kafka-clean kafka-pkg repo -Dbuildwithdeps=true
$ cd provisioner/docker
$ ./docker-hadoop.sh -d -dcp -C config_rockylinux-9.yaml -F docker-compose-cgroupv2.yml -G -L -r file:///bigtop-home/output -k zookeeper,kafka -s kafka -c 3                                                                                                         

> Task :bigtop-tests:smoke-tests:kafka:test
Finished generating test XML results (0.005 secs) into: /bigtop-home/bigtop-tests/smoke-tests/kafka/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.008 secs) into: /bigtop-home/bigtop-tests/smoke-tests/kafka/build/reports/tests/test
Now testing...
:bigtop-tests:smoke-tests:kafka:test (Thread[Daemon worker,5,main]) completed. Took 6.187 secs.

BUILD SUCCESSFUL in 22s
27 actionable tasks: 7 executed, 20 up-to-date
```

### For code changes:

- [x] Does the title or this PR starts with the corresponding JIRA issue id (e.g. 'BIGTOP-3638. Your PR title ...')?
- [x] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by sekikn** [comment]
I've just noticed Spark 3.5.3 has API incompatibility with recent versions of Kafka, so I'll downgrade Kafka to 3.4.1, which Spark 3.5.3 is built against by default. I'll also downgrade Scala to 2.12.x, since some script provided by Spark to switch Scala version doesn't seem to work in Bigtop's build process as it is.

**Comment by iwasakims** [comment]
Hmm. test2ReadKafkaTopics fails on rockylinux-8 aarch64. I'm looking into the cause.

**Comment by iwasakims** [comment]
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/lib/kafka/libs/logback-classic-1.2.13.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/kafka/libs/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```

@sekikn The cause of test failure turned out to be multiple logger bindings. If the logback binding is used, settings in log4j.properties and tools-log4j.properties are ignored and all level of logs are emitted to stdout. Since the test2ReadKafkaTopics compares stdout of kafka-console-consumer.sh with the expected result, the emitted logs break the test. Removing the logback-classic-1.2.13.jar fixed the issue.

**Comment by sekikn** [comment]
@iwasakims Thank you for finding a test failure and investigating its cause! I've just pushed a new commit for excluding logback-classic and ensured that it worked on x86_64 with some distros, but I'm afraid I don't have a Rocky8-installed arm64 machine. Would you try the latest PR?

**Review by iwasakims — APPROVED** [review]
+1. smoke-tests passed. Thanks for the update, @sekikn.

**Pull request merged**
