### PR TITLE
BIGTOP-3287. Bump Hadoop to 2.10.0.

### PR DESCRIPTION
**Pull request by iwasakims**
* upgraded version in bigtop.bom.
* removed patch of HADOOP-12366 which is included in hadoop-2.10.0.
* added patch of YARN-9945 to address build failured by jdk8.
* added jars of hadoop-yarn-server-timelineservice as files of hadoop-yarn.
* fixed classpath to invoke init-hcfs.groovy using hadoop classpath command.
* assuming tomcat-8.5.43 along with HADOOP-16439.

### CODE REVIEW

**Comment by iwasakims** [comment]
creating cluster by docker provisioner worked for me.

```
$ cd provisioner/docker
$ ./docker-hadoop.sh --create 5
```

runnign smoke tests is wip.

**Comment by iwasakims** [comment]
While Hadoop updated the versino of bundled Tomcat to 8.5 ( [HADOOP-16439](https://issues.apache.org/jira/browse/HADOOP-16439) ), hadoop-httpfs of Bigtop depends on bigtop-tomcat which is depended by other producs such as Sqoop and Oozie. I would like to address updating Tomcat in follow-up JIRAs.

**Comment by iwasakims** [comment]
Smoke-tests of hdfs, yarn, mapreduce are passed on my local docker provisioned 3 node cluster.

**Comment by sekikn** [comment]
Hmm, I tried to build Hadoop on CentOS 8 and Ubuntu 16.04 with the latest commit just in case, and encountered the following error on both.

```
$ ./gradlew hadoop-pkg -Dbuildwithdeps=true

(snip)

[INFO] --- maven-javadoc-plugin:2.8.1:jar (module-javadocs) @ hadoop-common ---
[INFO] 
ExcludePrivateAnnotationsStandardDoclet
1 error
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Apache Hadoop Main 2.10.0 .......................... SUCCESS [ 44.166 s]
[INFO] Apache Hadoop Build Tools .......................... SUCCESS [  1.389 s]
[INFO] Apache Hadoop Project POM .......................... SUCCESS [  8.960 s]
[INFO] Apache Hadoop Annotations .......................... SUCCESS [ 10.748 s]
[INFO] Apache Hadoop Assemblies ........................... SUCCESS [  0.484 s]
[INFO] Apache Hadoop Project Dist POM ..................... SUCCESS [  2.283 s]
[INFO] Apache Hadoop Maven Plugins ........................ SUCCESS [  6.656 s]
[INFO] Apache Hadoop MiniKDC .............................. SUCCESS [ 16.127 s]
[INFO] Apache Hadoop Auth ................................. SUCCESS [  9.900 s]
[INFO] Apache Hadoop Auth Examples ........................ SUCCESS [  6.525 s]
[INFO] Apache Hadoop Common ............................... FAILURE [01:35 min]

(snip)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:25 min
[INFO] Finished at: 2020-01-24T12:22:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.8.1:jar (module-javadocs) on project hadoop-common: MavenReportException: Error while creating archive: 
[ERROR] Exit code: 1 - javadoc: error - class file for org.apache.yetus.audience.InterfaceAudience not found
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-0.el8_0.x86_64/jre/../bin/javadoc -J-Xmx768m @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/vagrant/bigtop/build/hadoop/rpm/BUILD/hadoop-2.10.0-src/hadoop-common-project/hadoop-common/target' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hadoop-common
error: Bad exit status from /var/tmp/rpm-tmp.dtCOJt (%build)


RPM build errors:
    Macro expanded in comment on line 754: %{_docdir}/libhdfs-%{hadoop_version}

    Bad exit status from /var/tmp/rpm-tmp.dtCOJt (%build)

> Task :hadoop-rpm FAILED
```

@iwasakims Have you ever seen this error?

**Comment by iwasakims** [comment]
> [ERROR] Exit code: 1 - javadoc: error - class file for org.apache.yetus.audience.InterfaceAudience not found

Hmm, I haven't seen the error. Hadoop itself does not use the org.apache.yetus.audience.InterfaceAudience in the code. I suspected [BIGTOP-3279](https://issues.apache.org/jira/browse/BIGTOP-3279) is relevant since zookeeper-3.4.13 uses the class but I can not reproduce the error by applying the patch of this PR to current trunk on CentOS7.

**Comment by iwasakims** [comment]
I could not reproduce the error on CentOS 8. Building fails due to another reason. We need the patch of [HADOOP-16739](https://issues.apache.org/jira/browse/HADOOP-16739) to fix this. 

```
[WARNING] /srcs/bigtop/build/hadoop/rpm/BUILD/hadoop-2.10.0-src/hadoop-tools/hadoop-pipes/src/main/native/utils/impl/SerialUtils.cc:22:10: fatal error: rpc/types.h: No such file or directory
[WARNING]  #include <rpc/types.h>
[WARNING]           ^~~~~~~~~~~~~
[WARNING] compilation terminated.
[WARNING] make[2]: *** [CMakeFiles/hadooputils.dir/build.make:76: CMakeFiles/hadooputils.dir/main/native/utils/impl/SerialUtils.cc.o] Error 1
```

I would like to address issues on RHEL/CentOS 8 in follow-up JIRAs.

**Comment by sekikn** [comment]
> I suspected BIGTOP-3279 is relevant since zookeeper-3.4.13 uses the class

You're right. The `./gradlew hadoop-pkg -Dbuildwithdeps=true` command I executed builds zk first, and [it installs the generated jars into the local .m2 repository](https://github.com/apache/bigtop/blob/ab8208768ce93c7c5ef119779e179e86dec3ac81/bigtop-packages/src/common/zookeeper/do-component-build#L30-L31).
I succeeded in building Hadoop by removing those jars and running the same command without the `-Dbuildwithdeps=true` option, so probably there's something wrong in the zk's build process. I'll address that in another issue.

> I would like to address issues on RHEL/CentOS 8 in follow-up JIRAs.

Sounds good to me. Will commit this PR.

**Pull request merged**
