### PR TITLE
BIGTOP-4031: drop ambari --bigtop-packages/src/common/bigtop-ambari-mpack/

### PR DESCRIPTION
**Pull request by MacChen01**
Delete the remaining code directory bigtop-packages/src/common/bigtop-ambari-mpack/, because ambari would be removed.

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (BIGTOP-4031)
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by MacChen01** [comment]
@guyuqi @sekikn 
please help review the code, thanks.
Associated  PR： https://github.com/apache/bigtop/pull/1208

**Comment by kevinw66** [comment]
I think we should remove the dir `/provisioner/bigtop-stack-provisioner` also.

**Review by kevinw66 — APPROVED** [review]
+1 LGTM

**Comment by MacChen01** [comment]
> +1 LGTM

Thanks

**Pull request merged**
