### PR TITLE
BIGTOP-3080. New shell script zkTxnLogToolkit.sh should be added to the install script

### PR DESCRIPTION
**Pull request by anmolnar**
I added `TxnLogToolkit` invocation script to Zk install script.

### CODE REVIEW

**Comment by anmolnar** [comment]
Anyone?

**Comment by evans-ye** [comment]
@anmolnar Please see my comment in https://issues.apache.org/jira/browse/BIGTOP-3080. Let's make sure we're aligned on the same page before we proceed the PR.

**Comment by anmolnar** [comment]
@evans-ye Sorry, I didn't notice that. Let me check.

**Comment by evans-ye** [comment]
@anmolnar zookeeper is upgrade to 3.4.13. Maybe the tool is available now. Could you check with it?

**Pull request closed without merging**
