### PR TITLE
BIGTOP-3955: add support for phoenix

### PR DESCRIPTION
**Pull request by MacChen01**
### Description of PR
Add support for phoenix component, the point modifed is:

   select the python3 on openeuler.

### How was this patch tested?
docker run --rm -v pwd:/home/bigtop --workdir /home/bigtop bigtop/slaves:trunk-openeuler-22.03-aarch64 bash -c '. /etc/profile.d/bigtop.sh; ./gradlew phoenix-pkg'

### For code changes:

- [ ] Does the title or this PR starts with the corresponding JIRA issue id (BIGTOP-3955)
- [ ] Make sure that newly added files do not have any licensing issues. When in doubt refer to https://www.apache.org/licenses/

### CODE REVIEW

**Comment by guyuqi** [comment]
1. Please rebase the PR to `openEuler-support`.
2. What about adding `Provisioner` first?  
We just add Hadoop build support for openEuler, but we have not verified hadoop smoke tests yet.
If we add `Provisioner` first, we could verify the smoke tests for every components on openEuler.
Thanks.

**Comment by MacChen01** [comment]
> 

1. I create the different dev branch for different componet, why rebase the PR to openEuler-support? how?
2. I can adding the Provisioner module, how to push it?
3. can't see the openEuler-support in my local env.
image

@guyuqi

**Comment by guyuqi** [comment]
This PR: 
image

Based on `openEuler-support`:
image

You should fist check out the branch to `openEuler-support` and then check out your local branch `openeuler_phoenix_dev`.

**Comment by MacChen01** [comment]
> This PR: image
> 
> Based on `openEuler-support`: image
> 
> You should fist check out the branch to `openEuler-support` and then check out your local branch `openeuler_phoenix_dev`.

sorry for that, it has changed to openEuler-support branch.

**Comment by MacChen01** [comment]
> 2. What about adding `Provisioner` first?
>    We just added Hadoop build support for openEuler, but we have not verified hadoop smoke tests yet.
>    If we add `Provisioner` first, we could verify the smoke tests for every components on openEuler.
>    Thanks. @MacChen01

The code of `Provisioner` is:
https://github.com/apache/bigtop/pull/1131

**Comment by guyuqi** [comment]
@MacChen01 
Since #1131 was merged, could you please run the phoenix smoke tests on OpenEuler to verify this PR? 
Thanks.

**Comment by MacChen01** [comment]
> @MacChen01 Since #1131 was merged, could you please run the phoenix smoke tests on OpenEuler to verify this PR? Thanks.

We will verify it as soon as possible.

**Comment by MacChen01** [comment]
> > @MacChen01 Since #1131 was merged, could you please run the phoenix smoke tests on OpenEuler to verify this PR? Thanks.
> 
> We will verify it as soon as possible.

we got a problem:
1. During the phoinex smoke test, the hbase service will be restarted, the _**systemctl restart hbase-master**_ command will be executed, and the error log:
image

2. Enter the docker container and use the **_systemctl_** command to check the hbase service status, and find that the hbase-master and hbase-regionserver services are abnormal, and the error log:
image

3. After analysis the problem, using the _**hasrestart**_ parameter function in puppet to specify the display mode of service restart, and modify the hbase component _**bigtop-deploy/puppet/modules/hadoop_hbase/manifests/init.pp**_ file as follows:
image

_Reference link_: https://www.puppet.com/docs/puppet/7/types/service.html#service-attribute-restart
image

4. The problem is resolved, and the smoke test result is successed in openEuler, Fedora is also ok using this way.
image


@guyuqi pls help check it.

**Comment by MacChen01** [comment]
> > > @MacChen01 Since #1131 was merged, could you please run the phoenix smoke tests on OpenEuler to verify this PR? Thanks.
> > 
> > 
> > We will verify it as soon as possible.
> 
> we got a problem:
> 
> 1. During the phoinex smoke test, the hbase service will be restarted, the _**systemctl restart hbase-master**_ command will be executed, and the error log:
>    image
> 2. Enter the docker container and use the **_systemctl_** command to check the hbase service status, and find that the hbase-master and hbase-regionserver services are abnormal, and the error log:
>    image
> 3. After analysis the problem, using the _**hasrestart**_ parameter function in puppet to specify the display mode of service restart, and modify the hbase component _**bigtop-deploy/puppet/modules/hadoop_hbase/manifests/init.pp**_ file as follows:
>    image
> 
> _Reference link_: https://www.puppet.com/docs/puppet/7/types/service.html#service-attribute-restart image
> 
> 4. The problem is resolved, and the smoke test result is successed in openEuler, Fedora is also ok using this way.
>    image
> 
> @guyuqi pls help check it.

@guyuqi pls review the solution.

**Comment by guyuqi** [comment]
`hasrestart`: 
_If you set hasrestart to true, Puppet will use the init script's restart command. You can provide an explicit command for restarting with the restart attribute. If you do neither, the service's stop and start commands will be used._

But the error log: `...PID * does not belong to service, ... PID file is not owned by ...` 
What is systemd version on your environment? (`systemd --version`)
I'm sorry I don't understand that you add the `hasrestart` attribute to fix this issue.

I also have the concern that the hbase `init.pp` is the public puppet script for all Distros. 
Have you tested it for the other Distros?

In my opinion, please try to delete the original Hbase master PID file first and restart it in OpenEuler.

**Comment by MacChen01** [comment]
> `hasrestart`: _If you set hasrestart to true, Puppet will use the init script's restart command. You can provide an explicit command for restarting with the restart attribute. If you do neither, the service's stop and start commands will be used._
> 
> But the error log: `...PID * does not belong to service, ... PID file is not owned by ...` What is systemd version on your environment? (`systemd --version`) I'm sorry I don't understand that you add the `hasrestart` attribute to fix this issue.
> 
> I also have the concern that the hbase `init.pp` is the public puppet script for all Distros. Have you tested it for the other Distros?
> 
> In my opinion, please try to delete the original Hbase master PID file first and restart it in OpenEuler.

ok, i will take your suggestion and verify it.

**Comment by MacChen01** [comment]
The **_/sbin/service_** cmd is used by default to start component(such as hbase, the phoenix dep) in openEuler, but the phoenix's smoke test deploy use the systemctl cmd would got error above mentioned.

image

I using the **_/sbin/service_** cmd to replace **_systemctl_** method on phoenix in openEuler is ok, code is:
```
  class hbase_master_restart {
    if ($operatingsystem == 'openEuler'){
      exec { "hbase_master_restart":
        command => "/sbin/service hbase-master restart",
        path    => ['/usr/bin', '/bin','/sbin'],
        cwd     => '/tmp',
        timeout => 3000,
        require => [
        File['phoenix-server-lib'],
          Service['hbase-master'],
         ],
     }
    } else {
        exec { "hbase_master_restart":
          command => "systemctl restart hbase-master",
          path    => ['/usr/bin', '/bin'],
          cwd     => '/tmp',
          timeout => 3000,
          require => [
            File['phoenix-server-lib'],
            Service['hbase-master'],
          ],
        }
    }
  }

```
The smoke test is ok:
image

@guyuqi

**Comment by guyuqi** [comment]
> The **_/sbin/service_** cmd is used by default to start component(such as hbase, the phoenix dep) in openEuler, but the phoenix's smoke test deploy use the **_systemctl_** cmd would got error above mentioned.
> 
> image
> 
> I using the **_/sbin/service_** cmd to replace **_systemctl_** method on phoenix in openEuler is ok, code is:
> 
> ```
>   class hbase_master_restart {
>     if ($operatingsystem == 'openEuler'){
>       exec { "hbase_master_restart":
>         command => "/sbin/service hbase-master restart",
>         path    => ['/usr/bin', '/bin','/sbin'],
>         cwd     => '/tmp',
>         timeout => 3000,
>         require => [
>         File['phoenix-server-lib'],
>           Service['hbase-master'],
>          ],
>      }
>     } else {
>         exec { "hbase_master_restart":
>           command => "systemctl restart hbase-master",
>           path    => ['/usr/bin', '/bin'],
>           cwd     => '/tmp',
>           timeout => 3000,
>           require => [
>             File['phoenix-server-lib'],
>             Service['hbase-master'],
>           ],
>         }
>     }
>   }
> ```
> 
> The smoke test is ok: image
> 
> @guyuqi

May I ask what's systemd version on openEuler?
`/usr/bin/systemctl --version`

**Comment by MacChen01** [comment]
> > The **_/sbin/service_** cmd is used by default to start component(such as hbase, the phoenix dep) in openEuler, but the phoenix's smoke test deploy use the **_systemctl_** cmd would got error above mentioned.
> > image
> > I using the **_/sbin/service_** cmd to replace **_systemctl_** method on phoenix in openEuler is ok, code is:
> > ```
> >   class hbase_master_restart {
> >     if ($operatingsystem == 'openEuler'){
> >       exec { "hbase_master_restart":
> >         command => "/sbin/service hbase-master restart",
> >         path    => ['/usr/bin', '/bin','/sbin'],
> >         cwd     => '/tmp',
> >         timeout => 3000,
> >         require => [
> >         File['phoenix-server-lib'],
> >           Service['hbase-master'],
> >          ],
> >      }
> >     } else {
> >         exec { "hbase_master_restart":
> >           command => "systemctl restart hbase-master",
> >           path    => ['/usr/bin', '/bin'],
> >           cwd     => '/tmp',
> >           timeout => 3000,
> >           require => [
> >             File['phoenix-server-lib'],
> >             Service['hbase-master'],
> >           ],
> >         }
> >     }
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The smoke test is ok: image
> > @guyuqi
> 
> May I ask what's systemd version on openEuler? `/usr/bin/systemctl --version`

The version of systemctl is v249. @guyuqi 
image

**Comment by MacChen01** [comment]
> It's same with Ubuntu-22.04.
For I'm not familar with openEuler and the codes would not affect the other Distro, I'm +1 with your code proposal.

@guyuqi  the modify code is:
commit: c2905d897ac80c900f9c0fda65526f7ba2cb36ae

phoenix smoke test successful
image

**Comment by guyuqi** [comment]
Merged, thanks.

**Comment by MacChen01** [comment]
> Merged, thanks.

Thanks for your review and advice.

**Pull request merged**
