### PR TITLE
BIGTOP-3677. Building HBase for CentOS 7 on arm64 and ppc64le fails due to missing libraries.

### PR DESCRIPTION
**Pull request by iwasakims**
https://issues.apache.org/jira/browse/BIGTOP-3677

```
[ERROR] /ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol/src/main/protobuf/Cell.proto [0:0]: /ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol/target/protoc-plugins/protoc-2.5.0.2-linux-aarch_64.exe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol/target/protoc-plugins/protoc-2.5.0.2-linux-aarch_64.exe)
/ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol/target/protoc-plugins/protoc-2.5.0.2-linux-aarch_64.exe: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol/target/protoc-plugins/protoc-2.5.0.2-linux-aarch_64.exe)
/ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol/target/protoc-plugins/protoc-2.5.0.2-linux-aarch_64.exe: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol/target/protoc-plugins/protoc-2.5.0.2-linux-aarch_64.exe)
/ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol/target/protoc-plugins/protoc-2.5.0.2-linux-aarch_64.exe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol/target/protoc-plugins/protoc-2.5.0.2-linux-aarch_64.exe)
```

HBASE-26470(https://github.com/apache/hbase/pull/3860) brought fork of protobuf (org.openlabtesting.protobuf) to support aarch64 but the provided protoc is not enough portable. Since we are using patched protobuf on our own, overriding the `external.protobuf.groupid` and `external.protoc.version` should be the fix.

### CODE REVIEW

**Comment by iwasakims** [comment]
worked for me on my CentOS 7 aarch64:

```                                                       
$ uname -a
Linux ip-172-33-0-128.ap-northeast-1.compute.internal 4.18.0-147.8.1.el7.aarch64 #1 SMP Wed Apr 15 18:13:44 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux

$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7:server"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
```

**Comment by iwasakims** [comment]
@sekikn Do you think we need the same fix for ppc64le too?

**Comment by sekikn** [comment]
@iwasakims Yes, it also occurred on ppc64le though I missed that. Would you update the PR?
https://ci.bigtop.apache.org/view/Releases/job/Bigtop-3.1.0/1/DISTRO=centos-7,PLATFORM=ppc64le-slave/console

**Comment by iwasakims** [comment]
I added the commit for covering ppc64le. Thanks, @sekikn.

**Comment by iwasakims** [comment]
Oops. The error is related to protoc 3.17.3. We need additional fix for ppc64le.

```
[[1;31mERROR[m] PROTOC FAILED: /ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol-shaded/target/protoc-plugins/protoc-3.17.3-linux-ppcle_64.exe: /lib64/ld64.so.2: version `GLIBC_2.22' not found (required by /ws/build/hbase/rpm/BUILD/hbase-2.4.11/hbase-protocol-shaded/target/protoc-plugins/protoc-3.17.3-linux-ppcle_64.exe)
```

**Comment by iwasakims** [comment]
The `internal.protobuf.version` was 3.5.1-1 on HBase 2.2.6. It is 3.17.3 on HBase 2.4.11 (by HBASE-24168 and HBASE-26541).

**Comment by iwasakims** [comment]
Since protobuf >= 3.7 supports ppc64le, I removed the protoc-3.5.1-add-support-for-ppc64le.patch in the latest commit.

**Comment by iwasakims** [comment]
@sekikn Could you try the latest patch on ppc64le machine in CI env? I do not have testing environment.

**Comment by sekikn** [comment]
+1, ensured the PR also works on ppc64le. Thanks @iwasakims!

**Comment by sekikn** [comment]
Merged into master and branch-3.1.

**Comment by sekikn** [comment]
@iwasakims I've just noticed that we had to align the protobuf version in other places too (e.g., https://ci.bigtop.apache.org/view/Releases/job/Bigtop-3.1.0/5/DISTRO=centos-7,PLATFORM=ppc64le-slave/console). I'm going to submit another PR as an addendum.

**Pull request merged**
