### PR TITLE
BIGTOP-3408. hadoop-docker.sh generates broken site.yaml from config.yaml containing multiple components.

### PR DESCRIPTION
**Pull request by iwasakims**
[Link to BIGTOP-3408](https://issues.apache.org/jira/browse/BIGTOP-3408)

### CODE REVIEW

**Comment by sekikn** [comment]
Nice catch, thanks!
+1 merged into master.

**Comment by evans-ye** [comment]
@iwasakims Thanks for the fix. I'm just curious why this was not a problem before. Do we changed something and trigger this? Things like OS versions?

**Comment by sekikn** [comment]
@evans-ye, this bug was recently introduced by #671 (I missed that...).

**Comment by iwasakims** [comment]
@evans-ye  The issue was in the code reading components from config.yaml. Specifying components from cmdline like `./hadoop-docker.sh -c 3 --stack 'hdfs,yarn,mapreduce'` was not affected.

**Comment by evans-ye** [comment]
OK, I see. So now we change it back. Thanks!

**Pull request merged**
